// Generated by spider on 2026-06-12 11:59:48.541158

class AppImages {
  AppImages._();

  static const String placeholder = 'assets/images/placeholder.png';
  static const String revahLogo = 'assets/images/revah_logo.png';
}
