// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: admin.sql

package db

import (
	"context"
	"time"
)

const createAuditLog = `-- name: CreateAuditLog :exec
INSERT INTO audit_log (actor_id, actor_name, action, target, detail)
VALUES ($1, $2, $3,
        $4, $5)
`

type CreateAuditLogParams struct {
	ActorID   *int64 `json:"actor_id"`
	ActorName string `json:"actor_name"`
	Action    string `json:"action"`
	Target    string `json:"target"`
	Detail    string `json:"detail"`
}

func (q *Queries) CreateAuditLog(ctx context.Context, arg CreateAuditLogParams) error {
	_, err := q.db.Exec(ctx, createAuditLog,
		arg.ActorID,
		arg.ActorName,
		arg.Action,
		arg.Target,
		arg.Detail,
	)
	return err
}

const getWorkspaceSettings = `-- name: GetWorkspaceSettings :one
SELECT id, name, allowed_domains, require_2fa, session_hours, updated_at
FROM workspace_settings WHERE id = 1
`

func (q *Queries) GetWorkspaceSettings(ctx context.Context) (WorkspaceSetting, error) {
	row := q.db.QueryRow(ctx, getWorkspaceSettings)
	var i WorkspaceSetting
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.AllowedDomains,
		&i.Require2fa,
		&i.SessionHours,
		&i.UpdatedAt,
	)
	return i, err
}

const listAdminMembers = `-- name: ListAdminMembers :many
SELECT id, email, full_name, role, avatar, is_active, two_factor_enabled,
       created_at
FROM users
ORDER BY created_at ASC
`

type ListAdminMembersRow struct {
	ID               int64     `json:"id"`
	Email            string    `json:"email"`
	FullName         string    `json:"full_name"`
	Role             string    `json:"role"`
	Avatar           string    `json:"avatar"`
	IsActive         bool      `json:"is_active"`
	TwoFactorEnabled bool      `json:"two_factor_enabled"`
	CreatedAt        time.Time `json:"created_at"`
}

func (q *Queries) ListAdminMembers(ctx context.Context) ([]ListAdminMembersRow, error) {
	rows, err := q.db.Query(ctx, listAdminMembers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAdminMembersRow{}
	for rows.Next() {
		var i ListAdminMembersRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.FullName,
			&i.Role,
			&i.Avatar,
			&i.IsActive,
			&i.TwoFactorEnabled,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAuditLog = `-- name: ListAuditLog :many
SELECT id, actor_id, actor_name, action, target, detail, created_at
FROM audit_log
ORDER BY created_at DESC
LIMIT 300
`

func (q *Queries) ListAuditLog(ctx context.Context) ([]AuditLog, error) {
	rows, err := q.db.Query(ctx, listAuditLog)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditLog{}
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.ActorID,
			&i.ActorName,
			&i.Action,
			&i.Target,
			&i.Detail,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setUserActive = `-- name: SetUserActive :one
UPDATE users SET is_active = $1, updated_at = now()
WHERE id = $2
RETURNING id, email, full_name, role, is_active
`

type SetUserActiveParams struct {
	IsActive bool  `json:"is_active"`
	ID       int64 `json:"id"`
}

type SetUserActiveRow struct {
	ID       int64  `json:"id"`
	Email    string `json:"email"`
	FullName string `json:"full_name"`
	Role     string `json:"role"`
	IsActive bool   `json:"is_active"`
}

func (q *Queries) SetUserActive(ctx context.Context, arg SetUserActiveParams) (SetUserActiveRow, error) {
	row := q.db.QueryRow(ctx, setUserActive, arg.IsActive, arg.ID)
	var i SetUserActiveRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.FullName,
		&i.Role,
		&i.IsActive,
	)
	return i, err
}

const setUserTwoFactor = `-- name: SetUserTwoFactor :exec
UPDATE users SET two_factor_enabled = $1,
       updated_at = now()
WHERE id = $2
`

type SetUserTwoFactorParams struct {
	TwoFactorEnabled bool  `json:"two_factor_enabled"`
	ID               int64 `json:"id"`
}

func (q *Queries) SetUserTwoFactor(ctx context.Context, arg SetUserTwoFactorParams) error {
	_, err := q.db.Exec(ctx, setUserTwoFactor, arg.TwoFactorEnabled, arg.ID)
	return err
}

const updateWorkspaceSettings = `-- name: UpdateWorkspaceSettings :exec
UPDATE workspace_settings
SET name = $1, allowed_domains = $2,
    require_2fa = $3, session_hours = $4,
    updated_at = now()
WHERE id = 1
`

type UpdateWorkspaceSettingsParams struct {
	Name           string `json:"name"`
	AllowedDomains string `json:"allowed_domains"`
	Require2fa     bool   `json:"require_2fa"`
	SessionHours   int32  `json:"session_hours"`
}

func (q *Queries) UpdateWorkspaceSettings(ctx context.Context, arg UpdateWorkspaceSettingsParams) error {
	_, err := q.db.Exec(ctx, updateWorkspaceSettings,
		arg.Name,
		arg.AllowedDomains,
		arg.Require2fa,
		arg.SessionHours,
	)
	return err
}
