// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: approvals.sql

package db

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const createApproval = `-- name: CreateApproval :one
INSERT INTO approvals (
    subject_type, subject_id, subject_title, requester_id, approver_id, note)
VALUES (
    $1, $2, $3,
    $4, $5, $6)
RETURNING id, subject_type, subject_id, subject_title, requester_id, approver_id, status, note, decided_at, created_at
`

type CreateApprovalParams struct {
	SubjectType  string `json:"subject_type"`
	SubjectID    int64  `json:"subject_id"`
	SubjectTitle string `json:"subject_title"`
	RequesterID  int64  `json:"requester_id"`
	ApproverID   int64  `json:"approver_id"`
	Note         string `json:"note"`
}

func (q *Queries) CreateApproval(ctx context.Context, arg CreateApprovalParams) (Approval, error) {
	row := q.db.QueryRow(ctx, createApproval,
		arg.SubjectType,
		arg.SubjectID,
		arg.SubjectTitle,
		arg.RequesterID,
		arg.ApproverID,
		arg.Note,
	)
	var i Approval
	err := row.Scan(
		&i.ID,
		&i.SubjectType,
		&i.SubjectID,
		&i.SubjectTitle,
		&i.RequesterID,
		&i.ApproverID,
		&i.Status,
		&i.Note,
		&i.DecidedAt,
		&i.CreatedAt,
	)
	return i, err
}

const decideApproval = `-- name: DecideApproval :one
UPDATE approvals
SET status = $1, decided_at = now()
WHERE id = $2
RETURNING id, subject_type, subject_id, subject_title, requester_id, approver_id, status, note, decided_at, created_at
`

type DecideApprovalParams struct {
	Status string `json:"status"`
	ID     int64  `json:"id"`
}

func (q *Queries) DecideApproval(ctx context.Context, arg DecideApprovalParams) (Approval, error) {
	row := q.db.QueryRow(ctx, decideApproval, arg.Status, arg.ID)
	var i Approval
	err := row.Scan(
		&i.ID,
		&i.SubjectType,
		&i.SubjectID,
		&i.SubjectTitle,
		&i.RequesterID,
		&i.ApproverID,
		&i.Status,
		&i.Note,
		&i.DecidedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getApproval = `-- name: GetApproval :one
SELECT id, subject_type, subject_id, subject_title, requester_id, approver_id, status, note, decided_at, created_at FROM approvals WHERE id = $1
`

func (q *Queries) GetApproval(ctx context.Context, id int64) (Approval, error) {
	row := q.db.QueryRow(ctx, getApproval, id)
	var i Approval
	err := row.Scan(
		&i.ID,
		&i.SubjectType,
		&i.SubjectID,
		&i.SubjectTitle,
		&i.RequesterID,
		&i.ApproverID,
		&i.Status,
		&i.Note,
		&i.DecidedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listApprovalsForSubject = `-- name: ListApprovalsForSubject :many
SELECT a.id, a.subject_type, a.subject_id, a.subject_title, a.requester_id, a.approver_id, a.status, a.note, a.decided_at, a.created_at,
       ru.full_name AS requester_name,
       au.full_name AS approver_name
FROM approvals a
JOIN users ru ON ru.id = a.requester_id
JOIN users au ON au.id = a.approver_id
WHERE a.subject_type = $1
  AND a.subject_id = $2
ORDER BY a.created_at DESC
`

type ListApprovalsForSubjectParams struct {
	SubjectType string `json:"subject_type"`
	SubjectID   int64  `json:"subject_id"`
}

type ListApprovalsForSubjectRow struct {
	ID            int64              `json:"id"`
	SubjectType   string             `json:"subject_type"`
	SubjectID     int64              `json:"subject_id"`
	SubjectTitle  string             `json:"subject_title"`
	RequesterID   int64              `json:"requester_id"`
	ApproverID    int64              `json:"approver_id"`
	Status        string             `json:"status"`
	Note          string             `json:"note"`
	DecidedAt     pgtype.Timestamptz `json:"decided_at"`
	CreatedAt     time.Time          `json:"created_at"`
	RequesterName string             `json:"requester_name"`
	ApproverName  string             `json:"approver_name"`
}

func (q *Queries) ListApprovalsForSubject(ctx context.Context, arg ListApprovalsForSubjectParams) ([]ListApprovalsForSubjectRow, error) {
	rows, err := q.db.Query(ctx, listApprovalsForSubject, arg.SubjectType, arg.SubjectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListApprovalsForSubjectRow{}
	for rows.Next() {
		var i ListApprovalsForSubjectRow
		if err := rows.Scan(
			&i.ID,
			&i.SubjectType,
			&i.SubjectID,
			&i.SubjectTitle,
			&i.RequesterID,
			&i.ApproverID,
			&i.Status,
			&i.Note,
			&i.DecidedAt,
			&i.CreatedAt,
			&i.RequesterName,
			&i.ApproverName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMyApprovalRequests = `-- name: ListMyApprovalRequests :many
SELECT a.id, a.subject_type, a.subject_id, a.subject_title, a.requester_id, a.approver_id, a.status, a.note, a.decided_at, a.created_at, u.full_name AS approver_name
FROM approvals a
JOIN users u ON u.id = a.approver_id
WHERE a.requester_id = $1
ORDER BY a.created_at DESC
LIMIT 50
`

type ListMyApprovalRequestsRow struct {
	ID           int64              `json:"id"`
	SubjectType  string             `json:"subject_type"`
	SubjectID    int64              `json:"subject_id"`
	SubjectTitle string             `json:"subject_title"`
	RequesterID  int64              `json:"requester_id"`
	ApproverID   int64              `json:"approver_id"`
	Status       string             `json:"status"`
	Note         string             `json:"note"`
	DecidedAt    pgtype.Timestamptz `json:"decided_at"`
	CreatedAt    time.Time          `json:"created_at"`
	ApproverName string             `json:"approver_name"`
}

func (q *Queries) ListMyApprovalRequests(ctx context.Context, requesterID int64) ([]ListMyApprovalRequestsRow, error) {
	rows, err := q.db.Query(ctx, listMyApprovalRequests, requesterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMyApprovalRequestsRow{}
	for rows.Next() {
		var i ListMyApprovalRequestsRow
		if err := rows.Scan(
			&i.ID,
			&i.SubjectType,
			&i.SubjectID,
			&i.SubjectTitle,
			&i.RequesterID,
			&i.ApproverID,
			&i.Status,
			&i.Note,
			&i.DecidedAt,
			&i.CreatedAt,
			&i.ApproverName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingApprovals = `-- name: ListPendingApprovals :many
SELECT a.id, a.subject_type, a.subject_id, a.subject_title, a.requester_id, a.approver_id, a.status, a.note, a.decided_at, a.created_at, u.full_name AS requester_name
FROM approvals a
JOIN users u ON u.id = a.requester_id
WHERE a.approver_id = $1 AND a.status = 'pending'
ORDER BY a.created_at DESC
`

type ListPendingApprovalsRow struct {
	ID            int64              `json:"id"`
	SubjectType   string             `json:"subject_type"`
	SubjectID     int64              `json:"subject_id"`
	SubjectTitle  string             `json:"subject_title"`
	RequesterID   int64              `json:"requester_id"`
	ApproverID    int64              `json:"approver_id"`
	Status        string             `json:"status"`
	Note          string             `json:"note"`
	DecidedAt     pgtype.Timestamptz `json:"decided_at"`
	CreatedAt     time.Time          `json:"created_at"`
	RequesterName string             `json:"requester_name"`
}

func (q *Queries) ListPendingApprovals(ctx context.Context, approverID int64) ([]ListPendingApprovalsRow, error) {
	rows, err := q.db.Query(ctx, listPendingApprovals, approverID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPendingApprovalsRow{}
	for rows.Next() {
		var i ListPendingApprovalsRow
		if err := rows.Scan(
			&i.ID,
			&i.SubjectType,
			&i.SubjectID,
			&i.SubjectTitle,
			&i.RequesterID,
			&i.ApproverID,
			&i.Status,
			&i.Note,
			&i.DecidedAt,
			&i.CreatedAt,
			&i.RequesterName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
