// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: assets.sql

package db

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAsset = `-- name: CreateAsset :one
INSERT INTO assets (name, kind, status, identifier, vendor, assignee_id,
                    cost_cents, purchased_on, expires_on, notes)
VALUES ($1, $2, $3, $4,
        $5, $6, $7,
        $8, $9, $10)
RETURNING id, name, kind, status, identifier, vendor, assignee_id, cost_cents, purchased_on, expires_on, notes, created_at
`

type CreateAssetParams struct {
	Name        string      `json:"name"`
	Kind        string      `json:"kind"`
	Status      string      `json:"status"`
	Identifier  string      `json:"identifier"`
	Vendor      string      `json:"vendor"`
	AssigneeID  *int64      `json:"assignee_id"`
	CostCents   int64       `json:"cost_cents"`
	PurchasedOn pgtype.Date `json:"purchased_on"`
	ExpiresOn   pgtype.Date `json:"expires_on"`
	Notes       string      `json:"notes"`
}

func (q *Queries) CreateAsset(ctx context.Context, arg CreateAssetParams) (Asset, error) {
	row := q.db.QueryRow(ctx, createAsset,
		arg.Name,
		arg.Kind,
		arg.Status,
		arg.Identifier,
		arg.Vendor,
		arg.AssigneeID,
		arg.CostCents,
		arg.PurchasedOn,
		arg.ExpiresOn,
		arg.Notes,
	)
	var i Asset
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Kind,
		&i.Status,
		&i.Identifier,
		&i.Vendor,
		&i.AssigneeID,
		&i.CostCents,
		&i.PurchasedOn,
		&i.ExpiresOn,
		&i.Notes,
		&i.CreatedAt,
	)
	return i, err
}

const deleteAsset = `-- name: DeleteAsset :exec
DELETE FROM assets WHERE id = $1
`

func (q *Queries) DeleteAsset(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteAsset, id)
	return err
}

const listAssets = `-- name: ListAssets :many
SELECT a.id, a.name, a.kind, a.status, a.identifier, a.vendor, a.assignee_id, a.cost_cents, a.purchased_on, a.expires_on, a.notes, a.created_at, COALESCE(u.full_name, '')::text AS assignee_name
FROM assets a
LEFT JOIN users u ON u.id = a.assignee_id
ORDER BY a.name, a.id
`

type ListAssetsRow struct {
	ID           int64       `json:"id"`
	Name         string      `json:"name"`
	Kind         string      `json:"kind"`
	Status       string      `json:"status"`
	Identifier   string      `json:"identifier"`
	Vendor       string      `json:"vendor"`
	AssigneeID   *int64      `json:"assignee_id"`
	CostCents    int64       `json:"cost_cents"`
	PurchasedOn  pgtype.Date `json:"purchased_on"`
	ExpiresOn    pgtype.Date `json:"expires_on"`
	Notes        string      `json:"notes"`
	CreatedAt    time.Time   `json:"created_at"`
	AssigneeName string      `json:"assignee_name"`
}

func (q *Queries) ListAssets(ctx context.Context) ([]ListAssetsRow, error) {
	rows, err := q.db.Query(ctx, listAssets)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAssetsRow{}
	for rows.Next() {
		var i ListAssetsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Kind,
			&i.Status,
			&i.Identifier,
			&i.Vendor,
			&i.AssigneeID,
			&i.CostCents,
			&i.PurchasedOn,
			&i.ExpiresOn,
			&i.Notes,
			&i.CreatedAt,
			&i.AssigneeName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAsset = `-- name: UpdateAsset :one
UPDATE assets
SET name = $1,
    kind = $2,
    status = $3,
    identifier = $4,
    vendor = $5,
    assignee_id = $6,
    cost_cents = $7,
    purchased_on = $8,
    expires_on = $9,
    notes = $10
WHERE id = $11
RETURNING id, name, kind, status, identifier, vendor, assignee_id, cost_cents, purchased_on, expires_on, notes, created_at
`

type UpdateAssetParams struct {
	Name        string      `json:"name"`
	Kind        string      `json:"kind"`
	Status      string      `json:"status"`
	Identifier  string      `json:"identifier"`
	Vendor      string      `json:"vendor"`
	AssigneeID  *int64      `json:"assignee_id"`
	CostCents   int64       `json:"cost_cents"`
	PurchasedOn pgtype.Date `json:"purchased_on"`
	ExpiresOn   pgtype.Date `json:"expires_on"`
	Notes       string      `json:"notes"`
	ID          int64       `json:"id"`
}

func (q *Queries) UpdateAsset(ctx context.Context, arg UpdateAssetParams) (Asset, error) {
	row := q.db.QueryRow(ctx, updateAsset,
		arg.Name,
		arg.Kind,
		arg.Status,
		arg.Identifier,
		arg.Vendor,
		arg.AssigneeID,
		arg.CostCents,
		arg.PurchasedOn,
		arg.ExpiresOn,
		arg.Notes,
		arg.ID,
	)
	var i Asset
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Kind,
		&i.Status,
		&i.Identifier,
		&i.Vendor,
		&i.AssigneeID,
		&i.CostCents,
		&i.PurchasedOn,
		&i.ExpiresOn,
		&i.Notes,
		&i.CreatedAt,
	)
	return i, err
}
