// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: attachments.sql

package db

import (
	"context"
	"time"
)

const createAttachment = `-- name: CreateAttachment :one
INSERT INTO attachments (task_id, uploader_id, filename, stored_name, content_type, size)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, task_id, uploader_id, filename, stored_name, content_type, size, created_at
`

type CreateAttachmentParams struct {
	TaskID      int64  `json:"task_id"`
	UploaderID  *int64 `json:"uploader_id"`
	Filename    string `json:"filename"`
	StoredName  string `json:"stored_name"`
	ContentType string `json:"content_type"`
	Size        int64  `json:"size"`
}

func (q *Queries) CreateAttachment(ctx context.Context, arg CreateAttachmentParams) (Attachment, error) {
	row := q.db.QueryRow(ctx, createAttachment,
		arg.TaskID,
		arg.UploaderID,
		arg.Filename,
		arg.StoredName,
		arg.ContentType,
		arg.Size,
	)
	var i Attachment
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.UploaderID,
		&i.Filename,
		&i.StoredName,
		&i.ContentType,
		&i.Size,
		&i.CreatedAt,
	)
	return i, err
}

const deleteAttachment = `-- name: DeleteAttachment :exec
DELETE FROM attachments
WHERE id = $1
`

func (q *Queries) DeleteAttachment(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteAttachment, id)
	return err
}

const getAttachment = `-- name: GetAttachment :one
SELECT id, task_id, uploader_id, filename, stored_name, content_type, size, created_at FROM attachments
WHERE id = $1
`

func (q *Queries) GetAttachment(ctx context.Context, id int64) (Attachment, error) {
	row := q.db.QueryRow(ctx, getAttachment, id)
	var i Attachment
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.UploaderID,
		&i.Filename,
		&i.StoredName,
		&i.ContentType,
		&i.Size,
		&i.CreatedAt,
	)
	return i, err
}

const listAttachments = `-- name: ListAttachments :many
SELECT a.id, a.task_id, a.uploader_id, a.filename, a.content_type, a.size,
       a.created_at, u.full_name AS uploader_name
FROM attachments a
LEFT JOIN users u ON u.id = a.uploader_id
WHERE a.task_id = $1
ORDER BY a.created_at DESC
`

type ListAttachmentsRow struct {
	ID           int64     `json:"id"`
	TaskID       int64     `json:"task_id"`
	UploaderID   *int64    `json:"uploader_id"`
	Filename     string    `json:"filename"`
	ContentType  string    `json:"content_type"`
	Size         int64     `json:"size"`
	CreatedAt    time.Time `json:"created_at"`
	UploaderName *string   `json:"uploader_name"`
}

func (q *Queries) ListAttachments(ctx context.Context, taskID int64) ([]ListAttachmentsRow, error) {
	rows, err := q.db.Query(ctx, listAttachments, taskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAttachmentsRow{}
	for rows.Next() {
		var i ListAttachmentsRow
		if err := rows.Scan(
			&i.ID,
			&i.TaskID,
			&i.UploaderID,
			&i.Filename,
			&i.ContentType,
			&i.Size,
			&i.CreatedAt,
			&i.UploaderName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
