// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: automation.sql

package db

import (
	"context"
)

const createAutomationRule = `-- name: CreateAutomationRule :one
INSERT INTO automation_rules (name, enabled, trigger, conditions, actions,
                              created_by)
VALUES ($1, $2, $3,
        $4, $5, $6)
RETURNING id, name, enabled, trigger, conditions, actions, created_by, created_at, updated_at
`

type CreateAutomationRuleParams struct {
	Name       string `json:"name"`
	Enabled    bool   `json:"enabled"`
	Trigger    string `json:"trigger"`
	Conditions string `json:"conditions"`
	Actions    string `json:"actions"`
	CreatedBy  *int64 `json:"created_by"`
}

func (q *Queries) CreateAutomationRule(ctx context.Context, arg CreateAutomationRuleParams) (AutomationRule, error) {
	row := q.db.QueryRow(ctx, createAutomationRule,
		arg.Name,
		arg.Enabled,
		arg.Trigger,
		arg.Conditions,
		arg.Actions,
		arg.CreatedBy,
	)
	var i AutomationRule
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Enabled,
		&i.Trigger,
		&i.Conditions,
		&i.Actions,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteAutomationRule = `-- name: DeleteAutomationRule :exec
DELETE FROM automation_rules WHERE id = $1
`

func (q *Queries) DeleteAutomationRule(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteAutomationRule, id)
	return err
}

const getAutomationRule = `-- name: GetAutomationRule :one
SELECT id, name, enabled, trigger, conditions, actions, created_by, created_at, updated_at FROM automation_rules WHERE id = $1
`

func (q *Queries) GetAutomationRule(ctx context.Context, id int64) (AutomationRule, error) {
	row := q.db.QueryRow(ctx, getAutomationRule, id)
	var i AutomationRule
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Enabled,
		&i.Trigger,
		&i.Conditions,
		&i.Actions,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAutomationRules = `-- name: ListAutomationRules :many
SELECT id, name, enabled, trigger, conditions, actions, created_by, created_at, updated_at FROM automation_rules ORDER BY created_at DESC
`

func (q *Queries) ListAutomationRules(ctx context.Context) ([]AutomationRule, error) {
	rows, err := q.db.Query(ctx, listAutomationRules)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AutomationRule{}
	for rows.Next() {
		var i AutomationRule
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Enabled,
			&i.Trigger,
			&i.Conditions,
			&i.Actions,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEnabledRulesByTrigger = `-- name: ListEnabledRulesByTrigger :many
SELECT id, name, enabled, trigger, conditions, actions, created_by, created_at, updated_at FROM automation_rules
WHERE enabled = true AND trigger = $1
ORDER BY id
`

func (q *Queries) ListEnabledRulesByTrigger(ctx context.Context, trigger string) ([]AutomationRule, error) {
	rows, err := q.db.Query(ctx, listEnabledRulesByTrigger, trigger)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AutomationRule{}
	for rows.Next() {
		var i AutomationRule
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Enabled,
			&i.Trigger,
			&i.Conditions,
			&i.Actions,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setAutomationRuleEnabled = `-- name: SetAutomationRuleEnabled :exec
UPDATE automation_rules SET enabled = $1, updated_at = now()
WHERE id = $2
`

type SetAutomationRuleEnabledParams struct {
	Enabled bool  `json:"enabled"`
	ID      int64 `json:"id"`
}

func (q *Queries) SetAutomationRuleEnabled(ctx context.Context, arg SetAutomationRuleEnabledParams) error {
	_, err := q.db.Exec(ctx, setAutomationRuleEnabled, arg.Enabled, arg.ID)
	return err
}

const updateAutomationRule = `-- name: UpdateAutomationRule :exec
UPDATE automation_rules
SET name = $1, enabled = $2,
    trigger = $3, conditions = $4,
    actions = $5, updated_at = now()
WHERE id = $6
`

type UpdateAutomationRuleParams struct {
	Name       string `json:"name"`
	Enabled    bool   `json:"enabled"`
	Trigger    string `json:"trigger"`
	Conditions string `json:"conditions"`
	Actions    string `json:"actions"`
	ID         int64  `json:"id"`
}

func (q *Queries) UpdateAutomationRule(ctx context.Context, arg UpdateAutomationRuleParams) error {
	_, err := q.db.Exec(ctx, updateAutomationRule,
		arg.Name,
		arg.Enabled,
		arg.Trigger,
		arg.Conditions,
		arg.Actions,
		arg.ID,
	)
	return err
}
