// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: budgets.sql

package db

import (
	"context"
	"time"
)

const deleteBudget = `-- name: DeleteBudget :exec
DELETE FROM project_budgets WHERE id = $1
`

func (q *Queries) DeleteBudget(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteBudget, id)
	return err
}

const listBudgets = `-- name: ListBudgets :many
SELECT b.id, b.project_id, b.amount_cents, b.hourly_rate_cents, b.notes,
       b.created_at, b.updated_at,
       COALESCE(p.name, '')::text AS project_name,
       COALESCE((
           SELECT SUM(e.amount_cents) FROM expenses e
           WHERE e.project_id = b.project_id
             AND e.status IN ('approved', 'reimbursed')
       ), 0)::bigint AS expense_cents,
       COALESCE((
           SELECT SUM(t.minutes) FROM time_entries t
           JOIN tasks tk ON tk.id = t.task_id
           WHERE tk.project_id = b.project_id AND t.billable = true
       ), 0)::bigint AS billable_minutes
FROM project_budgets b
LEFT JOIN projects p ON p.id = b.project_id
ORDER BY p.name, b.id
`

type ListBudgetsRow struct {
	ID              int64     `json:"id"`
	ProjectID       int64     `json:"project_id"`
	AmountCents     int64     `json:"amount_cents"`
	HourlyRateCents int64     `json:"hourly_rate_cents"`
	Notes           string    `json:"notes"`
	CreatedAt       time.Time `json:"created_at"`
	UpdatedAt       time.Time `json:"updated_at"`
	ProjectName     string    `json:"project_name"`
	ExpenseCents    int64     `json:"expense_cents"`
	BillableMinutes int64     `json:"billable_minutes"`
}

func (q *Queries) ListBudgets(ctx context.Context) ([]ListBudgetsRow, error) {
	rows, err := q.db.Query(ctx, listBudgets)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBudgetsRow{}
	for rows.Next() {
		var i ListBudgetsRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.AmountCents,
			&i.HourlyRateCents,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ProjectName,
			&i.ExpenseCents,
			&i.BillableMinutes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertBudget = `-- name: UpsertBudget :one
INSERT INTO project_budgets (project_id, amount_cents, hourly_rate_cents,
                             notes, updated_at)
VALUES ($1, $2,
        $3, $4, now())
ON CONFLICT (project_id) DO UPDATE
SET amount_cents = EXCLUDED.amount_cents,
    hourly_rate_cents = EXCLUDED.hourly_rate_cents,
    notes = EXCLUDED.notes,
    updated_at = now()
RETURNING id, project_id, amount_cents, hourly_rate_cents, notes, created_at, updated_at
`

type UpsertBudgetParams struct {
	ProjectID       int64  `json:"project_id"`
	AmountCents     int64  `json:"amount_cents"`
	HourlyRateCents int64  `json:"hourly_rate_cents"`
	Notes           string `json:"notes"`
}

func (q *Queries) UpsertBudget(ctx context.Context, arg UpsertBudgetParams) (ProjectBudget, error) {
	row := q.db.QueryRow(ctx, upsertBudget,
		arg.ProjectID,
		arg.AmountCents,
		arg.HourlyRateCents,
		arg.Notes,
	)
	var i ProjectBudget
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.AmountCents,
		&i.HourlyRateCents,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
