// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: calendar.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const clearUserCalendarToken = `-- name: ClearUserCalendarToken :exec
UPDATE users SET calendar_token = NULL WHERE id = $1
`

func (q *Queries) ClearUserCalendarToken(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, clearUserCalendarToken, id)
	return err
}

const getUserByCalendarToken = `-- name: GetUserByCalendarToken :one
SELECT id, COALESCE(full_name, '')::text AS full_name
FROM users WHERE calendar_token = $1
`

type GetUserByCalendarTokenRow struct {
	ID       int64  `json:"id"`
	FullName string `json:"full_name"`
}

func (q *Queries) GetUserByCalendarToken(ctx context.Context, calendarToken *string) (GetUserByCalendarTokenRow, error) {
	row := q.db.QueryRow(ctx, getUserByCalendarToken, calendarToken)
	var i GetUserByCalendarTokenRow
	err := row.Scan(&i.ID, &i.FullName)
	return i, err
}

const getUserCalendarToken = `-- name: GetUserCalendarToken :one
SELECT COALESCE(calendar_token, '')::text FROM users WHERE id = $1
`

func (q *Queries) GetUserCalendarToken(ctx context.Context, id int64) (string, error) {
	row := q.db.QueryRow(ctx, getUserCalendarToken, id)
	var column_1 string
	err := row.Scan(&column_1)
	return column_1, err
}

const listCalendarTasks = `-- name: ListCalendarTasks :many
SELECT DISTINCT t.id, t.title, t.description, t.status, t.due_date
FROM tasks t
LEFT JOIN task_assignees ta ON ta.task_id = t.id
WHERE t.due_date IS NOT NULL
  AND (ta.user_id = $1 OR t.assignee_id = $1)
ORDER BY t.due_date
`

type ListCalendarTasksRow struct {
	ID          int64              `json:"id"`
	Title       string             `json:"title"`
	Description string             `json:"description"`
	Status      string             `json:"status"`
	DueDate     pgtype.Timestamptz `json:"due_date"`
}

func (q *Queries) ListCalendarTasks(ctx context.Context, userID int64) ([]ListCalendarTasksRow, error) {
	rows, err := q.db.Query(ctx, listCalendarTasks, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCalendarTasksRow{}
	for rows.Next() {
		var i ListCalendarTasksRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.DueDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setUserCalendarToken = `-- name: SetUserCalendarToken :exec
UPDATE users SET calendar_token = $1 WHERE id = $2
`

type SetUserCalendarTokenParams struct {
	Token *string `json:"token"`
	ID    int64   `json:"id"`
}

func (q *Queries) SetUserCalendarToken(ctx context.Context, arg SetUserCalendarTokenParams) error {
	_, err := q.db.Exec(ctx, setUserCalendarToken, arg.Token, arg.ID)
	return err
}
