// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: calendar_events.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCalendarEvent = `-- name: CreateCalendarEvent :one
INSERT INTO calendar_events (user_id, event_date, kind, title, note,
                             start_time, end_time, repeat_in, remind_days,
                             next_occurs)
VALUES ($1, $2, $3,
        $4, $5, $6,
        $7, $8, $9,
        $10)
RETURNING id, user_id, event_date, kind, title, note, start_time, end_time, repeat_in, remind_days, next_occurs, reminded_at, created_at, updated_at
`

type CreateCalendarEventParams struct {
	UserID     int64       `json:"user_id"`
	EventDate  pgtype.Date `json:"event_date"`
	Kind       string      `json:"kind"`
	Title      string      `json:"title"`
	Note       string      `json:"note"`
	StartTime  pgtype.Time `json:"start_time"`
	EndTime    pgtype.Time `json:"end_time"`
	RepeatIn   string      `json:"repeat_in"`
	RemindDays *int32      `json:"remind_days"`
	NextOccurs pgtype.Date `json:"next_occurs"`
}

func (q *Queries) CreateCalendarEvent(ctx context.Context, arg CreateCalendarEventParams) (CalendarEvent, error) {
	row := q.db.QueryRow(ctx, createCalendarEvent,
		arg.UserID,
		arg.EventDate,
		arg.Kind,
		arg.Title,
		arg.Note,
		arg.StartTime,
		arg.EndTime,
		arg.RepeatIn,
		arg.RemindDays,
		arg.NextOccurs,
	)
	var i CalendarEvent
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.EventDate,
		&i.Kind,
		&i.Title,
		&i.Note,
		&i.StartTime,
		&i.EndTime,
		&i.RepeatIn,
		&i.RemindDays,
		&i.NextOccurs,
		&i.RemindedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteCalendarEvent = `-- name: DeleteCalendarEvent :execrows
DELETE FROM calendar_events
WHERE id = $1 AND user_id = $2
`

type DeleteCalendarEventParams struct {
	ID     int64 `json:"id"`
	UserID int64 `json:"user_id"`
}

func (q *Queries) DeleteCalendarEvent(ctx context.Context, arg DeleteCalendarEventParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteCalendarEvent, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const dueCalendarReminders = `-- name: DueCalendarReminders :many
SELECT id, user_id, event_date, kind, title, note, start_time, end_time, repeat_in, remind_days, next_occurs, reminded_at, created_at, updated_at FROM calendar_events
WHERE remind_days IS NOT NULL
  AND reminded_at IS NULL
  AND next_occurs IS NOT NULL
  AND next_occurs <= CURRENT_DATE + remind_days
ORDER BY next_occurs, id
LIMIT 500
`

// Events whose reminder is due: the next occurrence is within remind_days, and
// nobody has been told yet.
func (q *Queries) DueCalendarReminders(ctx context.Context) ([]CalendarEvent, error) {
	rows, err := q.db.Query(ctx, dueCalendarReminders)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CalendarEvent{}
	for rows.Next() {
		var i CalendarEvent
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.EventDate,
			&i.Kind,
			&i.Title,
			&i.Note,
			&i.StartTime,
			&i.EndTime,
			&i.RepeatIn,
			&i.RemindDays,
			&i.NextOccurs,
			&i.RemindedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCalendarEvent = `-- name: GetCalendarEvent :one
SELECT id, user_id, event_date, kind, title, note, start_time, end_time, repeat_in, remind_days, next_occurs, reminded_at, created_at, updated_at FROM calendar_events WHERE id = $1
`

func (q *Queries) GetCalendarEvent(ctx context.Context, id int64) (CalendarEvent, error) {
	row := q.db.QueryRow(ctx, getCalendarEvent, id)
	var i CalendarEvent
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.EventDate,
		&i.Kind,
		&i.Title,
		&i.Note,
		&i.StartTime,
		&i.EndTime,
		&i.RepeatIn,
		&i.RemindDays,
		&i.NextOccurs,
		&i.RemindedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCalendarEvents = `-- name: ListCalendarEvents :many
SELECT id, user_id, event_date, kind, title, note, start_time, end_time, repeat_in, remind_days, next_occurs, reminded_at, created_at, updated_at FROM calendar_events
WHERE user_id = $1
  AND event_date >= $2
  AND event_date <= $3
ORDER BY event_date, start_time NULLS FIRST, id
`

type ListCalendarEventsParams struct {
	UserID   int64       `json:"user_id"`
	FromDate pgtype.Date `json:"from_date"`
	ToDate   pgtype.Date `json:"to_date"`
}

func (q *Queries) ListCalendarEvents(ctx context.Context, arg ListCalendarEventsParams) ([]CalendarEvent, error) {
	rows, err := q.db.Query(ctx, listCalendarEvents, arg.UserID, arg.FromDate, arg.ToDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CalendarEvent{}
	for rows.Next() {
		var i CalendarEvent
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.EventDate,
			&i.Kind,
			&i.Title,
			&i.Note,
			&i.StartTime,
			&i.EndTime,
			&i.RepeatIn,
			&i.RemindDays,
			&i.NextOccurs,
			&i.RemindedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRepeatingCalendarEvents = `-- name: ListRepeatingCalendarEvents :many
SELECT id, user_id, event_date, kind, title, note, start_time, end_time, repeat_in, remind_days, next_occurs, reminded_at, created_at, updated_at FROM calendar_events
WHERE user_id = $1
  AND repeat_in <> 'none'
ORDER BY event_date, id
`

// Every repeating event the user owns, whatever its original date — a birthday
// in 1994 must still show on this year's calendar.
func (q *Queries) ListRepeatingCalendarEvents(ctx context.Context, userID int64) ([]CalendarEvent, error) {
	rows, err := q.db.Query(ctx, listRepeatingCalendarEvents, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CalendarEvent{}
	for rows.Next() {
		var i CalendarEvent
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.EventDate,
			&i.Kind,
			&i.Title,
			&i.Note,
			&i.StartTime,
			&i.EndTime,
			&i.RepeatIn,
			&i.RemindDays,
			&i.NextOccurs,
			&i.RemindedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markCalendarEventReminded = `-- name: MarkCalendarEventReminded :exec
UPDATE calendar_events SET reminded_at = now() WHERE id = $1
`

func (q *Queries) MarkCalendarEventReminded(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, markCalendarEventReminded, id)
	return err
}

const rollCalendarEvent = `-- name: RollCalendarEvent :exec
UPDATE calendar_events
SET next_occurs = $1, reminded_at = NULL
WHERE id = $2
`

type RollCalendarEventParams struct {
	NextOccurs pgtype.Date `json:"next_occurs"`
	ID         int64       `json:"id"`
}

// Rolls a repeating event on to its next occurrence and clears the reminder
// flag, so it can be reminded about again next year.
func (q *Queries) RollCalendarEvent(ctx context.Context, arg RollCalendarEventParams) error {
	_, err := q.db.Exec(ctx, rollCalendarEvent, arg.NextOccurs, arg.ID)
	return err
}

const staleRepeatingEvents = `-- name: StaleRepeatingEvents :many
SELECT id, user_id, event_date, kind, title, note, start_time, end_time, repeat_in, remind_days, next_occurs, reminded_at, created_at, updated_at FROM calendar_events
WHERE repeat_in <> 'none'
  AND (next_occurs IS NULL OR next_occurs < CURRENT_DATE)
LIMIT 500
`

// Repeating events whose next occurrence has already gone by, so the sweep can
// move them on.
func (q *Queries) StaleRepeatingEvents(ctx context.Context) ([]CalendarEvent, error) {
	rows, err := q.db.Query(ctx, staleRepeatingEvents)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CalendarEvent{}
	for rows.Next() {
		var i CalendarEvent
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.EventDate,
			&i.Kind,
			&i.Title,
			&i.Note,
			&i.StartTime,
			&i.EndTime,
			&i.RepeatIn,
			&i.RemindDays,
			&i.NextOccurs,
			&i.RemindedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCalendarEvent = `-- name: UpdateCalendarEvent :one
UPDATE calendar_events
SET event_date = $1,
    kind = $2,
    title = $3,
    note = $4,
    start_time = $5,
    end_time = $6,
    repeat_in = $7,
    remind_days = $8,
    next_occurs = $9,
    reminded_at = NULL,
    updated_at = now()
WHERE id = $10 AND user_id = $11
RETURNING id, user_id, event_date, kind, title, note, start_time, end_time, repeat_in, remind_days, next_occurs, reminded_at, created_at, updated_at
`

type UpdateCalendarEventParams struct {
	EventDate  pgtype.Date `json:"event_date"`
	Kind       string      `json:"kind"`
	Title      string      `json:"title"`
	Note       string      `json:"note"`
	StartTime  pgtype.Time `json:"start_time"`
	EndTime    pgtype.Time `json:"end_time"`
	RepeatIn   string      `json:"repeat_in"`
	RemindDays *int32      `json:"remind_days"`
	NextOccurs pgtype.Date `json:"next_occurs"`
	ID         int64       `json:"id"`
	UserID     int64       `json:"user_id"`
}

// Scoped by user_id as well as id, so a wrong id cannot edit someone else's
// birthday — the check is in the WHERE clause, not only in the handler.
func (q *Queries) UpdateCalendarEvent(ctx context.Context, arg UpdateCalendarEventParams) (CalendarEvent, error) {
	row := q.db.QueryRow(ctx, updateCalendarEvent,
		arg.EventDate,
		arg.Kind,
		arg.Title,
		arg.Note,
		arg.StartTime,
		arg.EndTime,
		arg.RepeatIn,
		arg.RemindDays,
		arg.NextOccurs,
		arg.ID,
		arg.UserID,
	)
	var i CalendarEvent
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.EventDate,
		&i.Kind,
		&i.Title,
		&i.Note,
		&i.StartTime,
		&i.EndTime,
		&i.RepeatIn,
		&i.RemindDays,
		&i.NextOccurs,
		&i.RemindedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
