// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: chat.sql

package db

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const addConversationMember = `-- name: AddConversationMember :exec
INSERT INTO conversation_members (conversation_id, user_id, role)
VALUES ($1, $2, $3)
ON CONFLICT (conversation_id, user_id) DO NOTHING
`

type AddConversationMemberParams struct {
	ConversationID int64  `json:"conversation_id"`
	UserID         int64  `json:"user_id"`
	Role           string `json:"role"`
}

func (q *Queries) AddConversationMember(ctx context.Context, arg AddConversationMemberParams) error {
	_, err := q.db.Exec(ctx, addConversationMember, arg.ConversationID, arg.UserID, arg.Role)
	return err
}

const addReaction = `-- name: AddReaction :exec
INSERT INTO message_reactions (message_id, user_id, emoji)
VALUES ($1, $2, $3)
ON CONFLICT DO NOTHING
`

type AddReactionParams struct {
	MessageID int64  `json:"message_id"`
	UserID    int64  `json:"user_id"`
	Emoji     string `json:"emoji"`
}

func (q *Queries) AddReaction(ctx context.Context, arg AddReactionParams) error {
	_, err := q.db.Exec(ctx, addReaction, arg.MessageID, arg.UserID, arg.Emoji)
	return err
}

const conversationMemberIDs = `-- name: ConversationMemberIDs :many
SELECT user_id FROM conversation_members
WHERE conversation_id = $1
`

func (q *Queries) ConversationMemberIDs(ctx context.Context, conversationID int64) ([]int64, error) {
	rows, err := q.db.Query(ctx, conversationMemberIDs, conversationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var user_id int64
		if err := rows.Scan(&user_id); err != nil {
			return nil, err
		}
		items = append(items, user_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countConversationAdmins = `-- name: CountConversationAdmins :one
SELECT COUNT(*) FROM conversation_members
WHERE conversation_id = $1 AND role = 'admin'
`

func (q *Queries) CountConversationAdmins(ctx context.Context, conversationID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countConversationAdmins, conversationID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createConversation = `-- name: CreateConversation :one
INSERT INTO conversations (type, name, created_by)
VALUES ($1, $2, $3)
RETURNING id, type, name, created_by, created_at, avatar, visibility
`

type CreateConversationParams struct {
	Type      string `json:"type"`
	Name      string `json:"name"`
	CreatedBy *int64 `json:"created_by"`
}

func (q *Queries) CreateConversation(ctx context.Context, arg CreateConversationParams) (Conversation, error) {
	row := q.db.QueryRow(ctx, createConversation, arg.Type, arg.Name, arg.CreatedBy)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Name,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.Avatar,
		&i.Visibility,
	)
	return i, err
}

const createMessage = `-- name: CreateMessage :one
INSERT INTO messages (
    conversation_id, sender_id, kind, body,
    attachment_name, attachment_stored, attachment_type, attachment_size,
    reply_to_id, forwarded)
VALUES (
    $1, $2, $3, $4,
    $5, $6,
    $7, $8,
    $9, $10)
RETURNING id, conversation_id, sender_id, kind, body, attachment_name, attachment_stored, attachment_type, attachment_size, created_at, edited, reply_to_id, pinned, forwarded
`

type CreateMessageParams struct {
	ConversationID   int64  `json:"conversation_id"`
	SenderID         *int64 `json:"sender_id"`
	Kind             string `json:"kind"`
	Body             string `json:"body"`
	AttachmentName   string `json:"attachment_name"`
	AttachmentStored string `json:"attachment_stored"`
	AttachmentType   string `json:"attachment_type"`
	AttachmentSize   int64  `json:"attachment_size"`
	ReplyToID        *int64 `json:"reply_to_id"`
	Forwarded        bool   `json:"forwarded"`
}

func (q *Queries) CreateMessage(ctx context.Context, arg CreateMessageParams) (Message, error) {
	row := q.db.QueryRow(ctx, createMessage,
		arg.ConversationID,
		arg.SenderID,
		arg.Kind,
		arg.Body,
		arg.AttachmentName,
		arg.AttachmentStored,
		arg.AttachmentType,
		arg.AttachmentSize,
		arg.ReplyToID,
		arg.Forwarded,
	)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.SenderID,
		&i.Kind,
		&i.Body,
		&i.AttachmentName,
		&i.AttachmentStored,
		&i.AttachmentType,
		&i.AttachmentSize,
		&i.CreatedAt,
		&i.Edited,
		&i.ReplyToID,
		&i.Pinned,
		&i.Forwarded,
	)
	return i, err
}

const deleteMessage = `-- name: DeleteMessage :exec
DELETE FROM messages WHERE id = $1
`

func (q *Queries) DeleteMessage(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteMessage, id)
	return err
}

const findDMConversation = `-- name: FindDMConversation :one
SELECT c.id
FROM conversations c
JOIN conversation_members a
    ON a.conversation_id = c.id AND a.user_id = $1
JOIN conversation_members b
    ON b.conversation_id = c.id AND b.user_id = $2
WHERE c.type = 'dm'
  AND (SELECT COUNT(*) FROM conversation_members m
       WHERE m.conversation_id = c.id) = 2
LIMIT 1
`

type FindDMConversationParams struct {
	UserA int64 `json:"user_a"`
	UserB int64 `json:"user_b"`
}

func (q *Queries) FindDMConversation(ctx context.Context, arg FindDMConversationParams) (int64, error) {
	row := q.db.QueryRow(ctx, findDMConversation, arg.UserA, arg.UserB)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const getConversationMemberRole = `-- name: GetConversationMemberRole :one
SELECT role FROM conversation_members
WHERE conversation_id = $1 AND user_id = $2
`

type GetConversationMemberRoleParams struct {
	ConversationID int64 `json:"conversation_id"`
	UserID         int64 `json:"user_id"`
}

func (q *Queries) GetConversationMemberRole(ctx context.Context, arg GetConversationMemberRoleParams) (string, error) {
	row := q.db.QueryRow(ctx, getConversationMemberRole, arg.ConversationID, arg.UserID)
	var role string
	err := row.Scan(&role)
	return role, err
}

const getConversationMeta = `-- name: GetConversationMeta :one
SELECT id, type, name, visibility FROM conversations WHERE id = $1
`

type GetConversationMetaRow struct {
	ID         int64  `json:"id"`
	Type       string `json:"type"`
	Name       string `json:"name"`
	Visibility string `json:"visibility"`
}

func (q *Queries) GetConversationMeta(ctx context.Context, id int64) (GetConversationMetaRow, error) {
	row := q.db.QueryRow(ctx, getConversationMeta, id)
	var i GetConversationMetaRow
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Name,
		&i.Visibility,
	)
	return i, err
}

const getMessageWithSender = `-- name: GetMessageWithSender :one
SELECT m.id, m.conversation_id, m.sender_id, m.kind, m.body, m.attachment_name, m.attachment_stored, m.attachment_type, m.attachment_size, m.created_at, m.edited, m.reply_to_id, m.pinned, m.forwarded, u.full_name AS sender_name, u.avatar AS sender_avatar,
       r.body AS reply_body, r.kind AS reply_kind,
       ru.full_name AS reply_sender_name,
       (SELECT COUNT(*) FROM messages c WHERE c.reply_to_id = m.id)::int AS reply_count
FROM messages m
LEFT JOIN users u ON u.id = m.sender_id
LEFT JOIN messages r ON r.id = m.reply_to_id
LEFT JOIN users ru ON ru.id = r.sender_id
WHERE m.id = $1
`

type GetMessageWithSenderRow struct {
	ID               int64     `json:"id"`
	ConversationID   int64     `json:"conversation_id"`
	SenderID         *int64    `json:"sender_id"`
	Kind             string    `json:"kind"`
	Body             string    `json:"body"`
	AttachmentName   string    `json:"attachment_name"`
	AttachmentStored string    `json:"attachment_stored"`
	AttachmentType   string    `json:"attachment_type"`
	AttachmentSize   int64     `json:"attachment_size"`
	CreatedAt        time.Time `json:"created_at"`
	Edited           bool      `json:"edited"`
	ReplyToID        *int64    `json:"reply_to_id"`
	Pinned           bool      `json:"pinned"`
	Forwarded        bool      `json:"forwarded"`
	SenderName       *string   `json:"sender_name"`
	SenderAvatar     *string   `json:"sender_avatar"`
	ReplyBody        *string   `json:"reply_body"`
	ReplyKind        *string   `json:"reply_kind"`
	ReplySenderName  *string   `json:"reply_sender_name"`
	ReplyCount       int32     `json:"reply_count"`
}

func (q *Queries) GetMessageWithSender(ctx context.Context, id int64) (GetMessageWithSenderRow, error) {
	row := q.db.QueryRow(ctx, getMessageWithSender, id)
	var i GetMessageWithSenderRow
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.SenderID,
		&i.Kind,
		&i.Body,
		&i.AttachmentName,
		&i.AttachmentStored,
		&i.AttachmentType,
		&i.AttachmentSize,
		&i.CreatedAt,
		&i.Edited,
		&i.ReplyToID,
		&i.Pinned,
		&i.Forwarded,
		&i.SenderName,
		&i.SenderAvatar,
		&i.ReplyBody,
		&i.ReplyKind,
		&i.ReplySenderName,
		&i.ReplyCount,
	)
	return i, err
}

const hasReaction = `-- name: HasReaction :one
SELECT EXISTS (
    SELECT 1 FROM message_reactions
    WHERE message_id = $1 AND user_id = $2 AND emoji = $3
)
`

type HasReactionParams struct {
	MessageID int64  `json:"message_id"`
	UserID    int64  `json:"user_id"`
	Emoji     string `json:"emoji"`
}

func (q *Queries) HasReaction(ctx context.Context, arg HasReactionParams) (bool, error) {
	row := q.db.QueryRow(ctx, hasReaction, arg.MessageID, arg.UserID, arg.Emoji)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listConversationMembers = `-- name: ListConversationMembers :many
SELECT cm.user_id, cm.role, cm.joined_at, cm.last_read_at,
       u.full_name, u.email, u.avatar
FROM conversation_members cm
JOIN users u ON u.id = cm.user_id
WHERE cm.conversation_id = $1
ORDER BY u.full_name
`

type ListConversationMembersRow struct {
	UserID     int64              `json:"user_id"`
	Role       string             `json:"role"`
	JoinedAt   time.Time          `json:"joined_at"`
	LastReadAt pgtype.Timestamptz `json:"last_read_at"`
	FullName   string             `json:"full_name"`
	Email      string             `json:"email"`
	Avatar     string             `json:"avatar"`
}

func (q *Queries) ListConversationMembers(ctx context.Context, conversationID int64) ([]ListConversationMembersRow, error) {
	rows, err := q.db.Query(ctx, listConversationMembers, conversationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListConversationMembersRow{}
	for rows.Next() {
		var i ListConversationMembersRow
		if err := rows.Scan(
			&i.UserID,
			&i.Role,
			&i.JoinedAt,
			&i.LastReadAt,
			&i.FullName,
			&i.Email,
			&i.Avatar,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listConversationsForUser = `-- name: ListConversationsForUser :many
SELECT
    c.id,
    c.type,
    c.name,
    c.avatar,
    c.created_at,
    cm.last_read_at,
    COALESCE((SELECT m.body FROM messages m WHERE m.conversation_id = c.id
        ORDER BY m.created_at DESC LIMIT 1), '')::text AS last_body,
    COALESCE((SELECT m.kind FROM messages m WHERE m.conversation_id = c.id
        ORDER BY m.created_at DESC LIMIT 1), '')::text AS last_kind,
    COALESCE((SELECT m.created_at FROM messages m WHERE m.conversation_id = c.id
        ORDER BY m.created_at DESC LIMIT 1), c.created_at) AS last_at,
    (SELECT m.sender_id FROM messages m WHERE m.conversation_id = c.id
        ORDER BY m.created_at DESC LIMIT 1) AS last_sender_id,
    COALESCE((
        SELECT COUNT(*) FROM messages m2
        WHERE m2.conversation_id = c.id
          AND (cm.last_read_at IS NULL OR m2.created_at > cm.last_read_at)
          AND m2.sender_id IS DISTINCT FROM $1
    ), 0)::int AS unread_count,
    COALESCE((SELECT cm2.user_id FROM conversation_members cm2
        WHERE cm2.conversation_id = c.id
          AND cm2.user_id <> $1
          AND c.type = 'dm'
        LIMIT 1), 0)::bigint AS other_user_id,
    COALESCE((SELECT u.full_name FROM conversation_members cm2
        JOIN users u ON u.id = cm2.user_id
        WHERE cm2.conversation_id = c.id
          AND cm2.user_id <> $1
          AND c.type = 'dm'
        LIMIT 1), '')::text AS other_user_name,
    COALESCE((SELECT u.avatar FROM conversation_members cm2
        JOIN users u ON u.id = cm2.user_id
        WHERE cm2.conversation_id = c.id
          AND cm2.user_id <> $1
          AND c.type = 'dm'
        LIMIT 1), '')::text AS other_user_avatar,
    (SELECT COUNT(*) FROM conversation_members cmx
        WHERE cmx.conversation_id = c.id)::int AS member_count
FROM conversation_members cm
JOIN conversations c ON c.id = cm.conversation_id
WHERE cm.user_id = $1
ORDER BY last_at DESC, c.created_at DESC
`

type ListConversationsForUserRow struct {
	ID              int64              `json:"id"`
	Type            string             `json:"type"`
	Name            string             `json:"name"`
	Avatar          string             `json:"avatar"`
	CreatedAt       time.Time          `json:"created_at"`
	LastReadAt      pgtype.Timestamptz `json:"last_read_at"`
	LastBody        string             `json:"last_body"`
	LastKind        string             `json:"last_kind"`
	LastAt          time.Time          `json:"last_at"`
	LastSenderID    *int64             `json:"last_sender_id"`
	UnreadCount     int32              `json:"unread_count"`
	OtherUserID     int64              `json:"other_user_id"`
	OtherUserName   string             `json:"other_user_name"`
	OtherUserAvatar string             `json:"other_user_avatar"`
	MemberCount     int32              `json:"member_count"`
}

func (q *Queries) ListConversationsForUser(ctx context.Context, userID *int64) ([]ListConversationsForUserRow, error) {
	rows, err := q.db.Query(ctx, listConversationsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListConversationsForUserRow{}
	for rows.Next() {
		var i ListConversationsForUserRow
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.Name,
			&i.Avatar,
			&i.CreatedAt,
			&i.LastReadAt,
			&i.LastBody,
			&i.LastKind,
			&i.LastAt,
			&i.LastSenderID,
			&i.UnreadCount,
			&i.OtherUserID,
			&i.OtherUserName,
			&i.OtherUserAvatar,
			&i.MemberCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMessages = `-- name: ListMessages :many
SELECT m.id, m.conversation_id, m.sender_id, m.kind, m.body, m.attachment_name, m.attachment_stored, m.attachment_type, m.attachment_size, m.created_at, m.edited, m.reply_to_id, m.pinned, m.forwarded, u.full_name AS sender_name, u.avatar AS sender_avatar,
       r.body AS reply_body, r.kind AS reply_kind,
       ru.full_name AS reply_sender_name,
       (SELECT COUNT(*) FROM messages c WHERE c.reply_to_id = m.id)::int AS reply_count
FROM messages m
LEFT JOIN users u ON u.id = m.sender_id
LEFT JOIN messages r ON r.id = m.reply_to_id
LEFT JOIN users ru ON ru.id = r.sender_id
WHERE m.conversation_id = $1
ORDER BY m.created_at DESC
LIMIT $3 OFFSET $2
`

type ListMessagesParams struct {
	ConversationID int64 `json:"conversation_id"`
	Off            int32 `json:"off"`
	Lim            int32 `json:"lim"`
}

type ListMessagesRow struct {
	ID               int64     `json:"id"`
	ConversationID   int64     `json:"conversation_id"`
	SenderID         *int64    `json:"sender_id"`
	Kind             string    `json:"kind"`
	Body             string    `json:"body"`
	AttachmentName   string    `json:"attachment_name"`
	AttachmentStored string    `json:"attachment_stored"`
	AttachmentType   string    `json:"attachment_type"`
	AttachmentSize   int64     `json:"attachment_size"`
	CreatedAt        time.Time `json:"created_at"`
	Edited           bool      `json:"edited"`
	ReplyToID        *int64    `json:"reply_to_id"`
	Pinned           bool      `json:"pinned"`
	Forwarded        bool      `json:"forwarded"`
	SenderName       *string   `json:"sender_name"`
	SenderAvatar     *string   `json:"sender_avatar"`
	ReplyBody        *string   `json:"reply_body"`
	ReplyKind        *string   `json:"reply_kind"`
	ReplySenderName  *string   `json:"reply_sender_name"`
	ReplyCount       int32     `json:"reply_count"`
}

func (q *Queries) ListMessages(ctx context.Context, arg ListMessagesParams) ([]ListMessagesRow, error) {
	rows, err := q.db.Query(ctx, listMessages, arg.ConversationID, arg.Off, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMessagesRow{}
	for rows.Next() {
		var i ListMessagesRow
		if err := rows.Scan(
			&i.ID,
			&i.ConversationID,
			&i.SenderID,
			&i.Kind,
			&i.Body,
			&i.AttachmentName,
			&i.AttachmentStored,
			&i.AttachmentType,
			&i.AttachmentSize,
			&i.CreatedAt,
			&i.Edited,
			&i.ReplyToID,
			&i.Pinned,
			&i.Forwarded,
			&i.SenderName,
			&i.SenderAvatar,
			&i.ReplyBody,
			&i.ReplyKind,
			&i.ReplySenderName,
			&i.ReplyCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPinnedMessages = `-- name: ListPinnedMessages :many
SELECT m.id, m.conversation_id, m.sender_id, m.kind, m.body, m.attachment_name, m.attachment_stored, m.attachment_type, m.attachment_size, m.created_at, m.edited, m.reply_to_id, m.pinned, m.forwarded, u.full_name AS sender_name, u.avatar AS sender_avatar,
       r.body AS reply_body, r.kind AS reply_kind,
       ru.full_name AS reply_sender_name
FROM messages m
LEFT JOIN users u ON u.id = m.sender_id
LEFT JOIN messages r ON r.id = m.reply_to_id
LEFT JOIN users ru ON ru.id = r.sender_id
WHERE m.conversation_id = $1 AND m.pinned
ORDER BY m.created_at DESC
`

type ListPinnedMessagesRow struct {
	ID               int64     `json:"id"`
	ConversationID   int64     `json:"conversation_id"`
	SenderID         *int64    `json:"sender_id"`
	Kind             string    `json:"kind"`
	Body             string    `json:"body"`
	AttachmentName   string    `json:"attachment_name"`
	AttachmentStored string    `json:"attachment_stored"`
	AttachmentType   string    `json:"attachment_type"`
	AttachmentSize   int64     `json:"attachment_size"`
	CreatedAt        time.Time `json:"created_at"`
	Edited           bool      `json:"edited"`
	ReplyToID        *int64    `json:"reply_to_id"`
	Pinned           bool      `json:"pinned"`
	Forwarded        bool      `json:"forwarded"`
	SenderName       *string   `json:"sender_name"`
	SenderAvatar     *string   `json:"sender_avatar"`
	ReplyBody        *string   `json:"reply_body"`
	ReplyKind        *string   `json:"reply_kind"`
	ReplySenderName  *string   `json:"reply_sender_name"`
}

func (q *Queries) ListPinnedMessages(ctx context.Context, conversationID int64) ([]ListPinnedMessagesRow, error) {
	rows, err := q.db.Query(ctx, listPinnedMessages, conversationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPinnedMessagesRow{}
	for rows.Next() {
		var i ListPinnedMessagesRow
		if err := rows.Scan(
			&i.ID,
			&i.ConversationID,
			&i.SenderID,
			&i.Kind,
			&i.Body,
			&i.AttachmentName,
			&i.AttachmentStored,
			&i.AttachmentType,
			&i.AttachmentSize,
			&i.CreatedAt,
			&i.Edited,
			&i.ReplyToID,
			&i.Pinned,
			&i.Forwarded,
			&i.SenderName,
			&i.SenderAvatar,
			&i.ReplyBody,
			&i.ReplyKind,
			&i.ReplySenderName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublicChannels = `-- name: ListPublicChannels :many
SELECT c.id, c.name, c.avatar, c.created_at,
       (SELECT COUNT(*) FROM conversation_members cm2
        WHERE cm2.conversation_id = c.id)::int AS member_count
FROM conversations c
WHERE c.type = 'group' AND c.visibility = 'public'
  AND NOT EXISTS (
    SELECT 1 FROM conversation_members cm
    WHERE cm.conversation_id = c.id AND cm.user_id = $1
  )
ORDER BY c.created_at DESC
`

type ListPublicChannelsRow struct {
	ID          int64     `json:"id"`
	Name        string    `json:"name"`
	Avatar      string    `json:"avatar"`
	CreatedAt   time.Time `json:"created_at"`
	MemberCount int32     `json:"member_count"`
}

func (q *Queries) ListPublicChannels(ctx context.Context, userID int64) ([]ListPublicChannelsRow, error) {
	rows, err := q.db.Query(ctx, listPublicChannels, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPublicChannelsRow{}
	for rows.Next() {
		var i ListPublicChannelsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Avatar,
			&i.CreatedAt,
			&i.MemberCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReactionsForConversation = `-- name: ListReactionsForConversation :many
SELECT r.message_id, r.emoji, r.user_id
FROM message_reactions r
JOIN messages m ON m.id = r.message_id
WHERE m.conversation_id = $1
ORDER BY r.created_at
`

type ListReactionsForConversationRow struct {
	MessageID int64  `json:"message_id"`
	Emoji     string `json:"emoji"`
	UserID    int64  `json:"user_id"`
}

func (q *Queries) ListReactionsForConversation(ctx context.Context, conversationID int64) ([]ListReactionsForConversationRow, error) {
	rows, err := q.db.Query(ctx, listReactionsForConversation, conversationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListReactionsForConversationRow{}
	for rows.Next() {
		var i ListReactionsForConversationRow
		if err := rows.Scan(&i.MessageID, &i.Emoji, &i.UserID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listThreadReplies = `-- name: ListThreadReplies :many
SELECT m.id, m.conversation_id, m.sender_id, m.kind, m.body, m.attachment_name, m.attachment_stored, m.attachment_type, m.attachment_size, m.created_at, m.edited, m.reply_to_id, m.pinned, m.forwarded, u.full_name AS sender_name, u.avatar AS sender_avatar,
       r.body AS reply_body, r.kind AS reply_kind,
       ru.full_name AS reply_sender_name
FROM messages m
LEFT JOIN users u ON u.id = m.sender_id
LEFT JOIN messages r ON r.id = m.reply_to_id
LEFT JOIN users ru ON ru.id = r.sender_id
WHERE m.reply_to_id = $1
ORDER BY m.created_at ASC
`

type ListThreadRepliesRow struct {
	ID               int64     `json:"id"`
	ConversationID   int64     `json:"conversation_id"`
	SenderID         *int64    `json:"sender_id"`
	Kind             string    `json:"kind"`
	Body             string    `json:"body"`
	AttachmentName   string    `json:"attachment_name"`
	AttachmentStored string    `json:"attachment_stored"`
	AttachmentType   string    `json:"attachment_type"`
	AttachmentSize   int64     `json:"attachment_size"`
	CreatedAt        time.Time `json:"created_at"`
	Edited           bool      `json:"edited"`
	ReplyToID        *int64    `json:"reply_to_id"`
	Pinned           bool      `json:"pinned"`
	Forwarded        bool      `json:"forwarded"`
	SenderName       *string   `json:"sender_name"`
	SenderAvatar     *string   `json:"sender_avatar"`
	ReplyBody        *string   `json:"reply_body"`
	ReplyKind        *string   `json:"reply_kind"`
	ReplySenderName  *string   `json:"reply_sender_name"`
}

func (q *Queries) ListThreadReplies(ctx context.Context, replyToID *int64) ([]ListThreadRepliesRow, error) {
	rows, err := q.db.Query(ctx, listThreadReplies, replyToID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListThreadRepliesRow{}
	for rows.Next() {
		var i ListThreadRepliesRow
		if err := rows.Scan(
			&i.ID,
			&i.ConversationID,
			&i.SenderID,
			&i.Kind,
			&i.Body,
			&i.AttachmentName,
			&i.AttachmentStored,
			&i.AttachmentType,
			&i.AttachmentSize,
			&i.CreatedAt,
			&i.Edited,
			&i.ReplyToID,
			&i.Pinned,
			&i.Forwarded,
			&i.SenderName,
			&i.SenderAvatar,
			&i.ReplyBody,
			&i.ReplyKind,
			&i.ReplySenderName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markConversationRead = `-- name: MarkConversationRead :exec
UPDATE conversation_members SET last_read_at = now()
WHERE conversation_id = $1
  AND user_id = $2
`

type MarkConversationReadParams struct {
	ConversationID int64 `json:"conversation_id"`
	UserID         int64 `json:"user_id"`
}

func (q *Queries) MarkConversationRead(ctx context.Context, arg MarkConversationReadParams) error {
	_, err := q.db.Exec(ctx, markConversationRead, arg.ConversationID, arg.UserID)
	return err
}

const removeConversationMember = `-- name: RemoveConversationMember :exec
DELETE FROM conversation_members
WHERE conversation_id = $1
  AND user_id = $2
`

type RemoveConversationMemberParams struct {
	ConversationID int64 `json:"conversation_id"`
	UserID         int64 `json:"user_id"`
}

func (q *Queries) RemoveConversationMember(ctx context.Context, arg RemoveConversationMemberParams) error {
	_, err := q.db.Exec(ctx, removeConversationMember, arg.ConversationID, arg.UserID)
	return err
}

const removeReaction = `-- name: RemoveReaction :exec
DELETE FROM message_reactions
WHERE message_id = $1 AND user_id = $2 AND emoji = $3
`

type RemoveReactionParams struct {
	MessageID int64  `json:"message_id"`
	UserID    int64  `json:"user_id"`
	Emoji     string `json:"emoji"`
}

func (q *Queries) RemoveReaction(ctx context.Context, arg RemoveReactionParams) error {
	_, err := q.db.Exec(ctx, removeReaction, arg.MessageID, arg.UserID, arg.Emoji)
	return err
}

const renameConversation = `-- name: RenameConversation :exec
UPDATE conversations SET name = $1
WHERE id = $2
`

type RenameConversationParams struct {
	Name string `json:"name"`
	ID   int64  `json:"id"`
}

func (q *Queries) RenameConversation(ctx context.Context, arg RenameConversationParams) error {
	_, err := q.db.Exec(ctx, renameConversation, arg.Name, arg.ID)
	return err
}

const setConversationAvatar = `-- name: SetConversationAvatar :exec
UPDATE conversations SET avatar = $1
WHERE id = $2
`

type SetConversationAvatarParams struct {
	Avatar string `json:"avatar"`
	ID     int64  `json:"id"`
}

func (q *Queries) SetConversationAvatar(ctx context.Context, arg SetConversationAvatarParams) error {
	_, err := q.db.Exec(ctx, setConversationAvatar, arg.Avatar, arg.ID)
	return err
}

const setConversationMemberRole = `-- name: SetConversationMemberRole :exec
UPDATE conversation_members SET role = $1
WHERE conversation_id = $2
  AND user_id = $3
`

type SetConversationMemberRoleParams struct {
	Role           string `json:"role"`
	ConversationID int64  `json:"conversation_id"`
	UserID         int64  `json:"user_id"`
}

func (q *Queries) SetConversationMemberRole(ctx context.Context, arg SetConversationMemberRoleParams) error {
	_, err := q.db.Exec(ctx, setConversationMemberRole, arg.Role, arg.ConversationID, arg.UserID)
	return err
}

const setConversationVisibility = `-- name: SetConversationVisibility :exec
UPDATE conversations SET visibility = $1
WHERE id = $2
`

type SetConversationVisibilityParams struct {
	Visibility string `json:"visibility"`
	ID         int64  `json:"id"`
}

func (q *Queries) SetConversationVisibility(ctx context.Context, arg SetConversationVisibilityParams) error {
	_, err := q.db.Exec(ctx, setConversationVisibility, arg.Visibility, arg.ID)
	return err
}

const setMessagePinned = `-- name: SetMessagePinned :exec
UPDATE messages SET pinned = $2 WHERE id = $1
`

type SetMessagePinnedParams struct {
	ID     int64 `json:"id"`
	Pinned bool  `json:"pinned"`
}

func (q *Queries) SetMessagePinned(ctx context.Context, arg SetMessagePinnedParams) error {
	_, err := q.db.Exec(ctx, setMessagePinned, arg.ID, arg.Pinned)
	return err
}

const updateMessageBody = `-- name: UpdateMessageBody :exec
UPDATE messages SET body = $2, edited = TRUE WHERE id = $1
`

type UpdateMessageBodyParams struct {
	ID   int64  `json:"id"`
	Body string `json:"body"`
}

func (q *Queries) UpdateMessageBody(ctx context.Context, arg UpdateMessageBodyParams) error {
	_, err := q.db.Exec(ctx, updateMessageBody, arg.ID, arg.Body)
	return err
}
