// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: checklist_templates.sql

package db

import (
	"context"
)

const createChecklistTemplate = `-- name: CreateChecklistTemplate :one
INSERT INTO checklist_templates (name, category, items, created_by)
VALUES ($1, $2, $3,
        $4)
RETURNING id, name, category, items, created_by, created_at
`

type CreateChecklistTemplateParams struct {
	Name      string `json:"name"`
	Category  string `json:"category"`
	Items     string `json:"items"`
	CreatedBy *int64 `json:"created_by"`
}

func (q *Queries) CreateChecklistTemplate(ctx context.Context, arg CreateChecklistTemplateParams) (ChecklistTemplate, error) {
	row := q.db.QueryRow(ctx, createChecklistTemplate,
		arg.Name,
		arg.Category,
		arg.Items,
		arg.CreatedBy,
	)
	var i ChecklistTemplate
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Category,
		&i.Items,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const deleteChecklistTemplate = `-- name: DeleteChecklistTemplate :exec
DELETE FROM checklist_templates WHERE id = $1
`

func (q *Queries) DeleteChecklistTemplate(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteChecklistTemplate, id)
	return err
}

const getChecklistTemplate = `-- name: GetChecklistTemplate :one
SELECT id, name, category, items, created_by, created_at FROM checklist_templates WHERE id = $1
`

func (q *Queries) GetChecklistTemplate(ctx context.Context, id int64) (ChecklistTemplate, error) {
	row := q.db.QueryRow(ctx, getChecklistTemplate, id)
	var i ChecklistTemplate
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Category,
		&i.Items,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const listChecklistTemplates = `-- name: ListChecklistTemplates :many
SELECT id, name, category, items, created_by, created_at FROM checklist_templates
ORDER BY category, name, id
`

func (q *Queries) ListChecklistTemplates(ctx context.Context) ([]ChecklistTemplate, error) {
	rows, err := q.db.Query(ctx, listChecklistTemplates)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ChecklistTemplate{}
	for rows.Next() {
		var i ChecklistTemplate
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Category,
			&i.Items,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateChecklistTemplate = `-- name: UpdateChecklistTemplate :one
UPDATE checklist_templates
SET name = $1,
    category = $2,
    items = $3
WHERE id = $4
RETURNING id, name, category, items, created_by, created_at
`

type UpdateChecklistTemplateParams struct {
	Name     string `json:"name"`
	Category string `json:"category"`
	Items    string `json:"items"`
	ID       int64  `json:"id"`
}

func (q *Queries) UpdateChecklistTemplate(ctx context.Context, arg UpdateChecklistTemplateParams) (ChecklistTemplate, error) {
	row := q.db.QueryRow(ctx, updateChecklistTemplate,
		arg.Name,
		arg.Category,
		arg.Items,
		arg.ID,
	)
	var i ChecklistTemplate
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Category,
		&i.Items,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}
