// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: checklist.sql

package db

import (
	"context"
)

const createChecklistItem = `-- name: CreateChecklistItem :one
INSERT INTO checklist_items (task_id, content, position)
VALUES ($1, $2, $3)
RETURNING id, task_id, content, done, position, created_at
`

type CreateChecklistItemParams struct {
	TaskID   int64  `json:"task_id"`
	Content  string `json:"content"`
	Position int32  `json:"position"`
}

func (q *Queries) CreateChecklistItem(ctx context.Context, arg CreateChecklistItemParams) (ChecklistItem, error) {
	row := q.db.QueryRow(ctx, createChecklistItem, arg.TaskID, arg.Content, arg.Position)
	var i ChecklistItem
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.Content,
		&i.Done,
		&i.Position,
		&i.CreatedAt,
	)
	return i, err
}

const deleteChecklistItem = `-- name: DeleteChecklistItem :exec
DELETE FROM checklist_items
WHERE id = $1
`

func (q *Queries) DeleteChecklistItem(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteChecklistItem, id)
	return err
}

const listChecklist = `-- name: ListChecklist :many
SELECT id, task_id, content, done, position, created_at FROM checklist_items
WHERE task_id = $1
ORDER BY position ASC, id ASC
`

func (q *Queries) ListChecklist(ctx context.Context, taskID int64) ([]ChecklistItem, error) {
	rows, err := q.db.Query(ctx, listChecklist, taskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ChecklistItem{}
	for rows.Next() {
		var i ChecklistItem
		if err := rows.Scan(
			&i.ID,
			&i.TaskID,
			&i.Content,
			&i.Done,
			&i.Position,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const maxChecklistPosition = `-- name: MaxChecklistPosition :one
SELECT COALESCE(MAX(position), 0)::int FROM checklist_items
WHERE task_id = $1
`

func (q *Queries) MaxChecklistPosition(ctx context.Context, taskID int64) (int32, error) {
	row := q.db.QueryRow(ctx, maxChecklistPosition, taskID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const setChecklistItemDone = `-- name: SetChecklistItemDone :one
UPDATE checklist_items
SET done = $2
WHERE id = $1
RETURNING id, task_id, content, done, position, created_at
`

type SetChecklistItemDoneParams struct {
	ID   int64 `json:"id"`
	Done bool  `json:"done"`
}

func (q *Queries) SetChecklistItemDone(ctx context.Context, arg SetChecklistItemDoneParams) (ChecklistItem, error) {
	row := q.db.QueryRow(ctx, setChecklistItemDone, arg.ID, arg.Done)
	var i ChecklistItem
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.Content,
		&i.Done,
		&i.Position,
		&i.CreatedAt,
	)
	return i, err
}
