// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: clients.sql

package db

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const clearClientProjects = `-- name: ClearClientProjects :exec
UPDATE projects SET client_id = NULL WHERE client_id = $1
`

func (q *Queries) ClearClientProjects(ctx context.Context, clientID *int64) error {
	_, err := q.db.Exec(ctx, clearClientProjects, clientID)
	return err
}

const createClient = `-- name: CreateClient :one
INSERT INTO clients (name, company, email, portal_token)
VALUES ($1, $2, $3,
        $4)
RETURNING id, name, company, email, portal_token, created_at
`

type CreateClientParams struct {
	Name        string `json:"name"`
	Company     string `json:"company"`
	Email       string `json:"email"`
	PortalToken string `json:"portal_token"`
}

func (q *Queries) CreateClient(ctx context.Context, arg CreateClientParams) (Client, error) {
	row := q.db.QueryRow(ctx, createClient,
		arg.Name,
		arg.Company,
		arg.Email,
		arg.PortalToken,
	)
	var i Client
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Company,
		&i.Email,
		&i.PortalToken,
		&i.CreatedAt,
	)
	return i, err
}

const deleteClient = `-- name: DeleteClient :exec
DELETE FROM clients WHERE id = $1
`

func (q *Queries) DeleteClient(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteClient, id)
	return err
}

const getClientByToken = `-- name: GetClientByToken :one
SELECT id, name, company, email, portal_token, created_at FROM clients WHERE portal_token = $1
`

func (q *Queries) GetClientByToken(ctx context.Context, portalToken string) (Client, error) {
	row := q.db.QueryRow(ctx, getClientByToken, portalToken)
	var i Client
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Company,
		&i.Email,
		&i.PortalToken,
		&i.CreatedAt,
	)
	return i, err
}

const listClientInvoices = `-- name: ListClientInvoices :many
SELECT i.id, i.number, i.status, i.issue_date, i.due_date, i.created_at,
       COALESCE((
           SELECT SUM(l.amount_cents) FROM invoice_lines l
           WHERE l.invoice_id = i.id
       ), 0)::bigint AS total_cents
FROM invoices i
JOIN projects p ON p.id = i.project_id
WHERE p.client_id = $1 AND i.status <> 'void'
ORDER BY i.id DESC
`

type ListClientInvoicesRow struct {
	ID         int64       `json:"id"`
	Number     string      `json:"number"`
	Status     string      `json:"status"`
	IssueDate  pgtype.Date `json:"issue_date"`
	DueDate    pgtype.Date `json:"due_date"`
	CreatedAt  time.Time   `json:"created_at"`
	TotalCents int64       `json:"total_cents"`
}

func (q *Queries) ListClientInvoices(ctx context.Context, clientID *int64) ([]ListClientInvoicesRow, error) {
	rows, err := q.db.Query(ctx, listClientInvoices, clientID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListClientInvoicesRow{}
	for rows.Next() {
		var i ListClientInvoicesRow
		if err := rows.Scan(
			&i.ID,
			&i.Number,
			&i.Status,
			&i.IssueDate,
			&i.DueDate,
			&i.CreatedAt,
			&i.TotalCents,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listClientProjects = `-- name: ListClientProjects :many
SELECT p.id, p.name, p.description, p.status, p.due_date,
       COALESCE((
           SELECT COUNT(*) FROM tasks t WHERE t.project_id = p.id
       ), 0)::int AS total_tasks,
       COALESCE((
           SELECT COUNT(*) FROM tasks t WHERE t.project_id = p.id AND t.done
       ), 0)::int AS done_tasks
FROM projects p
WHERE p.client_id = $1
ORDER BY p.name, p.id
`

type ListClientProjectsRow struct {
	ID          int64              `json:"id"`
	Name        string             `json:"name"`
	Description string             `json:"description"`
	Status      string             `json:"status"`
	DueDate     pgtype.Timestamptz `json:"due_date"`
	TotalTasks  int32              `json:"total_tasks"`
	DoneTasks   int32              `json:"done_tasks"`
}

func (q *Queries) ListClientProjects(ctx context.Context, clientID *int64) ([]ListClientProjectsRow, error) {
	rows, err := q.db.Query(ctx, listClientProjects, clientID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListClientProjectsRow{}
	for rows.Next() {
		var i ListClientProjectsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Status,
			&i.DueDate,
			&i.TotalTasks,
			&i.DoneTasks,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listClients = `-- name: ListClients :many
SELECT c.id, c.name, c.company, c.email, c.portal_token, c.created_at,
       COALESCE((
           SELECT COUNT(*) FROM projects p WHERE p.client_id = c.id
       ), 0)::bigint AS project_count
FROM clients c
ORDER BY c.name, c.id
`

type ListClientsRow struct {
	ID           int64     `json:"id"`
	Name         string    `json:"name"`
	Company      string    `json:"company"`
	Email        string    `json:"email"`
	PortalToken  string    `json:"portal_token"`
	CreatedAt    time.Time `json:"created_at"`
	ProjectCount int64     `json:"project_count"`
}

func (q *Queries) ListClients(ctx context.Context) ([]ListClientsRow, error) {
	rows, err := q.db.Query(ctx, listClients)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListClientsRow{}
	for rows.Next() {
		var i ListClientsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Company,
			&i.Email,
			&i.PortalToken,
			&i.CreatedAt,
			&i.ProjectCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectsWithClientFlag = `-- name: ListProjectsWithClientFlag :many
SELECT p.id, p.name, COALESCE(p.client_id = $1, false)::bool AS assigned
FROM projects p
ORDER BY p.name, p.id
`

type ListProjectsWithClientFlagRow struct {
	ID       int64  `json:"id"`
	Name     string `json:"name"`
	Assigned bool   `json:"assigned"`
}

func (q *Queries) ListProjectsWithClientFlag(ctx context.Context, clientID *int64) ([]ListProjectsWithClientFlagRow, error) {
	rows, err := q.db.Query(ctx, listProjectsWithClientFlag, clientID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProjectsWithClientFlagRow{}
	for rows.Next() {
		var i ListProjectsWithClientFlagRow
		if err := rows.Scan(&i.ID, &i.Name, &i.Assigned); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setProjectClient = `-- name: SetProjectClient :exec
UPDATE projects SET client_id = $1 WHERE id = $2
`

type SetProjectClientParams struct {
	ClientID *int64 `json:"client_id"`
	ID       int64  `json:"id"`
}

func (q *Queries) SetProjectClient(ctx context.Context, arg SetProjectClientParams) error {
	_, err := q.db.Exec(ctx, setProjectClient, arg.ClientID, arg.ID)
	return err
}

const updateClient = `-- name: UpdateClient :one
UPDATE clients
SET name = $1,
    company = $2,
    email = $3
WHERE id = $4
RETURNING id, name, company, email, portal_token, created_at
`

type UpdateClientParams struct {
	Name    string `json:"name"`
	Company string `json:"company"`
	Email   string `json:"email"`
	ID      int64  `json:"id"`
}

func (q *Queries) UpdateClient(ctx context.Context, arg UpdateClientParams) (Client, error) {
	row := q.db.QueryRow(ctx, updateClient,
		arg.Name,
		arg.Company,
		arg.Email,
		arg.ID,
	)
	var i Client
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Company,
		&i.Email,
		&i.PortalToken,
		&i.CreatedAt,
	)
	return i, err
}
