// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: comments.sql

package db

import (
	"context"
	"time"
)

const createActivity = `-- name: CreateActivity :exec
INSERT INTO activity (task_id, actor_id, action, detail)
VALUES ($1, $2, $3, $4)
`

type CreateActivityParams struct {
	TaskID  int64  `json:"task_id"`
	ActorID *int64 `json:"actor_id"`
	Action  string `json:"action"`
	Detail  string `json:"detail"`
}

func (q *Queries) CreateActivity(ctx context.Context, arg CreateActivityParams) error {
	_, err := q.db.Exec(ctx, createActivity,
		arg.TaskID,
		arg.ActorID,
		arg.Action,
		arg.Detail,
	)
	return err
}

const createComment = `-- name: CreateComment :one
INSERT INTO comments (task_id, author_id, parent_id, body)
VALUES ($1, $2, $3,
        $4)
RETURNING id, task_id, author_id, body, created_at, parent_id
`

type CreateCommentParams struct {
	TaskID   int64  `json:"task_id"`
	AuthorID *int64 `json:"author_id"`
	ParentID *int64 `json:"parent_id"`
	Body     string `json:"body"`
}

func (q *Queries) CreateComment(ctx context.Context, arg CreateCommentParams) (Comment, error) {
	row := q.db.QueryRow(ctx, createComment,
		arg.TaskID,
		arg.AuthorID,
		arg.ParentID,
		arg.Body,
	)
	var i Comment
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.AuthorID,
		&i.Body,
		&i.CreatedAt,
		&i.ParentID,
	)
	return i, err
}

const deleteComment = `-- name: DeleteComment :exec
DELETE FROM comments
WHERE id = $1
`

func (q *Queries) DeleteComment(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteComment, id)
	return err
}

const getComment = `-- name: GetComment :one
SELECT id, task_id, author_id, body, created_at, parent_id FROM comments
WHERE id = $1
`

func (q *Queries) GetComment(ctx context.Context, id int64) (Comment, error) {
	row := q.db.QueryRow(ctx, getComment, id)
	var i Comment
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.AuthorID,
		&i.Body,
		&i.CreatedAt,
		&i.ParentID,
	)
	return i, err
}

const listActivity = `-- name: ListActivity :many
SELECT a.id, a.task_id, a.actor_id, a.action, a.detail, a.created_at,
       u.full_name AS actor_name
FROM activity a
LEFT JOIN users u ON u.id = a.actor_id
WHERE a.task_id = $1
ORDER BY a.created_at DESC
LIMIT 50
`

type ListActivityRow struct {
	ID        int64     `json:"id"`
	TaskID    int64     `json:"task_id"`
	ActorID   *int64    `json:"actor_id"`
	Action    string    `json:"action"`
	Detail    string    `json:"detail"`
	CreatedAt time.Time `json:"created_at"`
	ActorName *string   `json:"actor_name"`
}

func (q *Queries) ListActivity(ctx context.Context, taskID int64) ([]ListActivityRow, error) {
	rows, err := q.db.Query(ctx, listActivity, taskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActivityRow{}
	for rows.Next() {
		var i ListActivityRow
		if err := rows.Scan(
			&i.ID,
			&i.TaskID,
			&i.ActorID,
			&i.Action,
			&i.Detail,
			&i.CreatedAt,
			&i.ActorName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listComments = `-- name: ListComments :many
SELECT c.id, c.task_id, c.author_id, c.parent_id, c.body, c.created_at,
       u.full_name AS author_name
FROM comments c
LEFT JOIN users u ON u.id = c.author_id
WHERE c.task_id = $1
ORDER BY c.created_at ASC
`

type ListCommentsRow struct {
	ID         int64     `json:"id"`
	TaskID     int64     `json:"task_id"`
	AuthorID   *int64    `json:"author_id"`
	ParentID   *int64    `json:"parent_id"`
	Body       string    `json:"body"`
	CreatedAt  time.Time `json:"created_at"`
	AuthorName *string   `json:"author_name"`
}

func (q *Queries) ListComments(ctx context.Context, taskID int64) ([]ListCommentsRow, error) {
	rows, err := q.db.Query(ctx, listComments, taskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCommentsRow{}
	for rows.Next() {
		var i ListCommentsRow
		if err := rows.Scan(
			&i.ID,
			&i.TaskID,
			&i.AuthorID,
			&i.ParentID,
			&i.Body,
			&i.CreatedAt,
			&i.AuthorName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentActivity = `-- name: ListRecentActivity :many
SELECT a.id, a.task_id, a.actor_id, a.action, a.detail, a.created_at,
       COALESCE(u.full_name, '')::text AS actor_name,
       COALESCE(t.title, '')::text     AS task_title
FROM activity a
LEFT JOIN users u ON u.id = a.actor_id
LEFT JOIN tasks t ON t.id = a.task_id
ORDER BY a.created_at DESC
LIMIT 200
`

type ListRecentActivityRow struct {
	ID        int64     `json:"id"`
	TaskID    int64     `json:"task_id"`
	ActorID   *int64    `json:"actor_id"`
	Action    string    `json:"action"`
	Detail    string    `json:"detail"`
	CreatedAt time.Time `json:"created_at"`
	ActorName string    `json:"actor_name"`
	TaskTitle string    `json:"task_title"`
}

func (q *Queries) ListRecentActivity(ctx context.Context) ([]ListRecentActivityRow, error) {
	rows, err := q.db.Query(ctx, listRecentActivity)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRecentActivityRow{}
	for rows.Next() {
		var i ListRecentActivityRow
		if err := rows.Scan(
			&i.ID,
			&i.TaskID,
			&i.ActorID,
			&i.Action,
			&i.Detail,
			&i.CreatedAt,
			&i.ActorName,
			&i.TaskTitle,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
