// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: custom_fields.sql

package db

import (
	"context"
)

const createCustomField = `-- name: CreateCustomField :one
INSERT INTO custom_fields (name, field_type, options, position)
VALUES ($1, $2, $3,
        COALESCE((SELECT MAX(position) + 1 FROM custom_fields), 0))
RETURNING id, name, field_type, options, position, created_at
`

type CreateCustomFieldParams struct {
	Name      string   `json:"name"`
	FieldType string   `json:"field_type"`
	Options   []string `json:"options"`
}

func (q *Queries) CreateCustomField(ctx context.Context, arg CreateCustomFieldParams) (CustomField, error) {
	row := q.db.QueryRow(ctx, createCustomField, arg.Name, arg.FieldType, arg.Options)
	var i CustomField
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.FieldType,
		&i.Options,
		&i.Position,
		&i.CreatedAt,
	)
	return i, err
}

const deleteCustomField = `-- name: DeleteCustomField :exec
DELETE FROM custom_fields WHERE id = $1
`

func (q *Queries) DeleteCustomField(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteCustomField, id)
	return err
}

const deleteTaskFieldValue = `-- name: DeleteTaskFieldValue :exec
DELETE FROM task_field_values
WHERE task_id = $1 AND field_id = $2
`

type DeleteTaskFieldValueParams struct {
	TaskID  int64 `json:"task_id"`
	FieldID int64 `json:"field_id"`
}

func (q *Queries) DeleteTaskFieldValue(ctx context.Context, arg DeleteTaskFieldValueParams) error {
	_, err := q.db.Exec(ctx, deleteTaskFieldValue, arg.TaskID, arg.FieldID)
	return err
}

const listCustomFields = `-- name: ListCustomFields :many
SELECT id, name, field_type, options, position, created_at FROM custom_fields
ORDER BY position, id
`

func (q *Queries) ListCustomFields(ctx context.Context) ([]CustomField, error) {
	rows, err := q.db.Query(ctx, listCustomFields)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CustomField{}
	for rows.Next() {
		var i CustomField
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.FieldType,
			&i.Options,
			&i.Position,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTaskFieldValues = `-- name: ListTaskFieldValues :many
SELECT field_id, value FROM task_field_values
WHERE task_id = $1
`

type ListTaskFieldValuesRow struct {
	FieldID int64  `json:"field_id"`
	Value   string `json:"value"`
}

func (q *Queries) ListTaskFieldValues(ctx context.Context, taskID int64) ([]ListTaskFieldValuesRow, error) {
	rows, err := q.db.Query(ctx, listTaskFieldValues, taskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTaskFieldValuesRow{}
	for rows.Next() {
		var i ListTaskFieldValuesRow
		if err := rows.Scan(&i.FieldID, &i.Value); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setTaskFieldValue = `-- name: SetTaskFieldValue :exec
INSERT INTO task_field_values (task_id, field_id, value)
VALUES ($1, $2, $3)
ON CONFLICT (task_id, field_id) DO UPDATE SET value = EXCLUDED.value
`

type SetTaskFieldValueParams struct {
	TaskID  int64  `json:"task_id"`
	FieldID int64  `json:"field_id"`
	Value   string `json:"value"`
}

func (q *Queries) SetTaskFieldValue(ctx context.Context, arg SetTaskFieldValueParams) error {
	_, err := q.db.Exec(ctx, setTaskFieldValue, arg.TaskID, arg.FieldID, arg.Value)
	return err
}

const updateCustomField = `-- name: UpdateCustomField :one
UPDATE custom_fields
SET name = $2, options = $3
WHERE id = $1
RETURNING id, name, field_type, options, position, created_at
`

type UpdateCustomFieldParams struct {
	ID      int64    `json:"id"`
	Name    string   `json:"name"`
	Options []string `json:"options"`
}

func (q *Queries) UpdateCustomField(ctx context.Context, arg UpdateCustomFieldParams) (CustomField, error) {
	row := q.db.QueryRow(ctx, updateCustomField, arg.ID, arg.Name, arg.Options)
	var i CustomField
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.FieldType,
		&i.Options,
		&i.Position,
		&i.CreatedAt,
	)
	return i, err
}
