// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: daily.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countQuotes = `-- name: CountQuotes :one
SELECT count(*) FROM quotes
`

func (q *Queries) CountQuotes(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countQuotes)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createObservance = `-- name: CreateObservance :one
INSERT INTO observances (month, day, name_en, name_ne, scope, note_en,
                         note_ne, source)
VALUES ($1, $2, $3, $4,
        $5, $6, $7,
        $8)
ON CONFLICT (month, day, name_en) DO UPDATE
SET name_ne = EXCLUDED.name_ne,
    scope = EXCLUDED.scope,
    note_en = EXCLUDED.note_en,
    note_ne = EXCLUDED.note_ne,
    source = EXCLUDED.source
RETURNING id, month, day, name_en, name_ne, scope, note_en, note_ne, source, created_at
`

type CreateObservanceParams struct {
	Month  int32  `json:"month"`
	Day    int32  `json:"day"`
	NameEn string `json:"name_en"`
	NameNe string `json:"name_ne"`
	Scope  string `json:"scope"`
	NoteEn string `json:"note_en"`
	NoteNe string `json:"note_ne"`
	Source string `json:"source"`
}

func (q *Queries) CreateObservance(ctx context.Context, arg CreateObservanceParams) (Observance, error) {
	row := q.db.QueryRow(ctx, createObservance,
		arg.Month,
		arg.Day,
		arg.NameEn,
		arg.NameNe,
		arg.Scope,
		arg.NoteEn,
		arg.NoteNe,
		arg.Source,
	)
	var i Observance
	err := row.Scan(
		&i.ID,
		&i.Month,
		&i.Day,
		&i.NameEn,
		&i.NameNe,
		&i.Scope,
		&i.NoteEn,
		&i.NoteNe,
		&i.Source,
		&i.CreatedAt,
	)
	return i, err
}

const createQuote = `-- name: CreateQuote :one
INSERT INTO quotes (text_en, text_ne, author, source)
VALUES ($1, $2, $3,
        $4)
RETURNING id, text_en, text_ne, author, source, created_at
`

type CreateQuoteParams struct {
	TextEn string `json:"text_en"`
	TextNe string `json:"text_ne"`
	Author string `json:"author"`
	Source string `json:"source"`
}

func (q *Queries) CreateQuote(ctx context.Context, arg CreateQuoteParams) (Quote, error) {
	row := q.db.QueryRow(ctx, createQuote,
		arg.TextEn,
		arg.TextNe,
		arg.Author,
		arg.Source,
	)
	var i Quote
	err := row.Scan(
		&i.ID,
		&i.TextEn,
		&i.TextNe,
		&i.Author,
		&i.Source,
		&i.CreatedAt,
	)
	return i, err
}

const createRashifal = `-- name: CreateRashifal :one
INSERT INTO rashifal (rashi, period, from_date, to_date, text_en, text_ne,
                      source)
VALUES ($1, $2, $3,
        $4, $5, $6,
        $7)
ON CONFLICT (rashi, period, from_date) DO UPDATE
SET to_date = EXCLUDED.to_date,
    text_en = EXCLUDED.text_en,
    text_ne = EXCLUDED.text_ne,
    source = EXCLUDED.source
RETURNING id, rashi, period, from_date, to_date, text_en, text_ne, source, created_at
`

type CreateRashifalParams struct {
	Rashi    int32       `json:"rashi"`
	Period   string      `json:"period"`
	FromDate pgtype.Date `json:"from_date"`
	ToDate   pgtype.Date `json:"to_date"`
	TextEn   string      `json:"text_en"`
	TextNe   string      `json:"text_ne"`
	Source   string      `json:"source"`
}

func (q *Queries) CreateRashifal(ctx context.Context, arg CreateRashifalParams) (Rashifal, error) {
	row := q.db.QueryRow(ctx, createRashifal,
		arg.Rashi,
		arg.Period,
		arg.FromDate,
		arg.ToDate,
		arg.TextEn,
		arg.TextNe,
		arg.Source,
	)
	var i Rashifal
	err := row.Scan(
		&i.ID,
		&i.Rashi,
		&i.Period,
		&i.FromDate,
		&i.ToDate,
		&i.TextEn,
		&i.TextNe,
		&i.Source,
		&i.CreatedAt,
	)
	return i, err
}

const deleteObservance = `-- name: DeleteObservance :exec
DELETE FROM observances WHERE id = $1
`

func (q *Queries) DeleteObservance(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteObservance, id)
	return err
}

const deleteQuote = `-- name: DeleteQuote :exec
DELETE FROM quotes WHERE id = $1
`

func (q *Queries) DeleteQuote(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteQuote, id)
	return err
}

const deleteRashifal = `-- name: DeleteRashifal :exec
DELETE FROM rashifal WHERE id = $1
`

func (q *Queries) DeleteRashifal(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteRashifal, id)
	return err
}

const listObservances = `-- name: ListObservances :many
SELECT id, month, day, name_en, name_ne, scope, note_en, note_ne, source, created_at FROM observances ORDER BY month, day, id
`

func (q *Queries) ListObservances(ctx context.Context) ([]Observance, error) {
	rows, err := q.db.Query(ctx, listObservances)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Observance{}
	for rows.Next() {
		var i Observance
		if err := rows.Scan(
			&i.ID,
			&i.Month,
			&i.Day,
			&i.NameEn,
			&i.NameNe,
			&i.Scope,
			&i.NoteEn,
			&i.NoteNe,
			&i.Source,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listQuotes = `-- name: ListQuotes :many
SELECT id, text_en, text_ne, author, source, created_at FROM quotes ORDER BY id
`

func (q *Queries) ListQuotes(ctx context.Context) ([]Quote, error) {
	rows, err := q.db.Query(ctx, listQuotes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Quote{}
	for rows.Next() {
		var i Quote
		if err := rows.Scan(
			&i.ID,
			&i.TextEn,
			&i.TextNe,
			&i.Author,
			&i.Source,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const quoteForDay = `-- name: QuoteForDay :one
SELECT id, text_en, text_ne, author, source, created_at FROM quotes
ORDER BY id
OFFSET ($1::bigint % GREATEST((SELECT count(*) FROM quotes), 1))
LIMIT 1
`

// The quote for a given day, chosen by rotating through the table on the day
// of the year. Deterministic: the same day always gives the same quote, with
// no scheduler and no stored "quote of the day" row to go stale.
func (q *Queries) QuoteForDay(ctx context.Context, dayIndex int64) (Quote, error) {
	row := q.db.QueryRow(ctx, quoteForDay, dayIndex)
	var i Quote
	err := row.Scan(
		&i.ID,
		&i.TextEn,
		&i.TextNe,
		&i.Author,
		&i.Source,
		&i.CreatedAt,
	)
	return i, err
}

const rashifalForDay = `-- name: RashifalForDay :many
SELECT id, rashi, period, from_date, to_date, text_en, text_ne, source, created_at FROM rashifal
WHERE from_date <= $1
  AND to_date >= $1
ORDER BY rashi, period
`

// Every reading that covers a day: the daily one, the week it sits in, and the
// month. One query, so the card can show all three without three round trips.
func (q *Queries) RashifalForDay(ctx context.Context, onDate pgtype.Date) ([]Rashifal, error) {
	rows, err := q.db.Query(ctx, rashifalForDay, onDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Rashifal{}
	for rows.Next() {
		var i Rashifal
		if err := rows.Scan(
			&i.ID,
			&i.Rashi,
			&i.Period,
			&i.FromDate,
			&i.ToDate,
			&i.TextEn,
			&i.TextNe,
			&i.Source,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
