// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: dashboards.sql

package db

import (
	"context"
	"time"
)

const createDashboard = `-- name: CreateDashboard :one
INSERT INTO dashboards (name, owner_id, visibility, widgets)
VALUES ($1, $2, $3,
        $4)
RETURNING id, name, owner_id, visibility, widgets, created_at, updated_at
`

type CreateDashboardParams struct {
	Name       string `json:"name"`
	OwnerID    *int64 `json:"owner_id"`
	Visibility string `json:"visibility"`
	Widgets    string `json:"widgets"`
}

func (q *Queries) CreateDashboard(ctx context.Context, arg CreateDashboardParams) (Dashboard, error) {
	row := q.db.QueryRow(ctx, createDashboard,
		arg.Name,
		arg.OwnerID,
		arg.Visibility,
		arg.Widgets,
	)
	var i Dashboard
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.OwnerID,
		&i.Visibility,
		&i.Widgets,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteDashboard = `-- name: DeleteDashboard :exec
DELETE FROM dashboards WHERE id = $1
`

func (q *Queries) DeleteDashboard(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteDashboard, id)
	return err
}

const getDashboard = `-- name: GetDashboard :one
SELECT d.id, d.name, d.owner_id, d.visibility, d.widgets,
       d.created_at, d.updated_at,
       COALESCE(u.full_name, '')::text AS owner_name
FROM dashboards d
LEFT JOIN users u ON u.id = d.owner_id
WHERE d.id = $1
`

type GetDashboardRow struct {
	ID         int64     `json:"id"`
	Name       string    `json:"name"`
	OwnerID    *int64    `json:"owner_id"`
	Visibility string    `json:"visibility"`
	Widgets    string    `json:"widgets"`
	CreatedAt  time.Time `json:"created_at"`
	UpdatedAt  time.Time `json:"updated_at"`
	OwnerName  string    `json:"owner_name"`
}

func (q *Queries) GetDashboard(ctx context.Context, id int64) (GetDashboardRow, error) {
	row := q.db.QueryRow(ctx, getDashboard, id)
	var i GetDashboardRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.OwnerID,
		&i.Visibility,
		&i.Widgets,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OwnerName,
	)
	return i, err
}

const listDashboards = `-- name: ListDashboards :many
SELECT d.id, d.name, d.owner_id, d.visibility, d.widgets,
       d.created_at, d.updated_at,
       COALESCE(u.full_name, '')::text AS owner_name
FROM dashboards d
LEFT JOIN users u ON u.id = d.owner_id
WHERE d.visibility = 'workspace' OR d.owner_id = $1
ORDER BY d.name ASC
`

type ListDashboardsRow struct {
	ID         int64     `json:"id"`
	Name       string    `json:"name"`
	OwnerID    *int64    `json:"owner_id"`
	Visibility string    `json:"visibility"`
	Widgets    string    `json:"widgets"`
	CreatedAt  time.Time `json:"created_at"`
	UpdatedAt  time.Time `json:"updated_at"`
	OwnerName  string    `json:"owner_name"`
}

func (q *Queries) ListDashboards(ctx context.Context, actor *int64) ([]ListDashboardsRow, error) {
	rows, err := q.db.Query(ctx, listDashboards, actor)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDashboardsRow{}
	for rows.Next() {
		var i ListDashboardsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.OwnerID,
			&i.Visibility,
			&i.Widgets,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.OwnerName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDashboard = `-- name: UpdateDashboard :exec
UPDATE dashboards
SET name = $1, visibility = $2,
    widgets = $3, updated_at = now()
WHERE id = $4
`

type UpdateDashboardParams struct {
	Name       string `json:"name"`
	Visibility string `json:"visibility"`
	Widgets    string `json:"widgets"`
	ID         int64  `json:"id"`
}

func (q *Queries) UpdateDashboard(ctx context.Context, arg UpdateDashboardParams) error {
	_, err := q.db.Exec(ctx, updateDashboard,
		arg.Name,
		arg.Visibility,
		arg.Widgets,
		arg.ID,
	)
	return err
}
