// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: dependencies.sql

package db

import (
	"context"
)

const createDependency = `-- name: CreateDependency :one
INSERT INTO task_dependencies (predecessor_id, successor_id, type)
VALUES ($1, $2, $3)
RETURNING id, predecessor_id, successor_id, type, created_at
`

type CreateDependencyParams struct {
	PredecessorID int64  `json:"predecessor_id"`
	SuccessorID   int64  `json:"successor_id"`
	Type          string `json:"type"`
}

func (q *Queries) CreateDependency(ctx context.Context, arg CreateDependencyParams) (TaskDependency, error) {
	row := q.db.QueryRow(ctx, createDependency, arg.PredecessorID, arg.SuccessorID, arg.Type)
	var i TaskDependency
	err := row.Scan(
		&i.ID,
		&i.PredecessorID,
		&i.SuccessorID,
		&i.Type,
		&i.CreatedAt,
	)
	return i, err
}

const deleteDependency = `-- name: DeleteDependency :exec
DELETE FROM task_dependencies
WHERE id = $1
`

func (q *Queries) DeleteDependency(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteDependency, id)
	return err
}

const listDependencies = `-- name: ListDependencies :many
SELECT id, predecessor_id, successor_id, type, created_at FROM task_dependencies
ORDER BY id
`

func (q *Queries) ListDependencies(ctx context.Context) ([]TaskDependency, error) {
	rows, err := q.db.Query(ctx, listDependencies)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TaskDependency{}
	for rows.Next() {
		var i TaskDependency
		if err := rows.Scan(
			&i.ID,
			&i.PredecessorID,
			&i.SuccessorID,
			&i.Type,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
