// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: digest.sql

package db

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const listMyDueTasks = `-- name: ListMyDueTasks :many
SELECT DISTINCT t.id, t.title, t.status, t.done, t.due_date
FROM tasks t
LEFT JOIN task_assignees ta ON ta.task_id = t.id
WHERE t.due_date IS NOT NULL AND t.done = FALSE
  AND (ta.user_id = $1 OR t.assignee_id = $1)
ORDER BY t.due_date
`

type ListMyDueTasksRow struct {
	ID      int64              `json:"id"`
	Title   string             `json:"title"`
	Status  string             `json:"status"`
	Done    bool               `json:"done"`
	DueDate pgtype.Timestamptz `json:"due_date"`
}

func (q *Queries) ListMyDueTasks(ctx context.Context, userID int64) ([]ListMyDueTasksRow, error) {
	rows, err := q.db.Query(ctx, listMyDueTasks, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMyDueTasksRow{}
	for rows.Next() {
		var i ListMyDueTasksRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Status,
			&i.Done,
			&i.DueDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnreadNotificationsDigest = `-- name: ListUnreadNotificationsDigest :many
SELECT id, type, title, body, link, created_at
FROM notifications
WHERE user_id = $1 AND read = FALSE
ORDER BY created_at DESC
LIMIT 20
`

type ListUnreadNotificationsDigestRow struct {
	ID        int64     `json:"id"`
	Type      string    `json:"type"`
	Title     string    `json:"title"`
	Body      string    `json:"body"`
	Link      string    `json:"link"`
	CreatedAt time.Time `json:"created_at"`
}

func (q *Queries) ListUnreadNotificationsDigest(ctx context.Context, userID *int64) ([]ListUnreadNotificationsDigestRow, error) {
	rows, err := q.db.Query(ctx, listUnreadNotificationsDigest, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUnreadNotificationsDigestRow{}
	for rows.Next() {
		var i ListUnreadNotificationsDigestRow
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.Title,
			&i.Body,
			&i.Link,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
