// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: expenses.sql

package db

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const createExpense = `-- name: CreateExpense :one
INSERT INTO expenses (user_id, project_id, category, amount_cents, spent_on,
                      description, merchant, receipt_url)
VALUES ($1, $2, $3,
        $4, $5, $6,
        $7, $8)
RETURNING id, user_id, project_id, category, amount_cents, spent_on, description, merchant, receipt_url, status, created_at
`

type CreateExpenseParams struct {
	UserID      *int64      `json:"user_id"`
	ProjectID   *int64      `json:"project_id"`
	Category    string      `json:"category"`
	AmountCents int64       `json:"amount_cents"`
	SpentOn     pgtype.Date `json:"spent_on"`
	Description string      `json:"description"`
	Merchant    string      `json:"merchant"`
	ReceiptUrl  string      `json:"receipt_url"`
}

func (q *Queries) CreateExpense(ctx context.Context, arg CreateExpenseParams) (Expense, error) {
	row := q.db.QueryRow(ctx, createExpense,
		arg.UserID,
		arg.ProjectID,
		arg.Category,
		arg.AmountCents,
		arg.SpentOn,
		arg.Description,
		arg.Merchant,
		arg.ReceiptUrl,
	)
	var i Expense
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ProjectID,
		&i.Category,
		&i.AmountCents,
		&i.SpentOn,
		&i.Description,
		&i.Merchant,
		&i.ReceiptUrl,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const deleteExpense = `-- name: DeleteExpense :exec
DELETE FROM expenses WHERE id = $1
`

func (q *Queries) DeleteExpense(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteExpense, id)
	return err
}

const listExpenses = `-- name: ListExpenses :many
SELECT e.id, e.user_id, e.project_id, e.category, e.amount_cents, e.spent_on, e.description, e.merchant, e.receipt_url, e.status, e.created_at, COALESCE(u.full_name, '')::text AS submitter_name,
       COALESCE(p.name, '')::text AS project_name
FROM expenses e
LEFT JOIN users u ON u.id = e.user_id
LEFT JOIN projects p ON p.id = e.project_id
ORDER BY e.spent_on DESC NULLS LAST, e.id DESC
`

type ListExpensesRow struct {
	ID            int64       `json:"id"`
	UserID        *int64      `json:"user_id"`
	ProjectID     *int64      `json:"project_id"`
	Category      string      `json:"category"`
	AmountCents   int64       `json:"amount_cents"`
	SpentOn       pgtype.Date `json:"spent_on"`
	Description   string      `json:"description"`
	Merchant      string      `json:"merchant"`
	ReceiptUrl    string      `json:"receipt_url"`
	Status        string      `json:"status"`
	CreatedAt     time.Time   `json:"created_at"`
	SubmitterName string      `json:"submitter_name"`
	ProjectName   string      `json:"project_name"`
}

func (q *Queries) ListExpenses(ctx context.Context) ([]ListExpensesRow, error) {
	rows, err := q.db.Query(ctx, listExpenses)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListExpensesRow{}
	for rows.Next() {
		var i ListExpensesRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ProjectID,
			&i.Category,
			&i.AmountCents,
			&i.SpentOn,
			&i.Description,
			&i.Merchant,
			&i.ReceiptUrl,
			&i.Status,
			&i.CreatedAt,
			&i.SubmitterName,
			&i.ProjectName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setExpenseStatus = `-- name: SetExpenseStatus :one
UPDATE expenses SET status = $1 WHERE id = $2
RETURNING id, user_id, project_id, category, amount_cents, spent_on, description, merchant, receipt_url, status, created_at
`

type SetExpenseStatusParams struct {
	Status string `json:"status"`
	ID     int64  `json:"id"`
}

func (q *Queries) SetExpenseStatus(ctx context.Context, arg SetExpenseStatusParams) (Expense, error) {
	row := q.db.QueryRow(ctx, setExpenseStatus, arg.Status, arg.ID)
	var i Expense
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ProjectID,
		&i.Category,
		&i.AmountCents,
		&i.SpentOn,
		&i.Description,
		&i.Merchant,
		&i.ReceiptUrl,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const updateExpense = `-- name: UpdateExpense :one
UPDATE expenses
SET project_id = $1,
    category = $2,
    amount_cents = $3,
    spent_on = $4,
    description = $5,
    merchant = $6,
    receipt_url = $7
WHERE id = $8
RETURNING id, user_id, project_id, category, amount_cents, spent_on, description, merchant, receipt_url, status, created_at
`

type UpdateExpenseParams struct {
	ProjectID   *int64      `json:"project_id"`
	Category    string      `json:"category"`
	AmountCents int64       `json:"amount_cents"`
	SpentOn     pgtype.Date `json:"spent_on"`
	Description string      `json:"description"`
	Merchant    string      `json:"merchant"`
	ReceiptUrl  string      `json:"receipt_url"`
	ID          int64       `json:"id"`
}

func (q *Queries) UpdateExpense(ctx context.Context, arg UpdateExpenseParams) (Expense, error) {
	row := q.db.QueryRow(ctx, updateExpense,
		arg.ProjectID,
		arg.Category,
		arg.AmountCents,
		arg.SpentOn,
		arg.Description,
		arg.Merchant,
		arg.ReceiptUrl,
		arg.ID,
	)
	var i Expense
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ProjectID,
		&i.Category,
		&i.AmountCents,
		&i.SpentOn,
		&i.Description,
		&i.Merchant,
		&i.ReceiptUrl,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}
