// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: form_responses.sql

package db

import (
	"context"
	"time"
)

const countFormResponses = `-- name: CountFormResponses :one
SELECT COUNT(*) FROM form_responses WHERE page_id = $1
`

func (q *Queries) CountFormResponses(ctx context.Context, pageID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countFormResponses, pageID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createFormResponse = `-- name: CreateFormResponse :one
INSERT INTO form_responses (page_id, submitted_by, answers)
VALUES ($1, $2, $3)
RETURNING id, page_id, submitted_by, answers, created_at
`

type CreateFormResponseParams struct {
	PageID      int64  `json:"page_id"`
	SubmittedBy *int64 `json:"submitted_by"`
	Answers     string `json:"answers"`
}

func (q *Queries) CreateFormResponse(ctx context.Context, arg CreateFormResponseParams) (FormResponse, error) {
	row := q.db.QueryRow(ctx, createFormResponse, arg.PageID, arg.SubmittedBy, arg.Answers)
	var i FormResponse
	err := row.Scan(
		&i.ID,
		&i.PageID,
		&i.SubmittedBy,
		&i.Answers,
		&i.CreatedAt,
	)
	return i, err
}

const listFormResponses = `-- name: ListFormResponses :many
SELECT fr.id, fr.answers, fr.created_at,
       COALESCE(u.full_name, '')::text AS submitted_by_name
FROM form_responses fr
LEFT JOIN users u ON u.id = fr.submitted_by
WHERE fr.page_id = $1
ORDER BY fr.created_at DESC
`

type ListFormResponsesRow struct {
	ID              int64     `json:"id"`
	Answers         string    `json:"answers"`
	CreatedAt       time.Time `json:"created_at"`
	SubmittedByName string    `json:"submitted_by_name"`
}

func (q *Queries) ListFormResponses(ctx context.Context, pageID int64) ([]ListFormResponsesRow, error) {
	rows, err := q.db.Query(ctx, listFormResponses, pageID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListFormResponsesRow{}
	for rows.Next() {
		var i ListFormResponsesRow
		if err := rows.Scan(
			&i.ID,
			&i.Answers,
			&i.CreatedAt,
			&i.SubmittedByName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
