// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: git.sql

package db

import (
	"context"
	"time"
)

const createRepo = `-- name: CreateRepo :one
INSERT INTO git_repos (name, provider, url, default_branch, project_id,
                       webhook_token)
VALUES ($1, $2, $3,
        $4, $5,
        $6)
RETURNING id, name, provider, url, default_branch, project_id, webhook_token, created_at
`

type CreateRepoParams struct {
	Name          string `json:"name"`
	Provider      string `json:"provider"`
	Url           string `json:"url"`
	DefaultBranch string `json:"default_branch"`
	ProjectID     *int64 `json:"project_id"`
	WebhookToken  string `json:"webhook_token"`
}

func (q *Queries) CreateRepo(ctx context.Context, arg CreateRepoParams) (GitRepo, error) {
	row := q.db.QueryRow(ctx, createRepo,
		arg.Name,
		arg.Provider,
		arg.Url,
		arg.DefaultBranch,
		arg.ProjectID,
		arg.WebhookToken,
	)
	var i GitRepo
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Provider,
		&i.Url,
		&i.DefaultBranch,
		&i.ProjectID,
		&i.WebhookToken,
		&i.CreatedAt,
	)
	return i, err
}

const deleteRepo = `-- name: DeleteRepo :exec
DELETE FROM git_repos WHERE id = $1
`

func (q *Queries) DeleteRepo(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteRepo, id)
	return err
}

const getRepoByToken = `-- name: GetRepoByToken :one
SELECT id, name, provider, url, default_branch, project_id, webhook_token, created_at FROM git_repos WHERE webhook_token = $1
`

func (q *Queries) GetRepoByToken(ctx context.Context, webhookToken string) (GitRepo, error) {
	row := q.db.QueryRow(ctx, getRepoByToken, webhookToken)
	var i GitRepo
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Provider,
		&i.Url,
		&i.DefaultBranch,
		&i.ProjectID,
		&i.WebhookToken,
		&i.CreatedAt,
	)
	return i, err
}

const insertCommit = `-- name: InsertCommit :exec
INSERT INTO git_commits (repo_id, sha, message, author_name, author_email,
                         url, branch, task_ref, committed_at)
VALUES ($1, $2, $3,
        $4, $5, $6,
        $7, $8, $9)
ON CONFLICT (repo_id, sha) DO NOTHING
`

type InsertCommitParams struct {
	RepoID      int64     `json:"repo_id"`
	Sha         string    `json:"sha"`
	Message     string    `json:"message"`
	AuthorName  string    `json:"author_name"`
	AuthorEmail string    `json:"author_email"`
	Url         string    `json:"url"`
	Branch      string    `json:"branch"`
	TaskRef     *int64    `json:"task_ref"`
	CommittedAt time.Time `json:"committed_at"`
}

func (q *Queries) InsertCommit(ctx context.Context, arg InsertCommitParams) error {
	_, err := q.db.Exec(ctx, insertCommit,
		arg.RepoID,
		arg.Sha,
		arg.Message,
		arg.AuthorName,
		arg.AuthorEmail,
		arg.Url,
		arg.Branch,
		arg.TaskRef,
		arg.CommittedAt,
	)
	return err
}

const listCommits = `-- name: ListCommits :many
SELECT c.id, c.repo_id, c.sha, c.message, c.author_name, c.author_email, c.url, c.branch, c.task_ref, c.committed_at, c.created_at, r.name AS repo_name,
       COALESCE(t.title, '')::text AS task_title
FROM git_commits c
JOIN git_repos r ON r.id = c.repo_id
LEFT JOIN tasks t ON t.id = c.task_ref
ORDER BY c.committed_at DESC
LIMIT 200
`

type ListCommitsRow struct {
	ID          int64     `json:"id"`
	RepoID      int64     `json:"repo_id"`
	Sha         string    `json:"sha"`
	Message     string    `json:"message"`
	AuthorName  string    `json:"author_name"`
	AuthorEmail string    `json:"author_email"`
	Url         string    `json:"url"`
	Branch      string    `json:"branch"`
	TaskRef     *int64    `json:"task_ref"`
	CommittedAt time.Time `json:"committed_at"`
	CreatedAt   time.Time `json:"created_at"`
	RepoName    string    `json:"repo_name"`
	TaskTitle   string    `json:"task_title"`
}

func (q *Queries) ListCommits(ctx context.Context) ([]ListCommitsRow, error) {
	rows, err := q.db.Query(ctx, listCommits)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCommitsRow{}
	for rows.Next() {
		var i ListCommitsRow
		if err := rows.Scan(
			&i.ID,
			&i.RepoID,
			&i.Sha,
			&i.Message,
			&i.AuthorName,
			&i.AuthorEmail,
			&i.Url,
			&i.Branch,
			&i.TaskRef,
			&i.CommittedAt,
			&i.CreatedAt,
			&i.RepoName,
			&i.TaskTitle,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRepos = `-- name: ListRepos :many
SELECT r.id, r.name, r.provider, r.url, r.default_branch, r.project_id, r.webhook_token, r.created_at,
       COALESCE(p.name, '')::text AS project_name,
       COALESCE((
           SELECT COUNT(*) FROM git_commits c WHERE c.repo_id = r.id
       ), 0)::bigint AS commit_count,
       (
           SELECT MAX(c.committed_at) FROM git_commits c WHERE c.repo_id = r.id
       ) AS last_commit_at
FROM git_repos r
LEFT JOIN projects p ON p.id = r.project_id
ORDER BY r.name, r.id
`

type ListReposRow struct {
	ID            int64       `json:"id"`
	Name          string      `json:"name"`
	Provider      string      `json:"provider"`
	Url           string      `json:"url"`
	DefaultBranch string      `json:"default_branch"`
	ProjectID     *int64      `json:"project_id"`
	WebhookToken  string      `json:"webhook_token"`
	CreatedAt     time.Time   `json:"created_at"`
	ProjectName   string      `json:"project_name"`
	CommitCount   int64       `json:"commit_count"`
	LastCommitAt  interface{} `json:"last_commit_at"`
}

func (q *Queries) ListRepos(ctx context.Context) ([]ListReposRow, error) {
	rows, err := q.db.Query(ctx, listRepos)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListReposRow{}
	for rows.Next() {
		var i ListReposRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Provider,
			&i.Url,
			&i.DefaultBranch,
			&i.ProjectID,
			&i.WebhookToken,
			&i.CreatedAt,
			&i.ProjectName,
			&i.CommitCount,
			&i.LastCommitAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
