// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: holidays.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createHoliday = `-- name: CreateHoliday :one
INSERT INTO holidays (holiday_date, name_en, name_ne, is_public)
VALUES ($1, $2, $3,
        $4)
ON CONFLICT (holiday_date, name_en) DO UPDATE
SET name_ne = EXCLUDED.name_ne, is_public = EXCLUDED.is_public
RETURNING id, holiday_date, name_en, name_ne, is_public, created_at
`

type CreateHolidayParams struct {
	HolidayDate pgtype.Date `json:"holiday_date"`
	NameEn      string      `json:"name_en"`
	NameNe      string      `json:"name_ne"`
	IsPublic    bool        `json:"is_public"`
}

func (q *Queries) CreateHoliday(ctx context.Context, arg CreateHolidayParams) (Holiday, error) {
	row := q.db.QueryRow(ctx, createHoliday,
		arg.HolidayDate,
		arg.NameEn,
		arg.NameNe,
		arg.IsPublic,
	)
	var i Holiday
	err := row.Scan(
		&i.ID,
		&i.HolidayDate,
		&i.NameEn,
		&i.NameNe,
		&i.IsPublic,
		&i.CreatedAt,
	)
	return i, err
}

const deleteHoliday = `-- name: DeleteHoliday :exec
DELETE FROM holidays WHERE id = $1
`

func (q *Queries) DeleteHoliday(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteHoliday, id)
	return err
}

const listHolidays = `-- name: ListHolidays :many
SELECT id, holiday_date, name_en, name_ne, is_public, created_at FROM holidays
WHERE holiday_date >= $1
  AND holiday_date <= $2
ORDER BY holiday_date, id
`

type ListHolidaysParams struct {
	FromDate pgtype.Date `json:"from_date"`
	ToDate   pgtype.Date `json:"to_date"`
}

func (q *Queries) ListHolidays(ctx context.Context, arg ListHolidaysParams) ([]Holiday, error) {
	rows, err := q.db.Query(ctx, listHolidays, arg.FromDate, arg.ToDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Holiday{}
	for rows.Next() {
		var i Holiday
		if err := rows.Scan(
			&i.ID,
			&i.HolidayDate,
			&i.NameEn,
			&i.NameNe,
			&i.IsPublic,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
