// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: holidays.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createHoliday = `-- name: CreateHoliday :one
INSERT INTO holidays (holiday_date, name_en, name_ne, is_public, category,
                      description_en, description_ne, history_en, history_ne,
                      importance_en, importance_ne, celebration_en,
                      celebration_ne, aliases, is_government, is_bank,
                      is_school, is_optional, observed_by)
VALUES ($1, $2, $3,
        $4, $5,
        $6, $7,
        $8, $9,
        $10, $11,
        $12, $13,
        $14, $15, $16,
        $17, $18, $19)
ON CONFLICT (holiday_date, name_en) DO UPDATE
SET name_ne = EXCLUDED.name_ne,
    is_public = EXCLUDED.is_public,
    category = EXCLUDED.category,
    description_en = EXCLUDED.description_en,
    description_ne = EXCLUDED.description_ne,
    history_en = EXCLUDED.history_en,
    history_ne = EXCLUDED.history_ne,
    importance_en = EXCLUDED.importance_en,
    importance_ne = EXCLUDED.importance_ne,
    celebration_en = EXCLUDED.celebration_en,
    celebration_ne = EXCLUDED.celebration_ne,
    aliases = EXCLUDED.aliases,
    is_government = EXCLUDED.is_government,
    is_bank = EXCLUDED.is_bank,
    is_school = EXCLUDED.is_school,
    is_optional = EXCLUDED.is_optional,
    observed_by = EXCLUDED.observed_by
RETURNING id, holiday_date, name_en, name_ne, is_public, created_at, category, description_en, description_ne, history_en, history_ne, importance_en, importance_ne, celebration_en, celebration_ne, aliases, is_government, is_bank, is_school, is_optional, observed_by
`

type CreateHolidayParams struct {
	HolidayDate   pgtype.Date `json:"holiday_date"`
	NameEn        string      `json:"name_en"`
	NameNe        string      `json:"name_ne"`
	IsPublic      bool        `json:"is_public"`
	Category      string      `json:"category"`
	DescriptionEn string      `json:"description_en"`
	DescriptionNe string      `json:"description_ne"`
	HistoryEn     string      `json:"history_en"`
	HistoryNe     string      `json:"history_ne"`
	ImportanceEn  string      `json:"importance_en"`
	ImportanceNe  string      `json:"importance_ne"`
	CelebrationEn string      `json:"celebration_en"`
	CelebrationNe string      `json:"celebration_ne"`
	Aliases       string      `json:"aliases"`
	IsGovernment  bool        `json:"is_government"`
	IsBank        bool        `json:"is_bank"`
	IsSchool      bool        `json:"is_school"`
	IsOptional    bool        `json:"is_optional"`
	ObservedBy    string      `json:"observed_by"`
}

func (q *Queries) CreateHoliday(ctx context.Context, arg CreateHolidayParams) (Holiday, error) {
	row := q.db.QueryRow(ctx, createHoliday,
		arg.HolidayDate,
		arg.NameEn,
		arg.NameNe,
		arg.IsPublic,
		arg.Category,
		arg.DescriptionEn,
		arg.DescriptionNe,
		arg.HistoryEn,
		arg.HistoryNe,
		arg.ImportanceEn,
		arg.ImportanceNe,
		arg.CelebrationEn,
		arg.CelebrationNe,
		arg.Aliases,
		arg.IsGovernment,
		arg.IsBank,
		arg.IsSchool,
		arg.IsOptional,
		arg.ObservedBy,
	)
	var i Holiday
	err := row.Scan(
		&i.ID,
		&i.HolidayDate,
		&i.NameEn,
		&i.NameNe,
		&i.IsPublic,
		&i.CreatedAt,
		&i.Category,
		&i.DescriptionEn,
		&i.DescriptionNe,
		&i.HistoryEn,
		&i.HistoryNe,
		&i.ImportanceEn,
		&i.ImportanceNe,
		&i.CelebrationEn,
		&i.CelebrationNe,
		&i.Aliases,
		&i.IsGovernment,
		&i.IsBank,
		&i.IsSchool,
		&i.IsOptional,
		&i.ObservedBy,
	)
	return i, err
}

const deleteHoliday = `-- name: DeleteHoliday :exec
DELETE FROM holidays WHERE id = $1
`

func (q *Queries) DeleteHoliday(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteHoliday, id)
	return err
}

const dueHolidayReminders = `-- name: DueHolidayReminders :many
SELECT u.id AS user_id,
       u.holiday_remind_days,
       h.id AS holiday_id,
       h.holiday_date,
       h.name_en,
       h.name_ne
FROM users u
CROSS JOIN holidays h
LEFT JOIN holiday_reminders_sent s
       ON s.user_id = u.id AND s.holiday_id = h.id
WHERE u.holiday_remind_days IS NOT NULL
  AND u.status = 'active'
  AND h.is_public
  AND s.user_id IS NULL
  AND h.holiday_date >= CURRENT_DATE
  AND h.holiday_date <= CURRENT_DATE + u.holiday_remind_days
ORDER BY h.holiday_date, u.id
LIMIT 1000
`

type DueHolidayRemindersRow struct {
	UserID            int64       `json:"user_id"`
	HolidayRemindDays *int32      `json:"holiday_remind_days"`
	HolidayID         int64       `json:"holiday_id"`
	HolidayDate       pgtype.Date `json:"holiday_date"`
	NameEn            string      `json:"name_en"`
	NameNe            string      `json:"name_ne"`
}

// Every (user, holiday) pair that is due a reminder: the user has opted in, the
// holiday falls inside their notice period, and they have not been told yet.
//
// The LEFT JOIN ... IS NULL is what makes it idempotent — the sweep can run
// every half hour without telling anyone twice.
func (q *Queries) DueHolidayReminders(ctx context.Context) ([]DueHolidayRemindersRow, error) {
	rows, err := q.db.Query(ctx, dueHolidayReminders)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DueHolidayRemindersRow{}
	for rows.Next() {
		var i DueHolidayRemindersRow
		if err := rows.Scan(
			&i.UserID,
			&i.HolidayRemindDays,
			&i.HolidayID,
			&i.HolidayDate,
			&i.NameEn,
			&i.NameNe,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getHolidayRemindDays = `-- name: GetHolidayRemindDays :one
SELECT holiday_remind_days FROM users WHERE id = $1
`

func (q *Queries) GetHolidayRemindDays(ctx context.Context, id int64) (*int32, error) {
	row := q.db.QueryRow(ctx, getHolidayRemindDays, id)
	var holiday_remind_days *int32
	err := row.Scan(&holiday_remind_days)
	return holiday_remind_days, err
}

const listHolidays = `-- name: ListHolidays :many
SELECT id, holiday_date, name_en, name_ne, is_public, created_at, category, description_en, description_ne, history_en, history_ne, importance_en, importance_ne, celebration_en, celebration_ne, aliases, is_government, is_bank, is_school, is_optional, observed_by FROM holidays
WHERE holiday_date >= $1
  AND holiday_date <= $2
ORDER BY holiday_date, id
`

type ListHolidaysParams struct {
	FromDate pgtype.Date `json:"from_date"`
	ToDate   pgtype.Date `json:"to_date"`
}

func (q *Queries) ListHolidays(ctx context.Context, arg ListHolidaysParams) ([]Holiday, error) {
	rows, err := q.db.Query(ctx, listHolidays, arg.FromDate, arg.ToDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Holiday{}
	for rows.Next() {
		var i Holiday
		if err := rows.Scan(
			&i.ID,
			&i.HolidayDate,
			&i.NameEn,
			&i.NameNe,
			&i.IsPublic,
			&i.CreatedAt,
			&i.Category,
			&i.DescriptionEn,
			&i.DescriptionNe,
			&i.HistoryEn,
			&i.HistoryNe,
			&i.ImportanceEn,
			&i.ImportanceNe,
			&i.CelebrationEn,
			&i.CelebrationNe,
			&i.Aliases,
			&i.IsGovernment,
			&i.IsBank,
			&i.IsSchool,
			&i.IsOptional,
			&i.ObservedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markHolidayReminded = `-- name: MarkHolidayReminded :exec
INSERT INTO holiday_reminders_sent (user_id, holiday_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type MarkHolidayRemindedParams struct {
	UserID    int64 `json:"user_id"`
	HolidayID int64 `json:"holiday_id"`
}

func (q *Queries) MarkHolidayReminded(ctx context.Context, arg MarkHolidayRemindedParams) error {
	_, err := q.db.Exec(ctx, markHolidayReminded, arg.UserID, arg.HolidayID)
	return err
}

const setHolidayRemindDays = `-- name: SetHolidayRemindDays :exec
UPDATE users SET holiday_remind_days = $1
WHERE id = $2
`

type SetHolidayRemindDaysParams struct {
	HolidayRemindDays *int32 `json:"holiday_remind_days"`
	ID                int64  `json:"id"`
}

func (q *Queries) SetHolidayRemindDays(ctx context.Context, arg SetHolidayRemindDaysParams) error {
	_, err := q.db.Exec(ctx, setHolidayRemindDays, arg.HolidayRemindDays, arg.ID)
	return err
}

const updateHoliday = `-- name: UpdateHoliday :one
UPDATE holidays
SET holiday_date = $1,
    name_en = $2,
    name_ne = $3,
    is_public = $4,
    category = $5,
    description_en = $6,
    description_ne = $7,
    history_en = $8,
    history_ne = $9,
    importance_en = $10,
    importance_ne = $11,
    celebration_en = $12,
    celebration_ne = $13,
    aliases = $14,
    is_government = $15,
    is_bank = $16,
    is_school = $17,
    is_optional = $18,
    observed_by = $19
WHERE id = $20
RETURNING id, holiday_date, name_en, name_ne, is_public, created_at, category, description_en, description_ne, history_en, history_ne, importance_en, importance_ne, celebration_en, celebration_ne, aliases, is_government, is_bank, is_school, is_optional, observed_by
`

type UpdateHolidayParams struct {
	HolidayDate   pgtype.Date `json:"holiday_date"`
	NameEn        string      `json:"name_en"`
	NameNe        string      `json:"name_ne"`
	IsPublic      bool        `json:"is_public"`
	Category      string      `json:"category"`
	DescriptionEn string      `json:"description_en"`
	DescriptionNe string      `json:"description_ne"`
	HistoryEn     string      `json:"history_en"`
	HistoryNe     string      `json:"history_ne"`
	ImportanceEn  string      `json:"importance_en"`
	ImportanceNe  string      `json:"importance_ne"`
	CelebrationEn string      `json:"celebration_en"`
	CelebrationNe string      `json:"celebration_ne"`
	Aliases       string      `json:"aliases"`
	IsGovernment  bool        `json:"is_government"`
	IsBank        bool        `json:"is_bank"`
	IsSchool      bool        `json:"is_school"`
	IsOptional    bool        `json:"is_optional"`
	ObservedBy    string      `json:"observed_by"`
	ID            int64       `json:"id"`
}

func (q *Queries) UpdateHoliday(ctx context.Context, arg UpdateHolidayParams) (Holiday, error) {
	row := q.db.QueryRow(ctx, updateHoliday,
		arg.HolidayDate,
		arg.NameEn,
		arg.NameNe,
		arg.IsPublic,
		arg.Category,
		arg.DescriptionEn,
		arg.DescriptionNe,
		arg.HistoryEn,
		arg.HistoryNe,
		arg.ImportanceEn,
		arg.ImportanceNe,
		arg.CelebrationEn,
		arg.CelebrationNe,
		arg.Aliases,
		arg.IsGovernment,
		arg.IsBank,
		arg.IsSchool,
		arg.IsOptional,
		arg.ObservedBy,
		arg.ID,
	)
	var i Holiday
	err := row.Scan(
		&i.ID,
		&i.HolidayDate,
		&i.NameEn,
		&i.NameNe,
		&i.IsPublic,
		&i.CreatedAt,
		&i.Category,
		&i.DescriptionEn,
		&i.DescriptionNe,
		&i.HistoryEn,
		&i.HistoryNe,
		&i.ImportanceEn,
		&i.ImportanceNe,
		&i.CelebrationEn,
		&i.CelebrationNe,
		&i.Aliases,
		&i.IsGovernment,
		&i.IsBank,
		&i.IsSchool,
		&i.IsOptional,
		&i.ObservedBy,
	)
	return i, err
}
