// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: holidays.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createHoliday = `-- name: CreateHoliday :one
INSERT INTO holidays (holiday_date, name_en, name_ne, is_public, category,
                      description_en, description_ne, history_en, history_ne,
                      importance_en, importance_ne, celebration_en,
                      celebration_ne, aliases)
VALUES ($1, $2, $3,
        $4, $5,
        $6, $7,
        $8, $9,
        $10, $11,
        $12, $13,
        $14)
ON CONFLICT (holiday_date, name_en) DO UPDATE
SET name_ne = EXCLUDED.name_ne,
    is_public = EXCLUDED.is_public,
    category = EXCLUDED.category,
    description_en = EXCLUDED.description_en,
    description_ne = EXCLUDED.description_ne,
    history_en = EXCLUDED.history_en,
    history_ne = EXCLUDED.history_ne,
    importance_en = EXCLUDED.importance_en,
    importance_ne = EXCLUDED.importance_ne,
    celebration_en = EXCLUDED.celebration_en,
    celebration_ne = EXCLUDED.celebration_ne,
    aliases = EXCLUDED.aliases
RETURNING id, holiday_date, name_en, name_ne, is_public, created_at, category, description_en, description_ne, history_en, history_ne, importance_en, importance_ne, celebration_en, celebration_ne, aliases
`

type CreateHolidayParams struct {
	HolidayDate   pgtype.Date `json:"holiday_date"`
	NameEn        string      `json:"name_en"`
	NameNe        string      `json:"name_ne"`
	IsPublic      bool        `json:"is_public"`
	Category      string      `json:"category"`
	DescriptionEn string      `json:"description_en"`
	DescriptionNe string      `json:"description_ne"`
	HistoryEn     string      `json:"history_en"`
	HistoryNe     string      `json:"history_ne"`
	ImportanceEn  string      `json:"importance_en"`
	ImportanceNe  string      `json:"importance_ne"`
	CelebrationEn string      `json:"celebration_en"`
	CelebrationNe string      `json:"celebration_ne"`
	Aliases       string      `json:"aliases"`
}

func (q *Queries) CreateHoliday(ctx context.Context, arg CreateHolidayParams) (Holiday, error) {
	row := q.db.QueryRow(ctx, createHoliday,
		arg.HolidayDate,
		arg.NameEn,
		arg.NameNe,
		arg.IsPublic,
		arg.Category,
		arg.DescriptionEn,
		arg.DescriptionNe,
		arg.HistoryEn,
		arg.HistoryNe,
		arg.ImportanceEn,
		arg.ImportanceNe,
		arg.CelebrationEn,
		arg.CelebrationNe,
		arg.Aliases,
	)
	var i Holiday
	err := row.Scan(
		&i.ID,
		&i.HolidayDate,
		&i.NameEn,
		&i.NameNe,
		&i.IsPublic,
		&i.CreatedAt,
		&i.Category,
		&i.DescriptionEn,
		&i.DescriptionNe,
		&i.HistoryEn,
		&i.HistoryNe,
		&i.ImportanceEn,
		&i.ImportanceNe,
		&i.CelebrationEn,
		&i.CelebrationNe,
		&i.Aliases,
	)
	return i, err
}

const deleteHoliday = `-- name: DeleteHoliday :exec
DELETE FROM holidays WHERE id = $1
`

func (q *Queries) DeleteHoliday(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteHoliday, id)
	return err
}

const listHolidays = `-- name: ListHolidays :many
SELECT id, holiday_date, name_en, name_ne, is_public, created_at, category, description_en, description_ne, history_en, history_ne, importance_en, importance_ne, celebration_en, celebration_ne, aliases FROM holidays
WHERE holiday_date >= $1
  AND holiday_date <= $2
ORDER BY holiday_date, id
`

type ListHolidaysParams struct {
	FromDate pgtype.Date `json:"from_date"`
	ToDate   pgtype.Date `json:"to_date"`
}

func (q *Queries) ListHolidays(ctx context.Context, arg ListHolidaysParams) ([]Holiday, error) {
	rows, err := q.db.Query(ctx, listHolidays, arg.FromDate, arg.ToDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Holiday{}
	for rows.Next() {
		var i Holiday
		if err := rows.Scan(
			&i.ID,
			&i.HolidayDate,
			&i.NameEn,
			&i.NameNe,
			&i.IsPublic,
			&i.CreatedAt,
			&i.Category,
			&i.DescriptionEn,
			&i.DescriptionNe,
			&i.HistoryEn,
			&i.HistoryNe,
			&i.ImportanceEn,
			&i.ImportanceNe,
			&i.CelebrationEn,
			&i.CelebrationNe,
			&i.Aliases,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateHoliday = `-- name: UpdateHoliday :one
UPDATE holidays
SET holiday_date = $1,
    name_en = $2,
    name_ne = $3,
    is_public = $4,
    category = $5,
    description_en = $6,
    description_ne = $7,
    history_en = $8,
    history_ne = $9,
    importance_en = $10,
    importance_ne = $11,
    celebration_en = $12,
    celebration_ne = $13,
    aliases = $14
WHERE id = $15
RETURNING id, holiday_date, name_en, name_ne, is_public, created_at, category, description_en, description_ne, history_en, history_ne, importance_en, importance_ne, celebration_en, celebration_ne, aliases
`

type UpdateHolidayParams struct {
	HolidayDate   pgtype.Date `json:"holiday_date"`
	NameEn        string      `json:"name_en"`
	NameNe        string      `json:"name_ne"`
	IsPublic      bool        `json:"is_public"`
	Category      string      `json:"category"`
	DescriptionEn string      `json:"description_en"`
	DescriptionNe string      `json:"description_ne"`
	HistoryEn     string      `json:"history_en"`
	HistoryNe     string      `json:"history_ne"`
	ImportanceEn  string      `json:"importance_en"`
	ImportanceNe  string      `json:"importance_ne"`
	CelebrationEn string      `json:"celebration_en"`
	CelebrationNe string      `json:"celebration_ne"`
	Aliases       string      `json:"aliases"`
	ID            int64       `json:"id"`
}

func (q *Queries) UpdateHoliday(ctx context.Context, arg UpdateHolidayParams) (Holiday, error) {
	row := q.db.QueryRow(ctx, updateHoliday,
		arg.HolidayDate,
		arg.NameEn,
		arg.NameNe,
		arg.IsPublic,
		arg.Category,
		arg.DescriptionEn,
		arg.DescriptionNe,
		arg.HistoryEn,
		arg.HistoryNe,
		arg.ImportanceEn,
		arg.ImportanceNe,
		arg.CelebrationEn,
		arg.CelebrationNe,
		arg.Aliases,
		arg.ID,
	)
	var i Holiday
	err := row.Scan(
		&i.ID,
		&i.HolidayDate,
		&i.NameEn,
		&i.NameNe,
		&i.IsPublic,
		&i.CreatedAt,
		&i.Category,
		&i.DescriptionEn,
		&i.DescriptionNe,
		&i.HistoryEn,
		&i.HistoryNe,
		&i.ImportanceEn,
		&i.ImportanceNe,
		&i.CelebrationEn,
		&i.CelebrationNe,
		&i.Aliases,
	)
	return i, err
}
