// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: incidents.sql

package db

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const createIncident = `-- name: CreateIncident :one
INSERT INTO incidents (title, description, kind, severity, project_id,
                       assignee_id, reporter_id, component)
VALUES ($1, $2, $3,
        $4, $5, $6,
        $7, $8)
RETURNING id, title, description, kind, severity, status, project_id, assignee_id, reporter_id, component, resolved_at, created_at
`

type CreateIncidentParams struct {
	Title       string `json:"title"`
	Description string `json:"description"`
	Kind        string `json:"kind"`
	Severity    string `json:"severity"`
	ProjectID   *int64 `json:"project_id"`
	AssigneeID  *int64 `json:"assignee_id"`
	ReporterID  *int64 `json:"reporter_id"`
	Component   string `json:"component"`
}

func (q *Queries) CreateIncident(ctx context.Context, arg CreateIncidentParams) (Incident, error) {
	row := q.db.QueryRow(ctx, createIncident,
		arg.Title,
		arg.Description,
		arg.Kind,
		arg.Severity,
		arg.ProjectID,
		arg.AssigneeID,
		arg.ReporterID,
		arg.Component,
	)
	var i Incident
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Kind,
		&i.Severity,
		&i.Status,
		&i.ProjectID,
		&i.AssigneeID,
		&i.ReporterID,
		&i.Component,
		&i.ResolvedAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteIncident = `-- name: DeleteIncident :exec
DELETE FROM incidents WHERE id = $1
`

func (q *Queries) DeleteIncident(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteIncident, id)
	return err
}

const listIncidents = `-- name: ListIncidents :many
SELECT i.id, i.title, i.description, i.kind, i.severity, i.status, i.project_id, i.assignee_id, i.reporter_id, i.component, i.resolved_at, i.created_at,
       COALESCE(a.full_name, '')::text AS assignee_name,
       COALESCE(r.full_name, '')::text AS reporter_name,
       COALESCE(p.name, '')::text AS project_name
FROM incidents i
LEFT JOIN users a ON a.id = i.assignee_id
LEFT JOIN users r ON r.id = i.reporter_id
LEFT JOIN projects p ON p.id = i.project_id
ORDER BY
    CASE i.status
        WHEN 'open' THEN 0
        WHEN 'investigating' THEN 1
        WHEN 'mitigated' THEN 2
        WHEN 'resolved' THEN 3
        ELSE 4
    END,
    CASE i.severity
        WHEN 'critical' THEN 0
        WHEN 'high' THEN 1
        WHEN 'medium' THEN 2
        ELSE 3
    END,
    i.created_at DESC
`

type ListIncidentsRow struct {
	ID           int64              `json:"id"`
	Title        string             `json:"title"`
	Description  string             `json:"description"`
	Kind         string             `json:"kind"`
	Severity     string             `json:"severity"`
	Status       string             `json:"status"`
	ProjectID    *int64             `json:"project_id"`
	AssigneeID   *int64             `json:"assignee_id"`
	ReporterID   *int64             `json:"reporter_id"`
	Component    string             `json:"component"`
	ResolvedAt   pgtype.Timestamptz `json:"resolved_at"`
	CreatedAt    time.Time          `json:"created_at"`
	AssigneeName string             `json:"assignee_name"`
	ReporterName string             `json:"reporter_name"`
	ProjectName  string             `json:"project_name"`
}

func (q *Queries) ListIncidents(ctx context.Context) ([]ListIncidentsRow, error) {
	rows, err := q.db.Query(ctx, listIncidents)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListIncidentsRow{}
	for rows.Next() {
		var i ListIncidentsRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.Kind,
			&i.Severity,
			&i.Status,
			&i.ProjectID,
			&i.AssigneeID,
			&i.ReporterID,
			&i.Component,
			&i.ResolvedAt,
			&i.CreatedAt,
			&i.AssigneeName,
			&i.ReporterName,
			&i.ProjectName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setIncidentStatus = `-- name: SetIncidentStatus :one
UPDATE incidents
SET status = $1,
    resolved_at = $2
WHERE id = $3
RETURNING id, title, description, kind, severity, status, project_id, assignee_id, reporter_id, component, resolved_at, created_at
`

type SetIncidentStatusParams struct {
	Status     string             `json:"status"`
	ResolvedAt pgtype.Timestamptz `json:"resolved_at"`
	ID         int64              `json:"id"`
}

func (q *Queries) SetIncidentStatus(ctx context.Context, arg SetIncidentStatusParams) (Incident, error) {
	row := q.db.QueryRow(ctx, setIncidentStatus, arg.Status, arg.ResolvedAt, arg.ID)
	var i Incident
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Kind,
		&i.Severity,
		&i.Status,
		&i.ProjectID,
		&i.AssigneeID,
		&i.ReporterID,
		&i.Component,
		&i.ResolvedAt,
		&i.CreatedAt,
	)
	return i, err
}

const updateIncident = `-- name: UpdateIncident :one
UPDATE incidents
SET title = $1,
    description = $2,
    kind = $3,
    severity = $4,
    project_id = $5,
    assignee_id = $6,
    component = $7
WHERE id = $8
RETURNING id, title, description, kind, severity, status, project_id, assignee_id, reporter_id, component, resolved_at, created_at
`

type UpdateIncidentParams struct {
	Title       string `json:"title"`
	Description string `json:"description"`
	Kind        string `json:"kind"`
	Severity    string `json:"severity"`
	ProjectID   *int64 `json:"project_id"`
	AssigneeID  *int64 `json:"assignee_id"`
	Component   string `json:"component"`
	ID          int64  `json:"id"`
}

func (q *Queries) UpdateIncident(ctx context.Context, arg UpdateIncidentParams) (Incident, error) {
	row := q.db.QueryRow(ctx, updateIncident,
		arg.Title,
		arg.Description,
		arg.Kind,
		arg.Severity,
		arg.ProjectID,
		arg.AssigneeID,
		arg.Component,
		arg.ID,
	)
	var i Incident
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Kind,
		&i.Severity,
		&i.Status,
		&i.ProjectID,
		&i.AssigneeID,
		&i.ReporterID,
		&i.Component,
		&i.ResolvedAt,
		&i.CreatedAt,
	)
	return i, err
}
