// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: integrations.sql

package db

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAPIKey = `-- name: CreateAPIKey :one
INSERT INTO api_keys (user_id, name, token_hash, prefix)
VALUES ($1, $2, $3,
        $4)
RETURNING id, created_at
`

type CreateAPIKeyParams struct {
	UserID    int64  `json:"user_id"`
	Name      string `json:"name"`
	TokenHash string `json:"token_hash"`
	Prefix    string `json:"prefix"`
}

type CreateAPIKeyRow struct {
	ID        int64     `json:"id"`
	CreatedAt time.Time `json:"created_at"`
}

func (q *Queries) CreateAPIKey(ctx context.Context, arg CreateAPIKeyParams) (CreateAPIKeyRow, error) {
	row := q.db.QueryRow(ctx, createAPIKey,
		arg.UserID,
		arg.Name,
		arg.TokenHash,
		arg.Prefix,
	)
	var i CreateAPIKeyRow
	err := row.Scan(&i.ID, &i.CreatedAt)
	return i, err
}

const createWebhook = `-- name: CreateWebhook :one
INSERT INTO webhooks (url, secret, events, active, provider, created_by)
VALUES ($1, $2, $3, $4,
        $5, $6)
RETURNING id, url, secret, events, active, provider, created_by, created_at
`

type CreateWebhookParams struct {
	Url       string `json:"url"`
	Secret    string `json:"secret"`
	Events    string `json:"events"`
	Active    bool   `json:"active"`
	Provider  string `json:"provider"`
	CreatedBy *int64 `json:"created_by"`
}

func (q *Queries) CreateWebhook(ctx context.Context, arg CreateWebhookParams) (Webhook, error) {
	row := q.db.QueryRow(ctx, createWebhook,
		arg.Url,
		arg.Secret,
		arg.Events,
		arg.Active,
		arg.Provider,
		arg.CreatedBy,
	)
	var i Webhook
	err := row.Scan(
		&i.ID,
		&i.Url,
		&i.Secret,
		&i.Events,
		&i.Active,
		&i.Provider,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const deleteAPIKey = `-- name: DeleteAPIKey :exec
DELETE FROM api_keys WHERE id = $1 AND user_id = $2
`

type DeleteAPIKeyParams struct {
	ID     int64 `json:"id"`
	UserID int64 `json:"user_id"`
}

func (q *Queries) DeleteAPIKey(ctx context.Context, arg DeleteAPIKeyParams) error {
	_, err := q.db.Exec(ctx, deleteAPIKey, arg.ID, arg.UserID)
	return err
}

const deleteIntegration = `-- name: DeleteIntegration :exec
DELETE FROM integrations WHERE provider = $1
`

func (q *Queries) DeleteIntegration(ctx context.Context, provider string) error {
	_, err := q.db.Exec(ctx, deleteIntegration, provider)
	return err
}

const deleteWebhook = `-- name: DeleteWebhook :exec
DELETE FROM webhooks WHERE id = $1
`

func (q *Queries) DeleteWebhook(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteWebhook, id)
	return err
}

const getIntegration = `-- name: GetIntegration :one
SELECT provider, connected, config, updated_at FROM integrations
WHERE provider = $1
`

type GetIntegrationRow struct {
	Provider  string    `json:"provider"`
	Connected bool      `json:"connected"`
	Config    string    `json:"config"`
	UpdatedAt time.Time `json:"updated_at"`
}

func (q *Queries) GetIntegration(ctx context.Context, provider string) (GetIntegrationRow, error) {
	row := q.db.QueryRow(ctx, getIntegration, provider)
	var i GetIntegrationRow
	err := row.Scan(
		&i.Provider,
		&i.Connected,
		&i.Config,
		&i.UpdatedAt,
	)
	return i, err
}

const getWebhook = `-- name: GetWebhook :one
SELECT id, url, secret, events, active, provider, created_by, created_at FROM webhooks WHERE id = $1
`

func (q *Queries) GetWebhook(ctx context.Context, id int64) (Webhook, error) {
	row := q.db.QueryRow(ctx, getWebhook, id)
	var i Webhook
	err := row.Scan(
		&i.ID,
		&i.Url,
		&i.Secret,
		&i.Events,
		&i.Active,
		&i.Provider,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const listAPIKeys = `-- name: ListAPIKeys :many
SELECT id, name, prefix, last_used_at, created_at
FROM api_keys
WHERE user_id = $1
ORDER BY created_at DESC
`

type ListAPIKeysRow struct {
	ID         int64              `json:"id"`
	Name       string             `json:"name"`
	Prefix     string             `json:"prefix"`
	LastUsedAt pgtype.Timestamptz `json:"last_used_at"`
	CreatedAt  time.Time          `json:"created_at"`
}

func (q *Queries) ListAPIKeys(ctx context.Context, userID int64) ([]ListAPIKeysRow, error) {
	rows, err := q.db.Query(ctx, listAPIKeys, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAPIKeysRow{}
	for rows.Next() {
		var i ListAPIKeysRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Prefix,
			&i.LastUsedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActiveWebhooks = `-- name: ListActiveWebhooks :many
SELECT id, url, secret, events, active, provider, created_by, created_at FROM webhooks WHERE active = true
`

func (q *Queries) ListActiveWebhooks(ctx context.Context) ([]Webhook, error) {
	rows, err := q.db.Query(ctx, listActiveWebhooks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Webhook{}
	for rows.Next() {
		var i Webhook
		if err := rows.Scan(
			&i.ID,
			&i.Url,
			&i.Secret,
			&i.Events,
			&i.Active,
			&i.Provider,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listConnectedByProvider = `-- name: ListConnectedByProvider :many
SELECT provider, config FROM integrations
WHERE connected = true AND provider = ANY($1::text[])
`

type ListConnectedByProviderRow struct {
	Provider string `json:"provider"`
	Config   string `json:"config"`
}

func (q *Queries) ListConnectedByProvider(ctx context.Context, providers []string) ([]ListConnectedByProviderRow, error) {
	rows, err := q.db.Query(ctx, listConnectedByProvider, providers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListConnectedByProviderRow{}
	for rows.Next() {
		var i ListConnectedByProviderRow
		if err := rows.Scan(&i.Provider, &i.Config); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIntegrations = `-- name: ListIntegrations :many
SELECT provider, connected, config, updated_at FROM integrations
`

type ListIntegrationsRow struct {
	Provider  string    `json:"provider"`
	Connected bool      `json:"connected"`
	Config    string    `json:"config"`
	UpdatedAt time.Time `json:"updated_at"`
}

func (q *Queries) ListIntegrations(ctx context.Context) ([]ListIntegrationsRow, error) {
	rows, err := q.db.Query(ctx, listIntegrations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListIntegrationsRow{}
	for rows.Next() {
		var i ListIntegrationsRow
		if err := rows.Scan(
			&i.Provider,
			&i.Connected,
			&i.Config,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWebhooks = `-- name: ListWebhooks :many
SELECT id, url, secret, events, active, provider, created_by, created_at FROM webhooks ORDER BY created_at DESC
`

func (q *Queries) ListWebhooks(ctx context.Context) ([]Webhook, error) {
	rows, err := q.db.Query(ctx, listWebhooks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Webhook{}
	for rows.Next() {
		var i Webhook
		if err := rows.Scan(
			&i.ID,
			&i.Url,
			&i.Secret,
			&i.Events,
			&i.Active,
			&i.Provider,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lookupAPIKey = `-- name: LookupAPIKey :one
SELECT k.id, k.user_id, u.email, u.full_name, u.role
FROM api_keys k
JOIN users u ON u.id = k.user_id
WHERE k.token_hash = $1
`

type LookupAPIKeyRow struct {
	ID       int64  `json:"id"`
	UserID   int64  `json:"user_id"`
	Email    string `json:"email"`
	FullName string `json:"full_name"`
	Role     string `json:"role"`
}

func (q *Queries) LookupAPIKey(ctx context.Context, tokenHash string) (LookupAPIKeyRow, error) {
	row := q.db.QueryRow(ctx, lookupAPIKey, tokenHash)
	var i LookupAPIKeyRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Email,
		&i.FullName,
		&i.Role,
	)
	return i, err
}

const touchAPIKey = `-- name: TouchAPIKey :exec
UPDATE api_keys SET last_used_at = now() WHERE id = $1
`

func (q *Queries) TouchAPIKey(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, touchAPIKey, id)
	return err
}

const updateWebhook = `-- name: UpdateWebhook :exec
UPDATE webhooks
SET url = $1, events = $2, active = $3
WHERE id = $4
`

type UpdateWebhookParams struct {
	Url    string `json:"url"`
	Events string `json:"events"`
	Active bool   `json:"active"`
	ID     int64  `json:"id"`
}

func (q *Queries) UpdateWebhook(ctx context.Context, arg UpdateWebhookParams) error {
	_, err := q.db.Exec(ctx, updateWebhook,
		arg.Url,
		arg.Events,
		arg.Active,
		arg.ID,
	)
	return err
}

const upsertIntegration = `-- name: UpsertIntegration :exec
INSERT INTO integrations (provider, connected, config, updated_by, updated_at)
VALUES ($1, $2, $3,
        $4, now())
ON CONFLICT (provider) DO UPDATE
SET connected = $2, config = $3,
    updated_by = $4, updated_at = now()
`

type UpsertIntegrationParams struct {
	Provider  string `json:"provider"`
	Connected bool   `json:"connected"`
	Config    string `json:"config"`
	UpdatedBy *int64 `json:"updated_by"`
}

func (q *Queries) UpsertIntegration(ctx context.Context, arg UpsertIntegrationParams) error {
	_, err := q.db.Exec(ctx, upsertIntegration,
		arg.Provider,
		arg.Connected,
		arg.Config,
		arg.UpdatedBy,
	)
	return err
}
