// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: invoices.sql

package db

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const addInvoiceLine = `-- name: AddInvoiceLine :one
INSERT INTO invoice_lines (invoice_id, description, quantity_minutes,
                           rate_cents, amount_cents, sort)
VALUES ($1, $2,
        $3, $4,
        $5, $6)
RETURNING id, invoice_id, description, quantity_minutes, rate_cents, amount_cents, sort
`

type AddInvoiceLineParams struct {
	InvoiceID       int64  `json:"invoice_id"`
	Description     string `json:"description"`
	QuantityMinutes int32  `json:"quantity_minutes"`
	RateCents       int64  `json:"rate_cents"`
	AmountCents     int64  `json:"amount_cents"`
	Sort            int32  `json:"sort"`
}

func (q *Queries) AddInvoiceLine(ctx context.Context, arg AddInvoiceLineParams) (InvoiceLine, error) {
	row := q.db.QueryRow(ctx, addInvoiceLine,
		arg.InvoiceID,
		arg.Description,
		arg.QuantityMinutes,
		arg.RateCents,
		arg.AmountCents,
		arg.Sort,
	)
	var i InvoiceLine
	err := row.Scan(
		&i.ID,
		&i.InvoiceID,
		&i.Description,
		&i.QuantityMinutes,
		&i.RateCents,
		&i.AmountCents,
		&i.Sort,
	)
	return i, err
}

const createInvoice = `-- name: CreateInvoice :one
INSERT INTO invoices (number, project_id, client_name, client_email,
                      issue_date, due_date, notes)
VALUES ('INV-' || lpad(nextval('invoice_number_seq')::text, 4, '0'),
        $1, $2, $3,
        $4, $5, $6)
RETURNING id, number, project_id, client_name, client_email, status, issue_date, due_date, notes, created_at
`

type CreateInvoiceParams struct {
	ProjectID   *int64      `json:"project_id"`
	ClientName  string      `json:"client_name"`
	ClientEmail string      `json:"client_email"`
	IssueDate   pgtype.Date `json:"issue_date"`
	DueDate     pgtype.Date `json:"due_date"`
	Notes       string      `json:"notes"`
}

func (q *Queries) CreateInvoice(ctx context.Context, arg CreateInvoiceParams) (Invoice, error) {
	row := q.db.QueryRow(ctx, createInvoice,
		arg.ProjectID,
		arg.ClientName,
		arg.ClientEmail,
		arg.IssueDate,
		arg.DueDate,
		arg.Notes,
	)
	var i Invoice
	err := row.Scan(
		&i.ID,
		&i.Number,
		&i.ProjectID,
		&i.ClientName,
		&i.ClientEmail,
		&i.Status,
		&i.IssueDate,
		&i.DueDate,
		&i.Notes,
		&i.CreatedAt,
	)
	return i, err
}

const deleteInvoice = `-- name: DeleteInvoice :exec
DELETE FROM invoices WHERE id = $1
`

func (q *Queries) DeleteInvoice(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteInvoice, id)
	return err
}

const deleteInvoiceLine = `-- name: DeleteInvoiceLine :exec
DELETE FROM invoice_lines WHERE id = $1
`

func (q *Queries) DeleteInvoiceLine(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteInvoiceLine, id)
	return err
}

const getInvoice = `-- name: GetInvoice :one
SELECT i.id, i.number, i.project_id, i.client_name, i.client_email, i.status, i.issue_date, i.due_date, i.notes, i.created_at, COALESCE(p.name, '')::text AS project_name,
       COALESCE((
           SELECT SUM(l.amount_cents) FROM invoice_lines l
           WHERE l.invoice_id = i.id
       ), 0)::bigint AS total_cents
FROM invoices i
LEFT JOIN projects p ON p.id = i.project_id
WHERE i.id = $1
`

type GetInvoiceRow struct {
	ID          int64       `json:"id"`
	Number      string      `json:"number"`
	ProjectID   *int64      `json:"project_id"`
	ClientName  string      `json:"client_name"`
	ClientEmail string      `json:"client_email"`
	Status      string      `json:"status"`
	IssueDate   pgtype.Date `json:"issue_date"`
	DueDate     pgtype.Date `json:"due_date"`
	Notes       string      `json:"notes"`
	CreatedAt   time.Time   `json:"created_at"`
	ProjectName string      `json:"project_name"`
	TotalCents  int64       `json:"total_cents"`
}

func (q *Queries) GetInvoice(ctx context.Context, id int64) (GetInvoiceRow, error) {
	row := q.db.QueryRow(ctx, getInvoice, id)
	var i GetInvoiceRow
	err := row.Scan(
		&i.ID,
		&i.Number,
		&i.ProjectID,
		&i.ClientName,
		&i.ClientEmail,
		&i.Status,
		&i.IssueDate,
		&i.DueDate,
		&i.Notes,
		&i.CreatedAt,
		&i.ProjectName,
		&i.TotalCents,
	)
	return i, err
}

const getProjectRate = `-- name: GetProjectRate :one
SELECT COALESCE((
    SELECT hourly_rate_cents FROM project_budgets WHERE project_id = $1
), 0)::bigint
`

func (q *Queries) GetProjectRate(ctx context.Context, projectID int64) (int64, error) {
	row := q.db.QueryRow(ctx, getProjectRate, projectID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const listInvoiceLines = `-- name: ListInvoiceLines :many
SELECT id, invoice_id, description, quantity_minutes, rate_cents, amount_cents, sort FROM invoice_lines WHERE invoice_id = $1 ORDER BY sort, id
`

func (q *Queries) ListInvoiceLines(ctx context.Context, invoiceID int64) ([]InvoiceLine, error) {
	rows, err := q.db.Query(ctx, listInvoiceLines, invoiceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []InvoiceLine{}
	for rows.Next() {
		var i InvoiceLine
		if err := rows.Scan(
			&i.ID,
			&i.InvoiceID,
			&i.Description,
			&i.QuantityMinutes,
			&i.RateCents,
			&i.AmountCents,
			&i.Sort,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInvoices = `-- name: ListInvoices :many
SELECT i.id, i.number, i.project_id, i.client_name, i.client_email, i.status, i.issue_date, i.due_date, i.notes, i.created_at, COALESCE(p.name, '')::text AS project_name,
       COALESCE((
           SELECT SUM(l.amount_cents) FROM invoice_lines l
           WHERE l.invoice_id = i.id
       ), 0)::bigint AS total_cents,
       COALESCE((
           SELECT COUNT(*) FROM invoice_lines l WHERE l.invoice_id = i.id
       ), 0)::bigint AS line_count
FROM invoices i
LEFT JOIN projects p ON p.id = i.project_id
ORDER BY i.id DESC
`

type ListInvoicesRow struct {
	ID          int64       `json:"id"`
	Number      string      `json:"number"`
	ProjectID   *int64      `json:"project_id"`
	ClientName  string      `json:"client_name"`
	ClientEmail string      `json:"client_email"`
	Status      string      `json:"status"`
	IssueDate   pgtype.Date `json:"issue_date"`
	DueDate     pgtype.Date `json:"due_date"`
	Notes       string      `json:"notes"`
	CreatedAt   time.Time   `json:"created_at"`
	ProjectName string      `json:"project_name"`
	TotalCents  int64       `json:"total_cents"`
	LineCount   int64       `json:"line_count"`
}

func (q *Queries) ListInvoices(ctx context.Context) ([]ListInvoicesRow, error) {
	rows, err := q.db.Query(ctx, listInvoices)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListInvoicesRow{}
	for rows.Next() {
		var i ListInvoicesRow
		if err := rows.Scan(
			&i.ID,
			&i.Number,
			&i.ProjectID,
			&i.ClientName,
			&i.ClientEmail,
			&i.Status,
			&i.IssueDate,
			&i.DueDate,
			&i.Notes,
			&i.CreatedAt,
			&i.ProjectName,
			&i.TotalCents,
			&i.LineCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markProjectTimeInvoiced = `-- name: MarkProjectTimeInvoiced :exec
UPDATE time_entries te
SET invoice_id = $1
FROM tasks tk
WHERE te.task_id = tk.id
  AND tk.project_id = $2
  AND te.billable = true
  AND te.invoice_id IS NULL
`

type MarkProjectTimeInvoicedParams struct {
	InvoiceID *int64 `json:"invoice_id"`
	ProjectID *int64 `json:"project_id"`
}

func (q *Queries) MarkProjectTimeInvoiced(ctx context.Context, arg MarkProjectTimeInvoicedParams) error {
	_, err := q.db.Exec(ctx, markProjectTimeInvoiced, arg.InvoiceID, arg.ProjectID)
	return err
}

const releaseInvoiceTime = `-- name: ReleaseInvoiceTime :exec
UPDATE time_entries SET invoice_id = NULL WHERE invoice_id = $1
`

func (q *Queries) ReleaseInvoiceTime(ctx context.Context, invoiceID *int64) error {
	_, err := q.db.Exec(ctx, releaseInvoiceTime, invoiceID)
	return err
}

const setInvoiceStatus = `-- name: SetInvoiceStatus :one
UPDATE invoices SET status = $1 WHERE id = $2
RETURNING id, number, project_id, client_name, client_email, status, issue_date, due_date, notes, created_at
`

type SetInvoiceStatusParams struct {
	Status string `json:"status"`
	ID     int64  `json:"id"`
}

func (q *Queries) SetInvoiceStatus(ctx context.Context, arg SetInvoiceStatusParams) (Invoice, error) {
	row := q.db.QueryRow(ctx, setInvoiceStatus, arg.Status, arg.ID)
	var i Invoice
	err := row.Scan(
		&i.ID,
		&i.Number,
		&i.ProjectID,
		&i.ClientName,
		&i.ClientEmail,
		&i.Status,
		&i.IssueDate,
		&i.DueDate,
		&i.Notes,
		&i.CreatedAt,
	)
	return i, err
}

const unbilledTimeByUser = `-- name: UnbilledTimeByUser :many
SELECT u.id AS user_id, COALESCE(u.full_name, '')::text AS user_name,
       SUM(te.minutes)::bigint AS minutes
FROM time_entries te
JOIN tasks tk ON tk.id = te.task_id
LEFT JOIN users u ON u.id = te.user_id
WHERE tk.project_id = $1 AND te.billable = true AND te.invoice_id IS NULL
GROUP BY u.id, u.full_name
HAVING SUM(te.minutes) > 0
ORDER BY u.full_name
`

type UnbilledTimeByUserRow struct {
	UserID   *int64 `json:"user_id"`
	UserName string `json:"user_name"`
	Minutes  int64  `json:"minutes"`
}

func (q *Queries) UnbilledTimeByUser(ctx context.Context, projectID *int64) ([]UnbilledTimeByUserRow, error) {
	rows, err := q.db.Query(ctx, unbilledTimeByUser, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UnbilledTimeByUserRow{}
	for rows.Next() {
		var i UnbilledTimeByUserRow
		if err := rows.Scan(&i.UserID, &i.UserName, &i.Minutes); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
