// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: leave.sql

package db

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const cancelLeave = `-- name: CancelLeave :exec
DELETE FROM leave_requests
WHERE id = $1 AND user_id = $2
  AND status = 'pending'
`

type CancelLeaveParams struct {
	ID     int64 `json:"id"`
	UserID int64 `json:"user_id"`
}

func (q *Queries) CancelLeave(ctx context.Context, arg CancelLeaveParams) error {
	_, err := q.db.Exec(ctx, cancelLeave, arg.ID, arg.UserID)
	return err
}

const createLeave = `-- name: CreateLeave :one
INSERT INTO leave_requests (user_id, type, start_date, end_date, note)
VALUES ($1, $2, $3,
        $4, $5)
RETURNING id, user_id, type, start_date, end_date, status, note, approver_id, decided_at, created_at
`

type CreateLeaveParams struct {
	UserID    int64     `json:"user_id"`
	Type      string    `json:"type"`
	StartDate time.Time `json:"start_date"`
	EndDate   time.Time `json:"end_date"`
	Note      string    `json:"note"`
}

func (q *Queries) CreateLeave(ctx context.Context, arg CreateLeaveParams) (LeaveRequest, error) {
	row := q.db.QueryRow(ctx, createLeave,
		arg.UserID,
		arg.Type,
		arg.StartDate,
		arg.EndDate,
		arg.Note,
	)
	var i LeaveRequest
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Type,
		&i.StartDate,
		&i.EndDate,
		&i.Status,
		&i.Note,
		&i.ApproverID,
		&i.DecidedAt,
		&i.CreatedAt,
	)
	return i, err
}

const decideLeave = `-- name: DecideLeave :one
UPDATE leave_requests
SET status = $1,
    approver_id = $2,
    decided_at = now()
WHERE id = $3
RETURNING id, user_id, type, start_date, end_date, status, note, approver_id, decided_at, created_at
`

type DecideLeaveParams struct {
	Status     string `json:"status"`
	ApproverID *int64 `json:"approver_id"`
	ID         int64  `json:"id"`
}

func (q *Queries) DecideLeave(ctx context.Context, arg DecideLeaveParams) (LeaveRequest, error) {
	row := q.db.QueryRow(ctx, decideLeave, arg.Status, arg.ApproverID, arg.ID)
	var i LeaveRequest
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Type,
		&i.StartDate,
		&i.EndDate,
		&i.Status,
		&i.Note,
		&i.ApproverID,
		&i.DecidedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listLeaveInRange = `-- name: ListLeaveInRange :many
SELECT l.id, l.user_id, l.type, l.start_date, l.end_date, l.status, l.note, l.approver_id, l.decided_at, l.created_at, u.full_name AS user_name, u.avatar
FROM leave_requests l
JOIN users u ON u.id = l.user_id
WHERE l.status = 'approved'
  AND l.start_date < $1
  AND l.end_date >= $2
ORDER BY l.start_date
`

type ListLeaveInRangeParams struct {
	RangeEnd   time.Time `json:"range_end"`
	RangeStart time.Time `json:"range_start"`
}

type ListLeaveInRangeRow struct {
	ID         int64              `json:"id"`
	UserID     int64              `json:"user_id"`
	Type       string             `json:"type"`
	StartDate  time.Time          `json:"start_date"`
	EndDate    time.Time          `json:"end_date"`
	Status     string             `json:"status"`
	Note       string             `json:"note"`
	ApproverID *int64             `json:"approver_id"`
	DecidedAt  pgtype.Timestamptz `json:"decided_at"`
	CreatedAt  time.Time          `json:"created_at"`
	UserName   string             `json:"user_name"`
	Avatar     string             `json:"avatar"`
}

func (q *Queries) ListLeaveInRange(ctx context.Context, arg ListLeaveInRangeParams) ([]ListLeaveInRangeRow, error) {
	rows, err := q.db.Query(ctx, listLeaveInRange, arg.RangeEnd, arg.RangeStart)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListLeaveInRangeRow{}
	for rows.Next() {
		var i ListLeaveInRangeRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Type,
			&i.StartDate,
			&i.EndDate,
			&i.Status,
			&i.Note,
			&i.ApproverID,
			&i.DecidedAt,
			&i.CreatedAt,
			&i.UserName,
			&i.Avatar,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMyLeave = `-- name: ListMyLeave :many
SELECT l.id, l.user_id, l.type, l.start_date, l.end_date, l.status, l.note, l.approver_id, l.decided_at, l.created_at, COALESCE(a.full_name, '')::text AS approver_name
FROM leave_requests l
LEFT JOIN users a ON a.id = l.approver_id
WHERE l.user_id = $1
ORDER BY l.start_date DESC
`

type ListMyLeaveRow struct {
	ID           int64              `json:"id"`
	UserID       int64              `json:"user_id"`
	Type         string             `json:"type"`
	StartDate    time.Time          `json:"start_date"`
	EndDate      time.Time          `json:"end_date"`
	Status       string             `json:"status"`
	Note         string             `json:"note"`
	ApproverID   *int64             `json:"approver_id"`
	DecidedAt    pgtype.Timestamptz `json:"decided_at"`
	CreatedAt    time.Time          `json:"created_at"`
	ApproverName string             `json:"approver_name"`
}

func (q *Queries) ListMyLeave(ctx context.Context, userID int64) ([]ListMyLeaveRow, error) {
	rows, err := q.db.Query(ctx, listMyLeave, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMyLeaveRow{}
	for rows.Next() {
		var i ListMyLeaveRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Type,
			&i.StartDate,
			&i.EndDate,
			&i.Status,
			&i.Note,
			&i.ApproverID,
			&i.DecidedAt,
			&i.CreatedAt,
			&i.ApproverName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingLeave = `-- name: ListPendingLeave :many
SELECT l.id, l.user_id, l.type, l.start_date, l.end_date, l.status, l.note, l.approver_id, l.decided_at, l.created_at, u.full_name AS user_name, u.avatar
FROM leave_requests l
JOIN users u ON u.id = l.user_id
WHERE l.status = 'pending'
ORDER BY l.start_date
`

type ListPendingLeaveRow struct {
	ID         int64              `json:"id"`
	UserID     int64              `json:"user_id"`
	Type       string             `json:"type"`
	StartDate  time.Time          `json:"start_date"`
	EndDate    time.Time          `json:"end_date"`
	Status     string             `json:"status"`
	Note       string             `json:"note"`
	ApproverID *int64             `json:"approver_id"`
	DecidedAt  pgtype.Timestamptz `json:"decided_at"`
	CreatedAt  time.Time          `json:"created_at"`
	UserName   string             `json:"user_name"`
	Avatar     string             `json:"avatar"`
}

func (q *Queries) ListPendingLeave(ctx context.Context) ([]ListPendingLeaveRow, error) {
	rows, err := q.db.Query(ctx, listPendingLeave)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPendingLeaveRow{}
	for rows.Next() {
		var i ListPendingLeaveRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Type,
			&i.StartDate,
			&i.EndDate,
			&i.Status,
			&i.Note,
			&i.ApproverID,
			&i.DecidedAt,
			&i.CreatedAt,
			&i.UserName,
			&i.Avatar,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const usedLeaveDays = `-- name: UsedLeaveDays :one
SELECT COALESCE(SUM((DATE(end_date) - DATE(start_date)) + 1), 0)::int
FROM leave_requests
WHERE user_id = $1
  AND status = 'approved'
  AND type = 'vacation'
  AND start_date >= $2
  AND start_date < $3
`

type UsedLeaveDaysParams struct {
	UserID    int64     `json:"user_id"`
	YearStart time.Time `json:"year_start"`
	YearEnd   time.Time `json:"year_end"`
}

func (q *Queries) UsedLeaveDays(ctx context.Context, arg UsedLeaveDaysParams) (int32, error) {
	row := q.db.QueryRow(ctx, usedLeaveDays, arg.UserID, arg.YearStart, arg.YearEnd)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}
