// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: metrics.sql

package db

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const listCompletedTaskMetrics = `-- name: ListCompletedTaskMetrics :many
SELECT id, title, created_at, start_date, completed_at
FROM tasks
WHERE done = true
  AND completed_at IS NOT NULL
  AND parent_id IS NULL
  AND completed_at >= $1
ORDER BY completed_at
`

type ListCompletedTaskMetricsRow struct {
	ID          int64              `json:"id"`
	Title       string             `json:"title"`
	CreatedAt   time.Time          `json:"created_at"`
	StartDate   pgtype.Timestamptz `json:"start_date"`
	CompletedAt pgtype.Timestamptz `json:"completed_at"`
}

func (q *Queries) ListCompletedTaskMetrics(ctx context.Context, since pgtype.Timestamptz) ([]ListCompletedTaskMetricsRow, error) {
	rows, err := q.db.Query(ctx, listCompletedTaskMetrics, since)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCompletedTaskMetricsRow{}
	for rows.Next() {
		var i ListCompletedTaskMetricsRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.CreatedAt,
			&i.StartDate,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
