// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: milestones.sql

package db

import (
	"context"
	"time"
)

const createMilestone = `-- name: CreateMilestone :one
INSERT INTO milestones (project_id, name, due_date)
VALUES ($1, $2, $3)
RETURNING id, project_id, name, due_date, done, created_at
`

type CreateMilestoneParams struct {
	ProjectID *int64    `json:"project_id"`
	Name      string    `json:"name"`
	DueDate   time.Time `json:"due_date"`
}

func (q *Queries) CreateMilestone(ctx context.Context, arg CreateMilestoneParams) (Milestone, error) {
	row := q.db.QueryRow(ctx, createMilestone, arg.ProjectID, arg.Name, arg.DueDate)
	var i Milestone
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.DueDate,
		&i.Done,
		&i.CreatedAt,
	)
	return i, err
}

const deleteMilestone = `-- name: DeleteMilestone :exec
DELETE FROM milestones
WHERE id = $1
`

func (q *Queries) DeleteMilestone(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteMilestone, id)
	return err
}

const listMilestones = `-- name: ListMilestones :many
SELECT id, project_id, name, due_date, done, created_at FROM milestones
ORDER BY due_date ASC
`

func (q *Queries) ListMilestones(ctx context.Context) ([]Milestone, error) {
	rows, err := q.db.Query(ctx, listMilestones)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Milestone{}
	for rows.Next() {
		var i Milestone
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Name,
			&i.DueDate,
			&i.Done,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMilestone = `-- name: UpdateMilestone :one
UPDATE milestones
SET name     = $2,
    due_date = $3,
    done     = $4
WHERE id = $1
RETURNING id, project_id, name, due_date, done, created_at
`

type UpdateMilestoneParams struct {
	ID      int64     `json:"id"`
	Name    string    `json:"name"`
	DueDate time.Time `json:"due_date"`
	Done    bool      `json:"done"`
}

func (q *Queries) UpdateMilestone(ctx context.Context, arg UpdateMilestoneParams) (Milestone, error) {
	row := q.db.QueryRow(ctx, updateMilestone,
		arg.ID,
		arg.Name,
		arg.DueDate,
		arg.Done,
	)
	var i Milestone
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.DueDate,
		&i.Done,
		&i.CreatedAt,
	)
	return i, err
}
