// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: muhurats.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createMuhurat = `-- name: CreateMuhurat :one
INSERT INTO muhurats (muhurat_date, kind, start_time, end_time, note_en,
                      note_ne, source)
VALUES ($1, $2, $3,
        $4, $5, $6,
        $7)
RETURNING id, muhurat_date, kind, start_time, end_time, note_en, note_ne, source, created_at
`

type CreateMuhuratParams struct {
	MuhuratDate pgtype.Date `json:"muhurat_date"`
	Kind        string      `json:"kind"`
	StartTime   pgtype.Time `json:"start_time"`
	EndTime     pgtype.Time `json:"end_time"`
	NoteEn      string      `json:"note_en"`
	NoteNe      string      `json:"note_ne"`
	Source      string      `json:"source"`
}

func (q *Queries) CreateMuhurat(ctx context.Context, arg CreateMuhuratParams) (Muhurat, error) {
	row := q.db.QueryRow(ctx, createMuhurat,
		arg.MuhuratDate,
		arg.Kind,
		arg.StartTime,
		arg.EndTime,
		arg.NoteEn,
		arg.NoteNe,
		arg.Source,
	)
	var i Muhurat
	err := row.Scan(
		&i.ID,
		&i.MuhuratDate,
		&i.Kind,
		&i.StartTime,
		&i.EndTime,
		&i.NoteEn,
		&i.NoteNe,
		&i.Source,
		&i.CreatedAt,
	)
	return i, err
}

const deleteMuhurat = `-- name: DeleteMuhurat :exec
DELETE FROM muhurats WHERE id = $1
`

func (q *Queries) DeleteMuhurat(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteMuhurat, id)
	return err
}

const listMuhurats = `-- name: ListMuhurats :many
SELECT id, muhurat_date, kind, start_time, end_time, note_en, note_ne, source, created_at FROM muhurats
WHERE muhurat_date >= $1
  AND muhurat_date <= $2
ORDER BY muhurat_date, start_time NULLS FIRST, id
`

type ListMuhuratsParams struct {
	FromDate pgtype.Date `json:"from_date"`
	ToDate   pgtype.Date `json:"to_date"`
}

func (q *Queries) ListMuhurats(ctx context.Context, arg ListMuhuratsParams) ([]Muhurat, error) {
	rows, err := q.db.Query(ctx, listMuhurats, arg.FromDate, arg.ToDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Muhurat{}
	for rows.Next() {
		var i Muhurat
		if err := rows.Scan(
			&i.ID,
			&i.MuhuratDate,
			&i.Kind,
			&i.StartTime,
			&i.EndTime,
			&i.NoteEn,
			&i.NoteNe,
			&i.Source,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
