// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: notification_prefs.sql

package db

import (
	"context"
)

const setUserNotificationPrefs = `-- name: SetUserNotificationPrefs :exec
UPDATE users SET notification_prefs = $1 WHERE id = $2
`

type SetUserNotificationPrefsParams struct {
	Prefs string `json:"prefs"`
	ID    int64  `json:"id"`
}

func (q *Queries) SetUserNotificationPrefs(ctx context.Context, arg SetUserNotificationPrefsParams) error {
	_, err := q.db.Exec(ctx, setUserNotificationPrefs, arg.Prefs, arg.ID)
	return err
}
