// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: notifications.sql

package db

import (
	"context"
)

const countUnreadNotifications = `-- name: CountUnreadNotifications :one
SELECT COUNT(*) FROM notifications
WHERE read = FALSE
`

func (q *Queries) CountUnreadNotifications(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countUnreadNotifications)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createNotification = `-- name: CreateNotification :one
INSERT INTO notifications (type, title, body)
VALUES ($1, $2, $3)
RETURNING id, type, title, body, read, created_at
`

type CreateNotificationParams struct {
	Type  string `json:"type"`
	Title string `json:"title"`
	Body  string `json:"body"`
}

func (q *Queries) CreateNotification(ctx context.Context, arg CreateNotificationParams) (Notification, error) {
	row := q.db.QueryRow(ctx, createNotification, arg.Type, arg.Title, arg.Body)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Title,
		&i.Body,
		&i.Read,
		&i.CreatedAt,
	)
	return i, err
}

const listNotifications = `-- name: ListNotifications :many
SELECT id, type, title, body, read, created_at FROM notifications
ORDER BY created_at DESC
LIMIT 50
`

func (q *Queries) ListNotifications(ctx context.Context) ([]Notification, error) {
	rows, err := q.db.Query(ctx, listNotifications)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Notification{}
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.Title,
			&i.Body,
			&i.Read,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAllNotificationsRead = `-- name: MarkAllNotificationsRead :exec
UPDATE notifications
SET read = TRUE
WHERE read = FALSE
`

func (q *Queries) MarkAllNotificationsRead(ctx context.Context) error {
	_, err := q.db.Exec(ctx, markAllNotificationsRead)
	return err
}

const markNotificationRead = `-- name: MarkNotificationRead :exec
UPDATE notifications
SET read = TRUE
WHERE id = $1
`

func (q *Queries) MarkNotificationRead(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, markNotificationRead, id)
	return err
}
