// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: notifications.sql

package db

import (
	"context"
)

const countUnreadNotifications = `-- name: CountUnreadNotifications :one
SELECT COUNT(*) FROM notifications
WHERE user_id = $1 AND read = FALSE
`

func (q *Queries) CountUnreadNotifications(ctx context.Context, userID *int64) (int64, error) {
	row := q.db.QueryRow(ctx, countUnreadNotifications, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createNotification = `-- name: CreateNotification :one
INSERT INTO notifications (user_id, type, title, body, link)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, type, title, body, read, created_at, user_id, link
`

type CreateNotificationParams struct {
	UserID *int64 `json:"user_id"`
	Type   string `json:"type"`
	Title  string `json:"title"`
	Body   string `json:"body"`
	Link   string `json:"link"`
}

func (q *Queries) CreateNotification(ctx context.Context, arg CreateNotificationParams) (Notification, error) {
	row := q.db.QueryRow(ctx, createNotification,
		arg.UserID,
		arg.Type,
		arg.Title,
		arg.Body,
		arg.Link,
	)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Title,
		&i.Body,
		&i.Read,
		&i.CreatedAt,
		&i.UserID,
		&i.Link,
	)
	return i, err
}

const listNotifications = `-- name: ListNotifications :many
SELECT id, type, title, body, read, created_at, user_id, link FROM notifications
WHERE user_id = $1
ORDER BY created_at DESC
LIMIT 50
`

func (q *Queries) ListNotifications(ctx context.Context, userID *int64) ([]Notification, error) {
	rows, err := q.db.Query(ctx, listNotifications, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Notification{}
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.Title,
			&i.Body,
			&i.Read,
			&i.CreatedAt,
			&i.UserID,
			&i.Link,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAllNotificationsRead = `-- name: MarkAllNotificationsRead :exec
UPDATE notifications
SET read = TRUE
WHERE user_id = $1 AND read = FALSE
`

func (q *Queries) MarkAllNotificationsRead(ctx context.Context, userID *int64) error {
	_, err := q.db.Exec(ctx, markAllNotificationsRead, userID)
	return err
}

const markNotificationRead = `-- name: MarkNotificationRead :exec
UPDATE notifications
SET read = TRUE
WHERE id = $1 AND user_id = $2
`

type MarkNotificationReadParams struct {
	ID     int64  `json:"id"`
	UserID *int64 `json:"user_id"`
}

func (q *Queries) MarkNotificationRead(ctx context.Context, arg MarkNotificationReadParams) error {
	_, err := q.db.Exec(ctx, markNotificationRead, arg.ID, arg.UserID)
	return err
}
