// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: objectives.sql

package db

import (
	"context"
	"time"
)

const createKeyResult = `-- name: CreateKeyResult :one
INSERT INTO key_results (objective_id, title, start_value, current_value,
                         target_value, unit, position)
VALUES ($1, $2, $3,
        $4, $5, $6,
        $7)
RETURNING id
`

type CreateKeyResultParams struct {
	ObjectiveID  int64   `json:"objective_id"`
	Title        string  `json:"title"`
	StartValue   float64 `json:"start_value"`
	CurrentValue float64 `json:"current_value"`
	TargetValue  float64 `json:"target_value"`
	Unit         string  `json:"unit"`
	Position     int32   `json:"position"`
}

func (q *Queries) CreateKeyResult(ctx context.Context, arg CreateKeyResultParams) (int64, error) {
	row := q.db.QueryRow(ctx, createKeyResult,
		arg.ObjectiveID,
		arg.Title,
		arg.StartValue,
		arg.CurrentValue,
		arg.TargetValue,
		arg.Unit,
		arg.Position,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const createObjective = `-- name: CreateObjective :one
INSERT INTO objectives (title, description, owner_id, parent_id, period,
                        status, created_by)
VALUES ($1, $2, $3,
        $4, $5, $6,
        $7)
RETURNING id
`

type CreateObjectiveParams struct {
	Title       string `json:"title"`
	Description string `json:"description"`
	OwnerID     *int64 `json:"owner_id"`
	ParentID    *int64 `json:"parent_id"`
	Period      string `json:"period"`
	Status      string `json:"status"`
	CreatedBy   *int64 `json:"created_by"`
}

func (q *Queries) CreateObjective(ctx context.Context, arg CreateObjectiveParams) (int64, error) {
	row := q.db.QueryRow(ctx, createObjective,
		arg.Title,
		arg.Description,
		arg.OwnerID,
		arg.ParentID,
		arg.Period,
		arg.Status,
		arg.CreatedBy,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const deleteKeyResult = `-- name: DeleteKeyResult :exec
DELETE FROM key_results WHERE id = $1
`

func (q *Queries) DeleteKeyResult(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteKeyResult, id)
	return err
}

const deleteObjective = `-- name: DeleteObjective :exec
DELETE FROM objectives WHERE id = $1
`

func (q *Queries) DeleteObjective(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteObjective, id)
	return err
}

const getKeyResultObjective = `-- name: GetKeyResultObjective :one
SELECT objective_id FROM key_results WHERE id = $1
`

func (q *Queries) GetKeyResultObjective(ctx context.Context, id int64) (int64, error) {
	row := q.db.QueryRow(ctx, getKeyResultObjective, id)
	var objective_id int64
	err := row.Scan(&objective_id)
	return objective_id, err
}

const getObjective = `-- name: GetObjective :one
SELECT o.id, o.title, o.description, o.owner_id, o.parent_id, o.period,
       o.status, o.created_by, o.created_at, o.updated_at,
       COALESCE(ow.full_name, '')::text AS owner_name
FROM objectives o
LEFT JOIN users ow ON ow.id = o.owner_id
WHERE o.id = $1
`

type GetObjectiveRow struct {
	ID          int64     `json:"id"`
	Title       string    `json:"title"`
	Description string    `json:"description"`
	OwnerID     *int64    `json:"owner_id"`
	ParentID    *int64    `json:"parent_id"`
	Period      string    `json:"period"`
	Status      string    `json:"status"`
	CreatedBy   *int64    `json:"created_by"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
	OwnerName   string    `json:"owner_name"`
}

func (q *Queries) GetObjective(ctx context.Context, id int64) (GetObjectiveRow, error) {
	row := q.db.QueryRow(ctx, getObjective, id)
	var i GetObjectiveRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.OwnerID,
		&i.ParentID,
		&i.Period,
		&i.Status,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OwnerName,
	)
	return i, err
}

const listAllKeyResults = `-- name: ListAllKeyResults :many
SELECT id, objective_id, title, start_value, current_value, target_value,
       unit, position, created_at
FROM key_results
ORDER BY objective_id, position, id
`

func (q *Queries) ListAllKeyResults(ctx context.Context) ([]KeyResult, error) {
	rows, err := q.db.Query(ctx, listAllKeyResults)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []KeyResult{}
	for rows.Next() {
		var i KeyResult
		if err := rows.Scan(
			&i.ID,
			&i.ObjectiveID,
			&i.Title,
			&i.StartValue,
			&i.CurrentValue,
			&i.TargetValue,
			&i.Unit,
			&i.Position,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listObjectives = `-- name: ListObjectives :many
SELECT o.id, o.title, o.description, o.owner_id, o.parent_id, o.period,
       o.status, o.created_by, o.created_at, o.updated_at,
       COALESCE(ow.full_name, '')::text AS owner_name
FROM objectives o
LEFT JOIN users ow ON ow.id = o.owner_id
ORDER BY o.created_at ASC
`

type ListObjectivesRow struct {
	ID          int64     `json:"id"`
	Title       string    `json:"title"`
	Description string    `json:"description"`
	OwnerID     *int64    `json:"owner_id"`
	ParentID    *int64    `json:"parent_id"`
	Period      string    `json:"period"`
	Status      string    `json:"status"`
	CreatedBy   *int64    `json:"created_by"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
	OwnerName   string    `json:"owner_name"`
}

func (q *Queries) ListObjectives(ctx context.Context) ([]ListObjectivesRow, error) {
	rows, err := q.db.Query(ctx, listObjectives)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListObjectivesRow{}
	for rows.Next() {
		var i ListObjectivesRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.OwnerID,
			&i.ParentID,
			&i.Period,
			&i.Status,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.OwnerName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateKeyResult = `-- name: UpdateKeyResult :exec
UPDATE key_results
SET title = $1, start_value = $2,
    current_value = $3,
    target_value = $4, unit = $5
WHERE id = $6
`

type UpdateKeyResultParams struct {
	Title        string  `json:"title"`
	StartValue   float64 `json:"start_value"`
	CurrentValue float64 `json:"current_value"`
	TargetValue  float64 `json:"target_value"`
	Unit         string  `json:"unit"`
	ID           int64   `json:"id"`
}

func (q *Queries) UpdateKeyResult(ctx context.Context, arg UpdateKeyResultParams) error {
	_, err := q.db.Exec(ctx, updateKeyResult,
		arg.Title,
		arg.StartValue,
		arg.CurrentValue,
		arg.TargetValue,
		arg.Unit,
		arg.ID,
	)
	return err
}

const updateObjective = `-- name: UpdateObjective :exec
UPDATE objectives
SET title = $1, description = $2,
    owner_id = $3, parent_id = $4,
    period = $5, status = $6, updated_at = now()
WHERE id = $7
`

type UpdateObjectiveParams struct {
	Title       string `json:"title"`
	Description string `json:"description"`
	OwnerID     *int64 `json:"owner_id"`
	ParentID    *int64 `json:"parent_id"`
	Period      string `json:"period"`
	Status      string `json:"status"`
	ID          int64  `json:"id"`
}

func (q *Queries) UpdateObjective(ctx context.Context, arg UpdateObjectiveParams) error {
	_, err := q.db.Exec(ctx, updateObjective,
		arg.Title,
		arg.Description,
		arg.OwnerID,
		arg.ParentID,
		arg.Period,
		arg.Status,
		arg.ID,
	)
	return err
}
