// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: one_on_ones.sql

package db

import (
	"context"
	"time"
)

const addOneOnOneItem = `-- name: AddOneOnOneItem :one
INSERT INTO one_on_one_items (meeting_id, author_id, kind, body)
VALUES ($1, $2, $3,
        $4)
RETURNING id, meeting_id, author_id, kind, body, done, created_at
`

type AddOneOnOneItemParams struct {
	MeetingID int64  `json:"meeting_id"`
	AuthorID  *int64 `json:"author_id"`
	Kind      string `json:"kind"`
	Body      string `json:"body"`
}

func (q *Queries) AddOneOnOneItem(ctx context.Context, arg AddOneOnOneItemParams) (OneOnOneItem, error) {
	row := q.db.QueryRow(ctx, addOneOnOneItem,
		arg.MeetingID,
		arg.AuthorID,
		arg.Kind,
		arg.Body,
	)
	var i OneOnOneItem
	err := row.Scan(
		&i.ID,
		&i.MeetingID,
		&i.AuthorID,
		&i.Kind,
		&i.Body,
		&i.Done,
		&i.CreatedAt,
	)
	return i, err
}

const createOneOnOne = `-- name: CreateOneOnOne :one
INSERT INTO one_on_ones (manager_id, report_id, scheduled_at)
VALUES ($1, $2, $3)
RETURNING id, manager_id, report_id, scheduled_at, created_at
`

type CreateOneOnOneParams struct {
	ManagerID   int64     `json:"manager_id"`
	ReportID    int64     `json:"report_id"`
	ScheduledAt time.Time `json:"scheduled_at"`
}

func (q *Queries) CreateOneOnOne(ctx context.Context, arg CreateOneOnOneParams) (OneOnOne, error) {
	row := q.db.QueryRow(ctx, createOneOnOne, arg.ManagerID, arg.ReportID, arg.ScheduledAt)
	var i OneOnOne
	err := row.Scan(
		&i.ID,
		&i.ManagerID,
		&i.ReportID,
		&i.ScheduledAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteOneOnOne = `-- name: DeleteOneOnOne :exec
DELETE FROM one_on_ones WHERE id = $1
`

func (q *Queries) DeleteOneOnOne(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteOneOnOne, id)
	return err
}

const deleteOneOnOneItem = `-- name: DeleteOneOnOneItem :exec
DELETE FROM one_on_one_items WHERE id = $1
`

func (q *Queries) DeleteOneOnOneItem(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteOneOnOneItem, id)
	return err
}

const getOneOnOne = `-- name: GetOneOnOne :one
SELECT o.id, o.manager_id, o.report_id, o.scheduled_at, o.created_at,
       m.full_name AS manager_name,
       r.full_name AS report_name
FROM one_on_ones o
JOIN users m ON m.id = o.manager_id
JOIN users r ON r.id = o.report_id
WHERE o.id = $1
`

type GetOneOnOneRow struct {
	ID          int64     `json:"id"`
	ManagerID   int64     `json:"manager_id"`
	ReportID    int64     `json:"report_id"`
	ScheduledAt time.Time `json:"scheduled_at"`
	CreatedAt   time.Time `json:"created_at"`
	ManagerName string    `json:"manager_name"`
	ReportName  string    `json:"report_name"`
}

func (q *Queries) GetOneOnOne(ctx context.Context, id int64) (GetOneOnOneRow, error) {
	row := q.db.QueryRow(ctx, getOneOnOne, id)
	var i GetOneOnOneRow
	err := row.Scan(
		&i.ID,
		&i.ManagerID,
		&i.ReportID,
		&i.ScheduledAt,
		&i.CreatedAt,
		&i.ManagerName,
		&i.ReportName,
	)
	return i, err
}

const getOneOnOneItemMeeting = `-- name: GetOneOnOneItemMeeting :one
SELECT meeting_id FROM one_on_one_items WHERE id = $1
`

func (q *Queries) GetOneOnOneItemMeeting(ctx context.Context, id int64) (int64, error) {
	row := q.db.QueryRow(ctx, getOneOnOneItemMeeting, id)
	var meeting_id int64
	err := row.Scan(&meeting_id)
	return meeting_id, err
}

const listMyOneOnOnes = `-- name: ListMyOneOnOnes :many
SELECT o.id, o.manager_id, o.report_id, o.scheduled_at, o.created_at,
       m.full_name AS manager_name,
       r.full_name AS report_name
FROM one_on_ones o
JOIN users m ON m.id = o.manager_id
JOIN users r ON r.id = o.report_id
WHERE o.manager_id = $1 OR o.report_id = $1
ORDER BY o.scheduled_at DESC
`

type ListMyOneOnOnesRow struct {
	ID          int64     `json:"id"`
	ManagerID   int64     `json:"manager_id"`
	ReportID    int64     `json:"report_id"`
	ScheduledAt time.Time `json:"scheduled_at"`
	CreatedAt   time.Time `json:"created_at"`
	ManagerName string    `json:"manager_name"`
	ReportName  string    `json:"report_name"`
}

func (q *Queries) ListMyOneOnOnes(ctx context.Context, userID int64) ([]ListMyOneOnOnesRow, error) {
	rows, err := q.db.Query(ctx, listMyOneOnOnes, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMyOneOnOnesRow{}
	for rows.Next() {
		var i ListMyOneOnOnesRow
		if err := rows.Scan(
			&i.ID,
			&i.ManagerID,
			&i.ReportID,
			&i.ScheduledAt,
			&i.CreatedAt,
			&i.ManagerName,
			&i.ReportName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOneOnOneItems = `-- name: ListOneOnOneItems :many
SELECT i.id, i.meeting_id, i.author_id, i.kind, i.body, i.done, i.created_at, COALESCE(u.full_name, '')::text AS author_name
FROM one_on_one_items i
LEFT JOIN users u ON u.id = i.author_id
WHERE i.meeting_id = $1
ORDER BY i.created_at
`

type ListOneOnOneItemsRow struct {
	ID         int64     `json:"id"`
	MeetingID  int64     `json:"meeting_id"`
	AuthorID   *int64    `json:"author_id"`
	Kind       string    `json:"kind"`
	Body       string    `json:"body"`
	Done       bool      `json:"done"`
	CreatedAt  time.Time `json:"created_at"`
	AuthorName string    `json:"author_name"`
}

func (q *Queries) ListOneOnOneItems(ctx context.Context, meetingID int64) ([]ListOneOnOneItemsRow, error) {
	rows, err := q.db.Query(ctx, listOneOnOneItems, meetingID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOneOnOneItemsRow{}
	for rows.Next() {
		var i ListOneOnOneItemsRow
		if err := rows.Scan(
			&i.ID,
			&i.MeetingID,
			&i.AuthorID,
			&i.Kind,
			&i.Body,
			&i.Done,
			&i.CreatedAt,
			&i.AuthorName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const rescheduleOneOnOne = `-- name: RescheduleOneOnOne :exec
UPDATE one_on_ones SET scheduled_at = $1
WHERE id = $2
`

type RescheduleOneOnOneParams struct {
	ScheduledAt time.Time `json:"scheduled_at"`
	ID          int64     `json:"id"`
}

func (q *Queries) RescheduleOneOnOne(ctx context.Context, arg RescheduleOneOnOneParams) error {
	_, err := q.db.Exec(ctx, rescheduleOneOnOne, arg.ScheduledAt, arg.ID)
	return err
}

const setOneOnOneItemDone = `-- name: SetOneOnOneItemDone :exec
UPDATE one_on_one_items SET done = $1 WHERE id = $2
`

type SetOneOnOneItemDoneParams struct {
	Done bool  `json:"done"`
	ID   int64 `json:"id"`
}

func (q *Queries) SetOneOnOneItemDone(ctx context.Context, arg SetOneOnOneItemDoneParams) error {
	_, err := q.db.Exec(ctx, setOneOnOneItemDone, arg.Done, arg.ID)
	return err
}

const updateOneOnOneItem = `-- name: UpdateOneOnOneItem :exec
UPDATE one_on_one_items SET body = $1 WHERE id = $2
`

type UpdateOneOnOneItemParams struct {
	Body string `json:"body"`
	ID   int64  `json:"id"`
}

func (q *Queries) UpdateOneOnOneItem(ctx context.Context, arg UpdateOneOnOneItemParams) error {
	_, err := q.db.Exec(ctx, updateOneOnOneItem, arg.Body, arg.ID)
	return err
}
