// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: otp.sql

package db

import (
	"context"
	"time"
)

const consumeOTP = `-- name: ConsumeOTP :exec
UPDATE otp_codes
SET consumed = TRUE
WHERE id = $1
`

func (q *Queries) ConsumeOTP(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, consumeOTP, id)
	return err
}

const createOTP = `-- name: CreateOTP :one
INSERT INTO otp_codes (email, code_hash, purpose, expires_at)
VALUES ($1, $2, $3, $4)
RETURNING id, email, code_hash, purpose, expires_at, consumed, created_at
`

type CreateOTPParams struct {
	Email     string    `json:"email"`
	CodeHash  string    `json:"code_hash"`
	Purpose   string    `json:"purpose"`
	ExpiresAt time.Time `json:"expires_at"`
}

func (q *Queries) CreateOTP(ctx context.Context, arg CreateOTPParams) (OtpCode, error) {
	row := q.db.QueryRow(ctx, createOTP,
		arg.Email,
		arg.CodeHash,
		arg.Purpose,
		arg.ExpiresAt,
	)
	var i OtpCode
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.CodeHash,
		&i.Purpose,
		&i.ExpiresAt,
		&i.Consumed,
		&i.CreatedAt,
	)
	return i, err
}

const deleteOTPs = `-- name: DeleteOTPs :exec
DELETE FROM otp_codes
WHERE email = $1 AND purpose = $2
`

type DeleteOTPsParams struct {
	Email   string `json:"email"`
	Purpose string `json:"purpose"`
}

func (q *Queries) DeleteOTPs(ctx context.Context, arg DeleteOTPsParams) error {
	_, err := q.db.Exec(ctx, deleteOTPs, arg.Email, arg.Purpose)
	return err
}

const getLatestOTP = `-- name: GetLatestOTP :one
SELECT id, email, code_hash, purpose, expires_at, consumed, created_at FROM otp_codes
WHERE email = $1 AND purpose = $2 AND consumed = FALSE
ORDER BY created_at DESC
LIMIT 1
`

type GetLatestOTPParams struct {
	Email   string `json:"email"`
	Purpose string `json:"purpose"`
}

func (q *Queries) GetLatestOTP(ctx context.Context, arg GetLatestOTPParams) (OtpCode, error) {
	row := q.db.QueryRow(ctx, getLatestOTP, arg.Email, arg.Purpose)
	var i OtpCode
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.CodeHash,
		&i.Purpose,
		&i.ExpiresAt,
		&i.Consumed,
		&i.CreatedAt,
	)
	return i, err
}
