// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: page_links.sql

package db

import (
	"context"
)

const clearPageLinks = `-- name: ClearPageLinks :exec
DELETE FROM page_links WHERE source_page_id = $1
`

func (q *Queries) ClearPageLinks(ctx context.Context, sourcePageID int64) error {
	_, err := q.db.Exec(ctx, clearPageLinks, sourcePageID)
	return err
}

const findPageByTitle = `-- name: FindPageByTitle :one
SELECT id FROM pages
WHERE lower(title) = lower($1) AND is_template = false
ORDER BY id
LIMIT 1
`

func (q *Queries) FindPageByTitle(ctx context.Context, title string) (int64, error) {
	row := q.db.QueryRow(ctx, findPageByTitle, title)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertPageLink = `-- name: InsertPageLink :exec
INSERT INTO page_links (source_page_id, target_page_id)
VALUES ($1, $2)
ON CONFLICT (source_page_id, target_page_id) DO NOTHING
`

type InsertPageLinkParams struct {
	SourcePageID int64 `json:"source_page_id"`
	TargetPageID int64 `json:"target_page_id"`
}

func (q *Queries) InsertPageLink(ctx context.Context, arg InsertPageLinkParams) error {
	_, err := q.db.Exec(ctx, insertPageLink, arg.SourcePageID, arg.TargetPageID)
	return err
}

const listBacklinks = `-- name: ListBacklinks :many
SELECT p.id, p.title, p.type, p.icon
FROM page_links l
JOIN pages p ON p.id = l.source_page_id
WHERE l.target_page_id = $1
ORDER BY p.title, p.id
`

type ListBacklinksRow struct {
	ID    int64  `json:"id"`
	Title string `json:"title"`
	Type  string `json:"type"`
	Icon  string `json:"icon"`
}

func (q *Queries) ListBacklinks(ctx context.Context, targetPageID int64) ([]ListBacklinksRow, error) {
	rows, err := q.db.Query(ctx, listBacklinks, targetPageID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBacklinksRow{}
	for rows.Next() {
		var i ListBacklinksRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Type,
			&i.Icon,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
