// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: pages.sql

package db

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPage = `-- name: CreatePage :one
INSERT INTO pages (type, title, icon, body, parent_id, is_template, category,
                   owner_id, review_at, created_by, updated_by)
VALUES ($1, $2, $3, $4,
        $5, $6, $7,
        $8, $9,
        $10, $11)
RETURNING id, type, title, icon, body, created_by, updated_by, created_at, updated_at, parent_id, is_template, category, owner_id, review_at
`

type CreatePageParams struct {
	Type       string             `json:"type"`
	Title      string             `json:"title"`
	Icon       string             `json:"icon"`
	Body       string             `json:"body"`
	ParentID   *int64             `json:"parent_id"`
	IsTemplate bool               `json:"is_template"`
	Category   string             `json:"category"`
	OwnerID    *int64             `json:"owner_id"`
	ReviewAt   pgtype.Timestamptz `json:"review_at"`
	CreatedBy  *int64             `json:"created_by"`
	UpdatedBy  *int64             `json:"updated_by"`
}

func (q *Queries) CreatePage(ctx context.Context, arg CreatePageParams) (Page, error) {
	row := q.db.QueryRow(ctx, createPage,
		arg.Type,
		arg.Title,
		arg.Icon,
		arg.Body,
		arg.ParentID,
		arg.IsTemplate,
		arg.Category,
		arg.OwnerID,
		arg.ReviewAt,
		arg.CreatedBy,
		arg.UpdatedBy,
	)
	var i Page
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Title,
		&i.Icon,
		&i.Body,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ParentID,
		&i.IsTemplate,
		&i.Category,
		&i.OwnerID,
		&i.ReviewAt,
	)
	return i, err
}

const deletePage = `-- name: DeletePage :exec
DELETE FROM pages WHERE id = $1
`

func (q *Queries) DeletePage(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deletePage, id)
	return err
}

const getPage = `-- name: GetPage :one
SELECT p.id, p.type, p.title, p.icon, p.body, p.parent_id, p.is_template,
       p.category, p.owner_id, p.review_at, p.created_by, p.updated_by,
       p.created_at, p.updated_at,
       COALESCE(cu.full_name, '')::text AS created_by_name,
       COALESCE(uu.full_name, '')::text AS updated_by_name,
       COALESCE(ow.full_name, '')::text AS owner_name
FROM pages p
LEFT JOIN users cu ON cu.id = p.created_by
LEFT JOIN users uu ON uu.id = p.updated_by
LEFT JOIN users ow ON ow.id = p.owner_id
WHERE p.id = $1
`

type GetPageRow struct {
	ID            int64              `json:"id"`
	Type          string             `json:"type"`
	Title         string             `json:"title"`
	Icon          string             `json:"icon"`
	Body          string             `json:"body"`
	ParentID      *int64             `json:"parent_id"`
	IsTemplate    bool               `json:"is_template"`
	Category      string             `json:"category"`
	OwnerID       *int64             `json:"owner_id"`
	ReviewAt      pgtype.Timestamptz `json:"review_at"`
	CreatedBy     *int64             `json:"created_by"`
	UpdatedBy     *int64             `json:"updated_by"`
	CreatedAt     time.Time          `json:"created_at"`
	UpdatedAt     time.Time          `json:"updated_at"`
	CreatedByName string             `json:"created_by_name"`
	UpdatedByName string             `json:"updated_by_name"`
	OwnerName     string             `json:"owner_name"`
}

func (q *Queries) GetPage(ctx context.Context, id int64) (GetPageRow, error) {
	row := q.db.QueryRow(ctx, getPage, id)
	var i GetPageRow
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Title,
		&i.Icon,
		&i.Body,
		&i.ParentID,
		&i.IsTemplate,
		&i.Category,
		&i.OwnerID,
		&i.ReviewAt,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedByName,
		&i.UpdatedByName,
		&i.OwnerName,
	)
	return i, err
}

const listPages = `-- name: ListPages :many
SELECT p.id, p.type, p.title, p.icon, p.parent_id, p.is_template, p.category,
       p.owner_id, p.review_at, p.created_at, p.updated_at,
       COALESCE(cu.full_name, '')::text AS created_by_name,
       COALESCE(uu.full_name, '')::text AS updated_by_name,
       COALESCE(ow.full_name, '')::text AS owner_name
FROM pages p
LEFT JOIN users cu ON cu.id = p.created_by
LEFT JOIN users uu ON uu.id = p.updated_by
LEFT JOIN users ow ON ow.id = p.owner_id
WHERE p.type = $1 AND p.is_template = $2
ORDER BY p.title ASC
`

type ListPagesParams struct {
	Type       string `json:"type"`
	IsTemplate bool   `json:"is_template"`
}

type ListPagesRow struct {
	ID            int64              `json:"id"`
	Type          string             `json:"type"`
	Title         string             `json:"title"`
	Icon          string             `json:"icon"`
	ParentID      *int64             `json:"parent_id"`
	IsTemplate    bool               `json:"is_template"`
	Category      string             `json:"category"`
	OwnerID       *int64             `json:"owner_id"`
	ReviewAt      pgtype.Timestamptz `json:"review_at"`
	CreatedAt     time.Time          `json:"created_at"`
	UpdatedAt     time.Time          `json:"updated_at"`
	CreatedByName string             `json:"created_by_name"`
	UpdatedByName string             `json:"updated_by_name"`
	OwnerName     string             `json:"owner_name"`
}

func (q *Queries) ListPages(ctx context.Context, arg ListPagesParams) ([]ListPagesRow, error) {
	rows, err := q.db.Query(ctx, listPages, arg.Type, arg.IsTemplate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPagesRow{}
	for rows.Next() {
		var i ListPagesRow
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.Title,
			&i.Icon,
			&i.ParentID,
			&i.IsTemplate,
			&i.Category,
			&i.OwnerID,
			&i.ReviewAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CreatedByName,
			&i.UpdatedByName,
			&i.OwnerName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setPageParent = `-- name: SetPageParent :exec
UPDATE pages SET parent_id = $1, updated_at = now()
WHERE id = $2
`

type SetPageParentParams struct {
	ParentID *int64 `json:"parent_id"`
	ID       int64  `json:"id"`
}

func (q *Queries) SetPageParent(ctx context.Context, arg SetPageParentParams) error {
	_, err := q.db.Exec(ctx, setPageParent, arg.ParentID, arg.ID)
	return err
}

const updatePage = `-- name: UpdatePage :exec
UPDATE pages
SET title = $1, icon = $2, body = $3,
    category = $4, owner_id = $5,
    review_at = $6,
    updated_by = $7, updated_at = now()
WHERE id = $8
`

type UpdatePageParams struct {
	Title     string             `json:"title"`
	Icon      string             `json:"icon"`
	Body      string             `json:"body"`
	Category  string             `json:"category"`
	OwnerID   *int64             `json:"owner_id"`
	ReviewAt  pgtype.Timestamptz `json:"review_at"`
	UpdatedBy *int64             `json:"updated_by"`
	ID        int64              `json:"id"`
}

func (q *Queries) UpdatePage(ctx context.Context, arg UpdatePageParams) error {
	_, err := q.db.Exec(ctx, updatePage,
		arg.Title,
		arg.Icon,
		arg.Body,
		arg.Category,
		arg.OwnerID,
		arg.ReviewAt,
		arg.UpdatedBy,
		arg.ID,
	)
	return err
}
