// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: page_versions.sql

package db

import (
	"context"
	"time"
)

const getPageVersion = `-- name: GetPageVersion :one
SELECT id, page_id, title, body, edited_by, edited_at, created_at FROM page_versions WHERE id = $1
`

func (q *Queries) GetPageVersion(ctx context.Context, id int64) (PageVersion, error) {
	row := q.db.QueryRow(ctx, getPageVersion, id)
	var i PageVersion
	err := row.Scan(
		&i.ID,
		&i.PageID,
		&i.Title,
		&i.Body,
		&i.EditedBy,
		&i.EditedAt,
		&i.CreatedAt,
	)
	return i, err
}

const hasRecentPageVersion = `-- name: HasRecentPageVersion :one
SELECT EXISTS(
    SELECT 1 FROM page_versions
    WHERE page_id = $1 AND created_at > $2
)::bool
`

type HasRecentPageVersionParams struct {
	PageID int64     `json:"page_id"`
	Since  time.Time `json:"since"`
}

func (q *Queries) HasRecentPageVersion(ctx context.Context, arg HasRecentPageVersionParams) (bool, error) {
	row := q.db.QueryRow(ctx, hasRecentPageVersion, arg.PageID, arg.Since)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const listPageVersions = `-- name: ListPageVersions :many
SELECT v.id, v.page_id, v.title, v.body, v.edited_by, v.edited_at,
       v.created_at, COALESCE(u.full_name, '')::text AS editor_name
FROM page_versions v
LEFT JOIN users u ON u.id = v.edited_by
WHERE v.page_id = $1
ORDER BY v.created_at DESC
LIMIT 50
`

type ListPageVersionsRow struct {
	ID         int64     `json:"id"`
	PageID     int64     `json:"page_id"`
	Title      string    `json:"title"`
	Body       string    `json:"body"`
	EditedBy   *int64    `json:"edited_by"`
	EditedAt   time.Time `json:"edited_at"`
	CreatedAt  time.Time `json:"created_at"`
	EditorName string    `json:"editor_name"`
}

func (q *Queries) ListPageVersions(ctx context.Context, pageID int64) ([]ListPageVersionsRow, error) {
	rows, err := q.db.Query(ctx, listPageVersions, pageID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPageVersionsRow{}
	for rows.Next() {
		var i ListPageVersionsRow
		if err := rows.Scan(
			&i.ID,
			&i.PageID,
			&i.Title,
			&i.Body,
			&i.EditedBy,
			&i.EditedAt,
			&i.CreatedAt,
			&i.EditorName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const restorePageContent = `-- name: RestorePageContent :exec
UPDATE pages
SET title = $1,
    body = $2,
    updated_by = $3,
    updated_at = now()
WHERE id = $4
`

type RestorePageContentParams struct {
	Title     string `json:"title"`
	Body      string `json:"body"`
	UpdatedBy *int64 `json:"updated_by"`
	ID        int64  `json:"id"`
}

func (q *Queries) RestorePageContent(ctx context.Context, arg RestorePageContentParams) error {
	_, err := q.db.Exec(ctx, restorePageContent,
		arg.Title,
		arg.Body,
		arg.UpdatedBy,
		arg.ID,
	)
	return err
}

const snapshotPageVersion = `-- name: SnapshotPageVersion :exec
INSERT INTO page_versions (page_id, title, body, edited_by, edited_at)
VALUES ($1, $2, $3,
        $4, $5)
`

type SnapshotPageVersionParams struct {
	PageID   int64     `json:"page_id"`
	Title    string    `json:"title"`
	Body     string    `json:"body"`
	EditedBy *int64    `json:"edited_by"`
	EditedAt time.Time `json:"edited_at"`
}

func (q *Queries) SnapshotPageVersion(ctx context.Context, arg SnapshotPageVersionParams) error {
	_, err := q.db.Exec(ctx, snapshotPageVersion,
		arg.PageID,
		arg.Title,
		arg.Body,
		arg.EditedBy,
		arg.EditedAt,
	)
	return err
}
