// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: pages.sql

package db

import (
	"context"
	"time"
)

const createPage = `-- name: CreatePage :one
INSERT INTO pages (type, title, icon, body, parent_id, created_by, updated_by)
VALUES ($1, $2, $3, $4,
        $5, $6, $7)
RETURNING id, type, title, icon, body, created_by, updated_by, created_at, updated_at, parent_id
`

type CreatePageParams struct {
	Type      string `json:"type"`
	Title     string `json:"title"`
	Icon      string `json:"icon"`
	Body      string `json:"body"`
	ParentID  *int64 `json:"parent_id"`
	CreatedBy *int64 `json:"created_by"`
	UpdatedBy *int64 `json:"updated_by"`
}

func (q *Queries) CreatePage(ctx context.Context, arg CreatePageParams) (Page, error) {
	row := q.db.QueryRow(ctx, createPage,
		arg.Type,
		arg.Title,
		arg.Icon,
		arg.Body,
		arg.ParentID,
		arg.CreatedBy,
		arg.UpdatedBy,
	)
	var i Page
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Title,
		&i.Icon,
		&i.Body,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ParentID,
	)
	return i, err
}

const deletePage = `-- name: DeletePage :exec
DELETE FROM pages WHERE id = $1
`

func (q *Queries) DeletePage(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deletePage, id)
	return err
}

const getPage = `-- name: GetPage :one
SELECT p.id, p.type, p.title, p.icon, p.body, p.parent_id,
       p.created_by, p.updated_by, p.created_at, p.updated_at,
       COALESCE(cu.full_name, '')::text AS created_by_name,
       COALESCE(uu.full_name, '')::text AS updated_by_name
FROM pages p
LEFT JOIN users cu ON cu.id = p.created_by
LEFT JOIN users uu ON uu.id = p.updated_by
WHERE p.id = $1
`

type GetPageRow struct {
	ID            int64     `json:"id"`
	Type          string    `json:"type"`
	Title         string    `json:"title"`
	Icon          string    `json:"icon"`
	Body          string    `json:"body"`
	ParentID      *int64    `json:"parent_id"`
	CreatedBy     *int64    `json:"created_by"`
	UpdatedBy     *int64    `json:"updated_by"`
	CreatedAt     time.Time `json:"created_at"`
	UpdatedAt     time.Time `json:"updated_at"`
	CreatedByName string    `json:"created_by_name"`
	UpdatedByName string    `json:"updated_by_name"`
}

func (q *Queries) GetPage(ctx context.Context, id int64) (GetPageRow, error) {
	row := q.db.QueryRow(ctx, getPage, id)
	var i GetPageRow
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Title,
		&i.Icon,
		&i.Body,
		&i.ParentID,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedByName,
		&i.UpdatedByName,
	)
	return i, err
}

const listPages = `-- name: ListPages :many
SELECT p.id, p.type, p.title, p.icon, p.parent_id, p.created_at, p.updated_at,
       COALESCE(cu.full_name, '')::text AS created_by_name,
       COALESCE(uu.full_name, '')::text AS updated_by_name
FROM pages p
LEFT JOIN users cu ON cu.id = p.created_by
LEFT JOIN users uu ON uu.id = p.updated_by
WHERE p.type = $1
ORDER BY p.title ASC
`

type ListPagesRow struct {
	ID            int64     `json:"id"`
	Type          string    `json:"type"`
	Title         string    `json:"title"`
	Icon          string    `json:"icon"`
	ParentID      *int64    `json:"parent_id"`
	CreatedAt     time.Time `json:"created_at"`
	UpdatedAt     time.Time `json:"updated_at"`
	CreatedByName string    `json:"created_by_name"`
	UpdatedByName string    `json:"updated_by_name"`
}

func (q *Queries) ListPages(ctx context.Context, type_ string) ([]ListPagesRow, error) {
	rows, err := q.db.Query(ctx, listPages, type_)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPagesRow{}
	for rows.Next() {
		var i ListPagesRow
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.Title,
			&i.Icon,
			&i.ParentID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CreatedByName,
			&i.UpdatedByName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setPageParent = `-- name: SetPageParent :exec
UPDATE pages SET parent_id = $1, updated_at = now()
WHERE id = $2
`

type SetPageParentParams struct {
	ParentID *int64 `json:"parent_id"`
	ID       int64  `json:"id"`
}

func (q *Queries) SetPageParent(ctx context.Context, arg SetPageParentParams) error {
	_, err := q.db.Exec(ctx, setPageParent, arg.ParentID, arg.ID)
	return err
}

const updatePage = `-- name: UpdatePage :exec
UPDATE pages
SET title = $1, icon = $2, body = $3,
    updated_by = $4, updated_at = now()
WHERE id = $5
`

type UpdatePageParams struct {
	Title     string `json:"title"`
	Icon      string `json:"icon"`
	Body      string `json:"body"`
	UpdatedBy *int64 `json:"updated_by"`
	ID        int64  `json:"id"`
}

func (q *Queries) UpdatePage(ctx context.Context, arg UpdatePageParams) error {
	_, err := q.db.Exec(ctx, updatePage,
		arg.Title,
		arg.Icon,
		arg.Body,
		arg.UpdatedBy,
		arg.ID,
	)
	return err
}
