// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: productivity.sql

package db

import (
	"context"
	"time"
)

const addFavorite = `-- name: AddFavorite :exec
INSERT INTO favorites (user_id, kind, item_id, label, route)
VALUES ($1, $2, $3,
        $4, $5)
ON CONFLICT (user_id, kind, item_id)
DO UPDATE SET label = $4, route = $5
`

type AddFavoriteParams struct {
	UserID int64  `json:"user_id"`
	Kind   string `json:"kind"`
	ItemID int64  `json:"item_id"`
	Label  string `json:"label"`
	Route  string `json:"route"`
}

func (q *Queries) AddFavorite(ctx context.Context, arg AddFavoriteParams) error {
	_, err := q.db.Exec(ctx, addFavorite,
		arg.UserID,
		arg.Kind,
		arg.ItemID,
		arg.Label,
		arg.Route,
	)
	return err
}

const createReminder = `-- name: CreateReminder :one
INSERT INTO reminders (user_id, task_id, note, remind_at)
VALUES ($1, $2, $3,
        $4)
RETURNING id, task_id, note, remind_at, sent, created_at
`

type CreateReminderParams struct {
	UserID   int64     `json:"user_id"`
	TaskID   *int64    `json:"task_id"`
	Note     string    `json:"note"`
	RemindAt time.Time `json:"remind_at"`
}

type CreateReminderRow struct {
	ID        int64     `json:"id"`
	TaskID    *int64    `json:"task_id"`
	Note      string    `json:"note"`
	RemindAt  time.Time `json:"remind_at"`
	Sent      bool      `json:"sent"`
	CreatedAt time.Time `json:"created_at"`
}

func (q *Queries) CreateReminder(ctx context.Context, arg CreateReminderParams) (CreateReminderRow, error) {
	row := q.db.QueryRow(ctx, createReminder,
		arg.UserID,
		arg.TaskID,
		arg.Note,
		arg.RemindAt,
	)
	var i CreateReminderRow
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.Note,
		&i.RemindAt,
		&i.Sent,
		&i.CreatedAt,
	)
	return i, err
}

const createSavedFilter = `-- name: CreateSavedFilter :one
INSERT INTO saved_filters (user_id, name, config)
VALUES ($1, $2, $3)
RETURNING id, name, config, created_at
`

type CreateSavedFilterParams struct {
	UserID int64  `json:"user_id"`
	Name   string `json:"name"`
	Config string `json:"config"`
}

type CreateSavedFilterRow struct {
	ID        int64     `json:"id"`
	Name      string    `json:"name"`
	Config    string    `json:"config"`
	CreatedAt time.Time `json:"created_at"`
}

func (q *Queries) CreateSavedFilter(ctx context.Context, arg CreateSavedFilterParams) (CreateSavedFilterRow, error) {
	row := q.db.QueryRow(ctx, createSavedFilter, arg.UserID, arg.Name, arg.Config)
	var i CreateSavedFilterRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Config,
		&i.CreatedAt,
	)
	return i, err
}

const deleteReminder = `-- name: DeleteReminder :exec
DELETE FROM reminders
WHERE id = $1 AND user_id = $2
`

type DeleteReminderParams struct {
	ID     int64 `json:"id"`
	UserID int64 `json:"user_id"`
}

func (q *Queries) DeleteReminder(ctx context.Context, arg DeleteReminderParams) error {
	_, err := q.db.Exec(ctx, deleteReminder, arg.ID, arg.UserID)
	return err
}

const deleteSavedFilter = `-- name: DeleteSavedFilter :exec
DELETE FROM saved_filters
WHERE id = $1 AND user_id = $2
`

type DeleteSavedFilterParams struct {
	ID     int64 `json:"id"`
	UserID int64 `json:"user_id"`
}

func (q *Queries) DeleteSavedFilter(ctx context.Context, arg DeleteSavedFilterParams) error {
	_, err := q.db.Exec(ctx, deleteSavedFilter, arg.ID, arg.UserID)
	return err
}

const dueUserReminders = `-- name: DueUserReminders :many
SELECT r.id, r.user_id, r.task_id, r.note,
       COALESCE(t.title, '')::text AS task_title
FROM reminders r
LEFT JOIN tasks t ON t.id = r.task_id
WHERE NOT r.sent AND r.remind_at <= now()
`

type DueUserRemindersRow struct {
	ID        int64  `json:"id"`
	UserID    int64  `json:"user_id"`
	TaskID    *int64 `json:"task_id"`
	Note      string `json:"note"`
	TaskTitle string `json:"task_title"`
}

func (q *Queries) DueUserReminders(ctx context.Context) ([]DueUserRemindersRow, error) {
	rows, err := q.db.Query(ctx, dueUserReminders)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DueUserRemindersRow{}
	for rows.Next() {
		var i DueUserRemindersRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.TaskID,
			&i.Note,
			&i.TaskTitle,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFavorites = `-- name: ListFavorites :many
SELECT id, kind, item_id, label, route, created_at
FROM favorites
WHERE user_id = $1
ORDER BY created_at DESC
`

type ListFavoritesRow struct {
	ID        int64     `json:"id"`
	Kind      string    `json:"kind"`
	ItemID    int64     `json:"item_id"`
	Label     string    `json:"label"`
	Route     string    `json:"route"`
	CreatedAt time.Time `json:"created_at"`
}

func (q *Queries) ListFavorites(ctx context.Context, userID int64) ([]ListFavoritesRow, error) {
	rows, err := q.db.Query(ctx, listFavorites, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListFavoritesRow{}
	for rows.Next() {
		var i ListFavoritesRow
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.ItemID,
			&i.Label,
			&i.Route,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReminders = `-- name: ListReminders :many
SELECT r.id, r.task_id, r.note, r.remind_at, r.sent, r.created_at,
       COALESCE(t.title, '')::text AS task_title
FROM reminders r
LEFT JOIN tasks t ON t.id = r.task_id
WHERE r.user_id = $1
ORDER BY r.remind_at
`

type ListRemindersRow struct {
	ID        int64     `json:"id"`
	TaskID    *int64    `json:"task_id"`
	Note      string    `json:"note"`
	RemindAt  time.Time `json:"remind_at"`
	Sent      bool      `json:"sent"`
	CreatedAt time.Time `json:"created_at"`
	TaskTitle string    `json:"task_title"`
}

func (q *Queries) ListReminders(ctx context.Context, userID int64) ([]ListRemindersRow, error) {
	rows, err := q.db.Query(ctx, listReminders, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRemindersRow{}
	for rows.Next() {
		var i ListRemindersRow
		if err := rows.Scan(
			&i.ID,
			&i.TaskID,
			&i.Note,
			&i.RemindAt,
			&i.Sent,
			&i.CreatedAt,
			&i.TaskTitle,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSavedFilters = `-- name: ListSavedFilters :many
SELECT id, name, config, created_at
FROM saved_filters
WHERE user_id = $1
ORDER BY name
`

type ListSavedFiltersRow struct {
	ID        int64     `json:"id"`
	Name      string    `json:"name"`
	Config    string    `json:"config"`
	CreatedAt time.Time `json:"created_at"`
}

func (q *Queries) ListSavedFilters(ctx context.Context, userID int64) ([]ListSavedFiltersRow, error) {
	rows, err := q.db.Query(ctx, listSavedFilters, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSavedFiltersRow{}
	for rows.Next() {
		var i ListSavedFiltersRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Config,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markReminderSent = `-- name: MarkReminderSent :exec
UPDATE reminders SET sent = TRUE WHERE id = $1
`

func (q *Queries) MarkReminderSent(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, markReminderSent, id)
	return err
}

const removeFavorite = `-- name: RemoveFavorite :exec
DELETE FROM favorites
WHERE user_id = $1 AND kind = $2
  AND item_id = $3
`

type RemoveFavoriteParams struct {
	UserID int64  `json:"user_id"`
	Kind   string `json:"kind"`
	ItemID int64  `json:"item_id"`
}

func (q *Queries) RemoveFavorite(ctx context.Context, arg RemoveFavoriteParams) error {
	_, err := q.db.Exec(ctx, removeFavorite, arg.UserID, arg.Kind, arg.ItemID)
	return err
}
