// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: projects.sql

package db

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const createProject = `-- name: CreateProject :one
INSERT INTO projects (name, description, status, due_date, created_by, space_id, folder_id)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, name, description, status, due_date, created_by, created_at, updated_at, space_id, folder_id, client_id
`

type CreateProjectParams struct {
	Name        string             `json:"name"`
	Description string             `json:"description"`
	Status      string             `json:"status"`
	DueDate     pgtype.Timestamptz `json:"due_date"`
	CreatedBy   *int64             `json:"created_by"`
	SpaceID     *int64             `json:"space_id"`
	FolderID    *int64             `json:"folder_id"`
}

func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, createProject,
		arg.Name,
		arg.Description,
		arg.Status,
		arg.DueDate,
		arg.CreatedBy,
		arg.SpaceID,
		arg.FolderID,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Status,
		&i.DueDate,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SpaceID,
		&i.FolderID,
		&i.ClientID,
	)
	return i, err
}

const deleteProject = `-- name: DeleteProject :exec
DELETE FROM projects
WHERE id = $1
`

func (q *Queries) DeleteProject(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteProject, id)
	return err
}

const getProject = `-- name: GetProject :one
SELECT id, name, description, status, due_date, created_by, created_at, updated_at, space_id, folder_id, client_id FROM projects
WHERE id = $1
`

func (q *Queries) GetProject(ctx context.Context, id int64) (Project, error) {
	row := q.db.QueryRow(ctx, getProject, id)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Status,
		&i.DueDate,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SpaceID,
		&i.FolderID,
		&i.ClientID,
	)
	return i, err
}

const listProjects = `-- name: ListProjects :many
SELECT p.id, p.name, p.description, p.status, p.due_date, p.created_by, p.created_at, p.updated_at, p.space_id, p.folder_id, p.client_id,
       COALESCE(c.total, 0)::int          AS total_tasks,
       COALESCE(c.done, 0)::int           AS done_tasks,
       COALESCE(m.member_names, '{}')::text[] AS member_names
FROM projects p
LEFT JOIN (
    SELECT project_id,
           COUNT(*)                    AS total,
           COUNT(*) FILTER (WHERE done) AS done
    FROM tasks
    WHERE project_id IS NOT NULL
    GROUP BY project_id
) c ON c.project_id = p.id
LEFT JOIN (
    SELECT t.project_id, array_agg(DISTINCT u.full_name) AS member_names
    FROM tasks t
    JOIN users u ON u.id = t.assignee_id
    WHERE t.project_id IS NOT NULL
    GROUP BY t.project_id
) m ON m.project_id = p.id
ORDER BY p.created_at DESC
`

type ListProjectsRow struct {
	ID          int64              `json:"id"`
	Name        string             `json:"name"`
	Description string             `json:"description"`
	Status      string             `json:"status"`
	DueDate     pgtype.Timestamptz `json:"due_date"`
	CreatedBy   *int64             `json:"created_by"`
	CreatedAt   time.Time          `json:"created_at"`
	UpdatedAt   time.Time          `json:"updated_at"`
	SpaceID     *int64             `json:"space_id"`
	FolderID    *int64             `json:"folder_id"`
	ClientID    *int64             `json:"client_id"`
	TotalTasks  int32              `json:"total_tasks"`
	DoneTasks   int32              `json:"done_tasks"`
	MemberNames []string           `json:"member_names"`
}

func (q *Queries) ListProjects(ctx context.Context) ([]ListProjectsRow, error) {
	rows, err := q.db.Query(ctx, listProjects)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProjectsRow{}
	for rows.Next() {
		var i ListProjectsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Status,
			&i.DueDate,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SpaceID,
			&i.FolderID,
			&i.ClientID,
			&i.TotalTasks,
			&i.DoneTasks,
			&i.MemberNames,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProject = `-- name: UpdateProject :one
UPDATE projects
SET name        = $2,
    description = $3,
    status      = $4,
    due_date    = $5,
    space_id    = $6,
    folder_id   = $7,
    updated_at  = now()
WHERE id = $1
RETURNING id, name, description, status, due_date, created_by, created_at, updated_at, space_id, folder_id, client_id
`

type UpdateProjectParams struct {
	ID          int64              `json:"id"`
	Name        string             `json:"name"`
	Description string             `json:"description"`
	Status      string             `json:"status"`
	DueDate     pgtype.Timestamptz `json:"due_date"`
	SpaceID     *int64             `json:"space_id"`
	FolderID    *int64             `json:"folder_id"`
}

func (q *Queries) UpdateProject(ctx context.Context, arg UpdateProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, updateProject,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.Status,
		arg.DueDate,
		arg.SpaceID,
		arg.FolderID,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Status,
		&i.DueDate,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SpaceID,
		&i.FolderID,
		&i.ClientID,
	)
	return i, err
}
