// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: project_shares.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createProjectShare = `-- name: CreateProjectShare :one
INSERT INTO project_shares (token, project_id, created_by)
VALUES ($1, $2, $3)
RETURNING token
`

type CreateProjectShareParams struct {
	Token     string `json:"token"`
	ProjectID int64  `json:"project_id"`
	CreatedBy *int64 `json:"created_by"`
}

func (q *Queries) CreateProjectShare(ctx context.Context, arg CreateProjectShareParams) (string, error) {
	row := q.db.QueryRow(ctx, createProjectShare, arg.Token, arg.ProjectID, arg.CreatedBy)
	var token string
	err := row.Scan(&token)
	return token, err
}

const getProjectShareToken = `-- name: GetProjectShareToken :one
SELECT token FROM project_shares WHERE project_id = $1
`

func (q *Queries) GetProjectShareToken(ctx context.Context, projectID int64) (string, error) {
	row := q.db.QueryRow(ctx, getProjectShareToken, projectID)
	var token string
	err := row.Scan(&token)
	return token, err
}

const getSharedProject = `-- name: GetSharedProject :one
SELECT p.id, p.name, p.description, p.status, p.due_date
FROM project_shares s
JOIN projects p ON p.id = s.project_id
WHERE s.token = $1
`

type GetSharedProjectRow struct {
	ID          int64              `json:"id"`
	Name        string             `json:"name"`
	Description string             `json:"description"`
	Status      string             `json:"status"`
	DueDate     pgtype.Timestamptz `json:"due_date"`
}

func (q *Queries) GetSharedProject(ctx context.Context, token string) (GetSharedProjectRow, error) {
	row := q.db.QueryRow(ctx, getSharedProject, token)
	var i GetSharedProjectRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Status,
		&i.DueDate,
	)
	return i, err
}

const listSharedProjectTasks = `-- name: ListSharedProjectTasks :many
SELECT t.id, t.title, t.done, t.status, t.due_date
FROM project_shares s
JOIN tasks t ON t.project_id = s.project_id
WHERE s.token = $1 AND t.parent_id IS NULL
ORDER BY t.done, t.created_at
`

type ListSharedProjectTasksRow struct {
	ID      int64              `json:"id"`
	Title   string             `json:"title"`
	Done    bool               `json:"done"`
	Status  string             `json:"status"`
	DueDate pgtype.Timestamptz `json:"due_date"`
}

func (q *Queries) ListSharedProjectTasks(ctx context.Context, token string) ([]ListSharedProjectTasksRow, error) {
	rows, err := q.db.Query(ctx, listSharedProjectTasks, token)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSharedProjectTasksRow{}
	for rows.Next() {
		var i ListSharedProjectTasksRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Done,
			&i.Status,
			&i.DueDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeProjectShare = `-- name: RevokeProjectShare :exec
DELETE FROM project_shares WHERE project_id = $1
`

func (q *Queries) RevokeProjectShare(ctx context.Context, projectID int64) error {
	_, err := q.db.Exec(ctx, revokeProjectShare, projectID)
	return err
}
