// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: project_templates.sql

package db

import (
	"context"
)

const createProjectTemplate = `-- name: CreateProjectTemplate :one
INSERT INTO project_templates (name, project_name, description, status, created_by)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, name, project_name, description, status, created_by, created_at
`

type CreateProjectTemplateParams struct {
	Name        string `json:"name"`
	ProjectName string `json:"project_name"`
	Description string `json:"description"`
	Status      string `json:"status"`
	CreatedBy   *int64 `json:"created_by"`
}

func (q *Queries) CreateProjectTemplate(ctx context.Context, arg CreateProjectTemplateParams) (ProjectTemplate, error) {
	row := q.db.QueryRow(ctx, createProjectTemplate,
		arg.Name,
		arg.ProjectName,
		arg.Description,
		arg.Status,
		arg.CreatedBy,
	)
	var i ProjectTemplate
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ProjectName,
		&i.Description,
		&i.Status,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const deleteProjectTemplate = `-- name: DeleteProjectTemplate :exec
DELETE FROM project_templates WHERE id = $1
`

func (q *Queries) DeleteProjectTemplate(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteProjectTemplate, id)
	return err
}

const listProjectTemplates = `-- name: ListProjectTemplates :many
SELECT id, name, project_name, description, status, created_by, created_at FROM project_templates ORDER BY name, id
`

func (q *Queries) ListProjectTemplates(ctx context.Context) ([]ProjectTemplate, error) {
	rows, err := q.db.Query(ctx, listProjectTemplates)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProjectTemplate{}
	for rows.Next() {
		var i ProjectTemplate
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ProjectName,
			&i.Description,
			&i.Status,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
