// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: project_members.sql

package db

import (
	"context"
	"time"
)

const countProjectMembers = `-- name: CountProjectMembers :one
SELECT COUNT(*) FROM project_members WHERE project_id = $1
`

func (q *Queries) CountProjectMembers(ctx context.Context, projectID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countProjectMembers, projectID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteProjectMember = `-- name: DeleteProjectMember :exec
DELETE FROM project_members
WHERE project_id = $1 AND user_id = $2
`

type DeleteProjectMemberParams struct {
	ProjectID int64 `json:"project_id"`
	UserID    int64 `json:"user_id"`
}

func (q *Queries) DeleteProjectMember(ctx context.Context, arg DeleteProjectMemberParams) error {
	_, err := q.db.Exec(ctx, deleteProjectMember, arg.ProjectID, arg.UserID)
	return err
}

const getProjectMemberRole = `-- name: GetProjectMemberRole :one
SELECT role FROM project_members
WHERE project_id = $1 AND user_id = $2
`

type GetProjectMemberRoleParams struct {
	ProjectID int64 `json:"project_id"`
	UserID    int64 `json:"user_id"`
}

func (q *Queries) GetProjectMemberRole(ctx context.Context, arg GetProjectMemberRoleParams) (string, error) {
	row := q.db.QueryRow(ctx, getProjectMemberRole, arg.ProjectID, arg.UserID)
	var role string
	err := row.Scan(&role)
	return role, err
}

const listProjectAccess = `-- name: ListProjectAccess :many
SELECT p.id AS project_id,
       COALESCE(mine.role, '')::text AS my_role,
       COALESCE(cnt.n, 0)::bigint    AS member_count
FROM projects p
LEFT JOIN project_members mine
       ON mine.project_id = p.id AND mine.user_id = $1
LEFT JOIN (
    SELECT project_id, COUNT(*) AS n FROM project_members GROUP BY project_id
) cnt ON cnt.project_id = p.id
`

type ListProjectAccessRow struct {
	ProjectID   int64  `json:"project_id"`
	MyRole      string `json:"my_role"`
	MemberCount int64  `json:"member_count"`
}

func (q *Queries) ListProjectAccess(ctx context.Context, userID int64) ([]ListProjectAccessRow, error) {
	rows, err := q.db.Query(ctx, listProjectAccess, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProjectAccessRow{}
	for rows.Next() {
		var i ListProjectAccessRow
		if err := rows.Scan(&i.ProjectID, &i.MyRole, &i.MemberCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectMembers = `-- name: ListProjectMembers :many
SELECT pm.project_id, pm.user_id, pm.role, pm.created_at,
       COALESCE(u.full_name, '')::text AS user_name,
       COALESCE(u.email, '')::text     AS user_email
FROM project_members pm
JOIN users u ON u.id = pm.user_id
WHERE pm.project_id = $1
ORDER BY u.full_name, pm.user_id
`

type ListProjectMembersRow struct {
	ProjectID int64     `json:"project_id"`
	UserID    int64     `json:"user_id"`
	Role      string    `json:"role"`
	CreatedAt time.Time `json:"created_at"`
	UserName  string    `json:"user_name"`
	UserEmail string    `json:"user_email"`
}

func (q *Queries) ListProjectMembers(ctx context.Context, projectID int64) ([]ListProjectMembersRow, error) {
	rows, err := q.db.Query(ctx, listProjectMembers, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProjectMembersRow{}
	for rows.Next() {
		var i ListProjectMembersRow
		if err := rows.Scan(
			&i.ProjectID,
			&i.UserID,
			&i.Role,
			&i.CreatedAt,
			&i.UserName,
			&i.UserEmail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertProjectMember = `-- name: UpsertProjectMember :exec
INSERT INTO project_members (project_id, user_id, role)
VALUES ($1, $2, $3)
ON CONFLICT (project_id, user_id) DO UPDATE SET role = EXCLUDED.role
`

type UpsertProjectMemberParams struct {
	ProjectID int64  `json:"project_id"`
	UserID    int64  `json:"user_id"`
	Role      string `json:"role"`
}

func (q *Queries) UpsertProjectMember(ctx context.Context, arg UpsertProjectMemberParams) error {
	_, err := q.db.Exec(ctx, upsertProjectMember, arg.ProjectID, arg.UserID, arg.Role)
	return err
}
