// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: releases.sql

package db

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const createRelease = `-- name: CreateRelease :one
INSERT INTO releases (name, version, status, target_date, notes, created_by)
VALUES ($1, $2, $3,
        $4, $5, $6)
RETURNING id, name, version, status, target_date, notes, created_at, updated_at
`

type CreateReleaseParams struct {
	Name       string      `json:"name"`
	Version    string      `json:"version"`
	Status     string      `json:"status"`
	TargetDate pgtype.Date `json:"target_date"`
	Notes      string      `json:"notes"`
	CreatedBy  *int64      `json:"created_by"`
}

type CreateReleaseRow struct {
	ID         int64       `json:"id"`
	Name       string      `json:"name"`
	Version    string      `json:"version"`
	Status     string      `json:"status"`
	TargetDate pgtype.Date `json:"target_date"`
	Notes      string      `json:"notes"`
	CreatedAt  time.Time   `json:"created_at"`
	UpdatedAt  time.Time   `json:"updated_at"`
}

func (q *Queries) CreateRelease(ctx context.Context, arg CreateReleaseParams) (CreateReleaseRow, error) {
	row := q.db.QueryRow(ctx, createRelease,
		arg.Name,
		arg.Version,
		arg.Status,
		arg.TargetDate,
		arg.Notes,
		arg.CreatedBy,
	)
	var i CreateReleaseRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Version,
		&i.Status,
		&i.TargetDate,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteRelease = `-- name: DeleteRelease :exec
DELETE FROM releases WHERE id = $1
`

func (q *Queries) DeleteRelease(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteRelease, id)
	return err
}

const listReleases = `-- name: ListReleases :many
SELECT id, name, version, status, target_date, notes, created_at, updated_at
FROM releases
ORDER BY target_date NULLS LAST, created_at
`

type ListReleasesRow struct {
	ID         int64       `json:"id"`
	Name       string      `json:"name"`
	Version    string      `json:"version"`
	Status     string      `json:"status"`
	TargetDate pgtype.Date `json:"target_date"`
	Notes      string      `json:"notes"`
	CreatedAt  time.Time   `json:"created_at"`
	UpdatedAt  time.Time   `json:"updated_at"`
}

func (q *Queries) ListReleases(ctx context.Context) ([]ListReleasesRow, error) {
	rows, err := q.db.Query(ctx, listReleases)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListReleasesRow{}
	for rows.Next() {
		var i ListReleasesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Version,
			&i.Status,
			&i.TargetDate,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRelease = `-- name: UpdateRelease :exec
UPDATE releases
SET name = $1, version = $2,
    status = $3, target_date = $4,
    notes = $5, updated_at = now()
WHERE id = $6
`

type UpdateReleaseParams struct {
	Name       string      `json:"name"`
	Version    string      `json:"version"`
	Status     string      `json:"status"`
	TargetDate pgtype.Date `json:"target_date"`
	Notes      string      `json:"notes"`
	ID         int64       `json:"id"`
}

func (q *Queries) UpdateRelease(ctx context.Context, arg UpdateReleaseParams) error {
	_, err := q.db.Exec(ctx, updateRelease,
		arg.Name,
		arg.Version,
		arg.Status,
		arg.TargetDate,
		arg.Notes,
		arg.ID,
	)
	return err
}
