// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: resources.sql

package db

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAvailability = `-- name: CreateAvailability :one
INSERT INTO availability (user_id, start_date, end_date, kind, note, created_by)
VALUES ($1, $2, $3,
        $4, $5, $6)
RETURNING id
`

type CreateAvailabilityParams struct {
	UserID    int64       `json:"user_id"`
	StartDate pgtype.Date `json:"start_date"`
	EndDate   pgtype.Date `json:"end_date"`
	Kind      string      `json:"kind"`
	Note      string      `json:"note"`
	CreatedBy *int64      `json:"created_by"`
}

func (q *Queries) CreateAvailability(ctx context.Context, arg CreateAvailabilityParams) (int64, error) {
	row := q.db.QueryRow(ctx, createAvailability,
		arg.UserID,
		arg.StartDate,
		arg.EndDate,
		arg.Kind,
		arg.Note,
		arg.CreatedBy,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const deleteAvailability = `-- name: DeleteAvailability :exec
DELETE FROM availability WHERE id = $1
`

func (q *Queries) DeleteAvailability(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteAvailability, id)
	return err
}

const listAvailability = `-- name: ListAvailability :many
SELECT a.id, a.user_id, a.start_date, a.end_date, a.kind, a.note,
       a.created_at,
       COALESCE(u.full_name, '')::text AS user_name
FROM availability a
JOIN users u ON u.id = a.user_id
ORDER BY a.start_date DESC, a.id DESC
`

type ListAvailabilityRow struct {
	ID        int64       `json:"id"`
	UserID    int64       `json:"user_id"`
	StartDate pgtype.Date `json:"start_date"`
	EndDate   pgtype.Date `json:"end_date"`
	Kind      string      `json:"kind"`
	Note      string      `json:"note"`
	CreatedAt time.Time   `json:"created_at"`
	UserName  string      `json:"user_name"`
}

func (q *Queries) ListAvailability(ctx context.Context) ([]ListAvailabilityRow, error) {
	rows, err := q.db.Query(ctx, listAvailability)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAvailabilityRow{}
	for rows.Next() {
		var i ListAvailabilityRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.StartDate,
			&i.EndDate,
			&i.Kind,
			&i.Note,
			&i.CreatedAt,
			&i.UserName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCapacity = `-- name: ListCapacity :many
SELECT u.id AS user_id,
       u.full_name,
       u.email,
       COALESCE(mc.weekly_hours, 40)::int AS weekly_hours
FROM users u
LEFT JOIN member_capacity mc ON mc.user_id = u.id
ORDER BY u.full_name, u.email
`

type ListCapacityRow struct {
	UserID      int64  `json:"user_id"`
	FullName    string `json:"full_name"`
	Email       string `json:"email"`
	WeeklyHours int32  `json:"weekly_hours"`
}

func (q *Queries) ListCapacity(ctx context.Context) ([]ListCapacityRow, error) {
	rows, err := q.db.Query(ctx, listCapacity)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCapacityRow{}
	for rows.Next() {
		var i ListCapacityRow
		if err := rows.Scan(
			&i.UserID,
			&i.FullName,
			&i.Email,
			&i.WeeklyHours,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setCapacity = `-- name: SetCapacity :exec
INSERT INTO member_capacity (user_id, weekly_hours)
VALUES ($1, $2)
ON CONFLICT (user_id)
DO UPDATE SET weekly_hours = $2, updated_at = now()
`

type SetCapacityParams struct {
	UserID      int64 `json:"user_id"`
	WeeklyHours int32 `json:"weekly_hours"`
}

func (q *Queries) SetCapacity(ctx context.Context, arg SetCapacityParams) error {
	_, err := q.db.Exec(ctx, setCapacity, arg.UserID, arg.WeeklyHours)
	return err
}
