// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: retro.sql

package db

import (
	"context"
	"time"
)

const addRetroItem = `-- name: AddRetroItem :one
INSERT INTO retro_items (sprint_id, author_id, kind, body)
VALUES ($1, $2, $3,
        $4)
RETURNING id, sprint_id, kind, body, author_id, done, created_at
`

type AddRetroItemParams struct {
	SprintID int64  `json:"sprint_id"`
	AuthorID *int64 `json:"author_id"`
	Kind     string `json:"kind"`
	Body     string `json:"body"`
}

func (q *Queries) AddRetroItem(ctx context.Context, arg AddRetroItemParams) (RetroItem, error) {
	row := q.db.QueryRow(ctx, addRetroItem,
		arg.SprintID,
		arg.AuthorID,
		arg.Kind,
		arg.Body,
	)
	var i RetroItem
	err := row.Scan(
		&i.ID,
		&i.SprintID,
		&i.Kind,
		&i.Body,
		&i.AuthorID,
		&i.Done,
		&i.CreatedAt,
	)
	return i, err
}

const deleteRetroItem = `-- name: DeleteRetroItem :exec
DELETE FROM retro_items WHERE id = $1
`

func (q *Queries) DeleteRetroItem(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteRetroItem, id)
	return err
}

const listRetroItems = `-- name: ListRetroItems :many
SELECT r.id, r.sprint_id, r.kind, r.body, r.author_id, r.done, r.created_at, COALESCE(u.full_name, '')::text AS author_name
FROM retro_items r
LEFT JOIN users u ON u.id = r.author_id
WHERE r.sprint_id = $1
ORDER BY r.created_at
`

type ListRetroItemsRow struct {
	ID         int64     `json:"id"`
	SprintID   int64     `json:"sprint_id"`
	Kind       string    `json:"kind"`
	Body       string    `json:"body"`
	AuthorID   *int64    `json:"author_id"`
	Done       bool      `json:"done"`
	CreatedAt  time.Time `json:"created_at"`
	AuthorName string    `json:"author_name"`
}

func (q *Queries) ListRetroItems(ctx context.Context, sprintID int64) ([]ListRetroItemsRow, error) {
	rows, err := q.db.Query(ctx, listRetroItems, sprintID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRetroItemsRow{}
	for rows.Next() {
		var i ListRetroItemsRow
		if err := rows.Scan(
			&i.ID,
			&i.SprintID,
			&i.Kind,
			&i.Body,
			&i.AuthorID,
			&i.Done,
			&i.CreatedAt,
			&i.AuthorName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setRetroDone = `-- name: SetRetroDone :exec
UPDATE retro_items SET done = $1 WHERE id = $2
`

type SetRetroDoneParams struct {
	Done bool  `json:"done"`
	ID   int64 `json:"id"`
}

func (q *Queries) SetRetroDone(ctx context.Context, arg SetRetroDoneParams) error {
	_, err := q.db.Exec(ctx, setRetroDone, arg.Done, arg.ID)
	return err
}
