// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: saved_reports.sql

package db

import (
	"context"
)

const createSavedReport = `-- name: CreateSavedReport :one
INSERT INTO saved_reports (name, config, created_by)
VALUES ($1, $2, $3)
RETURNING id, name, config, created_by, created_at
`

type CreateSavedReportParams struct {
	Name      string `json:"name"`
	Config    string `json:"config"`
	CreatedBy *int64 `json:"created_by"`
}

func (q *Queries) CreateSavedReport(ctx context.Context, arg CreateSavedReportParams) (SavedReport, error) {
	row := q.db.QueryRow(ctx, createSavedReport, arg.Name, arg.Config, arg.CreatedBy)
	var i SavedReport
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Config,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const deleteSavedReport = `-- name: DeleteSavedReport :exec
DELETE FROM saved_reports WHERE id = $1
`

func (q *Queries) DeleteSavedReport(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteSavedReport, id)
	return err
}

const listSavedReports = `-- name: ListSavedReports :many
SELECT id, name, config, created_by, created_at FROM saved_reports ORDER BY name, id
`

func (q *Queries) ListSavedReports(ctx context.Context) ([]SavedReport, error) {
	rows, err := q.db.Query(ctx, listSavedReports)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SavedReport{}
	for rows.Next() {
		var i SavedReport
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Config,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSavedReport = `-- name: UpdateSavedReport :one
UPDATE saved_reports
SET name = $1, config = $2
WHERE id = $3
RETURNING id, name, config, created_by, created_at
`

type UpdateSavedReportParams struct {
	Name   string `json:"name"`
	Config string `json:"config"`
	ID     int64  `json:"id"`
}

func (q *Queries) UpdateSavedReport(ctx context.Context, arg UpdateSavedReportParams) (SavedReport, error) {
	row := q.db.QueryRow(ctx, updateSavedReport, arg.Name, arg.Config, arg.ID)
	var i SavedReport
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Config,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}
