// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: search.sql

package db

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const searchProjects = `-- name: SearchProjects :many
SELECT id, name, status, due_date
FROM projects
WHERE name ILIKE '%' || $1 || '%'
   OR description ILIKE '%' || $1 || '%'
ORDER BY created_at DESC
LIMIT $2
`

type SearchProjectsParams struct {
	Query *string `json:"query"`
	Lim   int32   `json:"lim"`
}

type SearchProjectsRow struct {
	ID      int64              `json:"id"`
	Name    string             `json:"name"`
	Status  string             `json:"status"`
	DueDate pgtype.Timestamptz `json:"due_date"`
}

func (q *Queries) SearchProjects(ctx context.Context, arg SearchProjectsParams) ([]SearchProjectsRow, error) {
	rows, err := q.db.Query(ctx, searchProjects, arg.Query, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchProjectsRow{}
	for rows.Next() {
		var i SearchProjectsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Status,
			&i.DueDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchTasks = `-- name: SearchTasks :many
SELECT t.id, t.title, t.description, t.done, t.created_at, t.updated_at, t.project_id, t.assignee_id, t.start_date, t.due_date, t.status, t.parent_id, t.recurrence, t.baseline_start, t.baseline_due, t.priority, t.tags, t.reminder_sent, t.estimate_minutes, t.sprint_id, t.points, t.issue_type, t.severity, t.release_id,
       p.name      AS project_name,
       u.full_name AS assignee_name,
       COALESCE(st.total, 0)::int AS subtask_count,
       COALESCE(st.done, 0)::int  AS subtask_done_count
FROM tasks t
LEFT JOIN projects p ON p.id = t.project_id
LEFT JOIN users u ON u.id = t.assignee_id
LEFT JOIN (
    SELECT parent_id,
           COUNT(*)                     AS total,
           COUNT(*) FILTER (WHERE done) AS done
    FROM tasks
    WHERE parent_id IS NOT NULL
    GROUP BY parent_id
) st ON st.parent_id = t.id
WHERE t.parent_id IS NULL
  AND (
        t.title ILIKE '%' || $1 || '%'
     OR t.description ILIKE '%' || $1 || '%'
     OR p.name ILIKE '%' || $1 || '%'
     OR EXISTS (
          SELECT 1 FROM unnest(t.tags) tg
          WHERE tg ILIKE '%' || $1 || '%'
        )
  )
ORDER BY t.created_at DESC
LIMIT $3 OFFSET $2
`

type SearchTasksParams struct {
	Query *string `json:"query"`
	Off   int32   `json:"off"`
	Lim   int32   `json:"lim"`
}

type SearchTasksRow struct {
	ID               int64              `json:"id"`
	Title            string             `json:"title"`
	Description      string             `json:"description"`
	Done             bool               `json:"done"`
	CreatedAt        time.Time          `json:"created_at"`
	UpdatedAt        time.Time          `json:"updated_at"`
	ProjectID        *int64             `json:"project_id"`
	AssigneeID       *int64             `json:"assignee_id"`
	StartDate        pgtype.Timestamptz `json:"start_date"`
	DueDate          pgtype.Timestamptz `json:"due_date"`
	Status           string             `json:"status"`
	ParentID         *int64             `json:"parent_id"`
	Recurrence       string             `json:"recurrence"`
	BaselineStart    pgtype.Timestamptz `json:"baseline_start"`
	BaselineDue      pgtype.Timestamptz `json:"baseline_due"`
	Priority         string             `json:"priority"`
	Tags             []string           `json:"tags"`
	ReminderSent     bool               `json:"reminder_sent"`
	EstimateMinutes  int32              `json:"estimate_minutes"`
	SprintID         *int64             `json:"sprint_id"`
	Points           int32              `json:"points"`
	IssueType        string             `json:"issue_type"`
	Severity         string             `json:"severity"`
	ReleaseID        *int64             `json:"release_id"`
	ProjectName      *string            `json:"project_name"`
	AssigneeName     *string            `json:"assignee_name"`
	SubtaskCount     int32              `json:"subtask_count"`
	SubtaskDoneCount int32              `json:"subtask_done_count"`
}

// Full-text-ish search across top-level tasks: title, description, project
// name and tags. Paginated with limit/offset.
func (q *Queries) SearchTasks(ctx context.Context, arg SearchTasksParams) ([]SearchTasksRow, error) {
	rows, err := q.db.Query(ctx, searchTasks, arg.Query, arg.Off, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchTasksRow{}
	for rows.Next() {
		var i SearchTasksRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.Done,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ProjectID,
			&i.AssigneeID,
			&i.StartDate,
			&i.DueDate,
			&i.Status,
			&i.ParentID,
			&i.Recurrence,
			&i.BaselineStart,
			&i.BaselineDue,
			&i.Priority,
			&i.Tags,
			&i.ReminderSent,
			&i.EstimateMinutes,
			&i.SprintID,
			&i.Points,
			&i.IssueType,
			&i.Severity,
			&i.ReleaseID,
			&i.ProjectName,
			&i.AssigneeName,
			&i.SubtaskCount,
			&i.SubtaskDoneCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
