// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: skills.sql

package db

import (
	"context"
)

const deleteSkill = `-- name: DeleteSkill :exec
DELETE FROM user_skills WHERE id = $1 AND user_id = $2
`

type DeleteSkillParams struct {
	ID     int64 `json:"id"`
	UserID int64 `json:"user_id"`
}

func (q *Queries) DeleteSkill(ctx context.Context, arg DeleteSkillParams) error {
	_, err := q.db.Exec(ctx, deleteSkill, arg.ID, arg.UserID)
	return err
}

const listAllSkills = `-- name: ListAllSkills :many
SELECT s.id, s.user_id, s.skill, s.level,
       u.full_name AS user_name, u.avatar
FROM user_skills s
JOIN users u ON u.id = s.user_id
ORDER BY u.full_name, s.skill
`

type ListAllSkillsRow struct {
	ID       int64  `json:"id"`
	UserID   int64  `json:"user_id"`
	Skill    string `json:"skill"`
	Level    int32  `json:"level"`
	UserName string `json:"user_name"`
	Avatar   string `json:"avatar"`
}

func (q *Queries) ListAllSkills(ctx context.Context) ([]ListAllSkillsRow, error) {
	rows, err := q.db.Query(ctx, listAllSkills)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAllSkillsRow{}
	for rows.Next() {
		var i ListAllSkillsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Skill,
			&i.Level,
			&i.UserName,
			&i.Avatar,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMySkills = `-- name: ListMySkills :many
SELECT id, user_id, skill, level, created_at FROM user_skills WHERE user_id = $1 ORDER BY skill
`

func (q *Queries) ListMySkills(ctx context.Context, userID int64) ([]UserSkill, error) {
	rows, err := q.db.Query(ctx, listMySkills, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UserSkill{}
	for rows.Next() {
		var i UserSkill
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Skill,
			&i.Level,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertSkill = `-- name: UpsertSkill :one
INSERT INTO user_skills (user_id, skill, level)
VALUES ($1, $2, $3)
ON CONFLICT (user_id, skill) DO UPDATE
    SET level = EXCLUDED.level
RETURNING id, user_id, skill, level, created_at
`

type UpsertSkillParams struct {
	UserID int64  `json:"user_id"`
	Skill  string `json:"skill"`
	Level  int32  `json:"level"`
}

func (q *Queries) UpsertSkill(ctx context.Context, arg UpsertSkillParams) (UserSkill, error) {
	row := q.db.QueryRow(ctx, upsertSkill, arg.UserID, arg.Skill, arg.Level)
	var i UserSkill
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Skill,
		&i.Level,
		&i.CreatedAt,
	)
	return i, err
}
