// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: spaces.sql

package db

import (
	"context"
)

const createFolder = `-- name: CreateFolder :one
INSERT INTO folders (space_id, name, position)
VALUES ($1, $2, $3)
RETURNING id, space_id, name, position, created_at
`

type CreateFolderParams struct {
	SpaceID  int64  `json:"space_id"`
	Name     string `json:"name"`
	Position int32  `json:"position"`
}

func (q *Queries) CreateFolder(ctx context.Context, arg CreateFolderParams) (Folder, error) {
	row := q.db.QueryRow(ctx, createFolder, arg.SpaceID, arg.Name, arg.Position)
	var i Folder
	err := row.Scan(
		&i.ID,
		&i.SpaceID,
		&i.Name,
		&i.Position,
		&i.CreatedAt,
	)
	return i, err
}

const createSpace = `-- name: CreateSpace :one
INSERT INTO spaces (name, color, position, created_by)
VALUES ($1, $2, $3, $4)
RETURNING id, name, color, position, created_by, created_at
`

type CreateSpaceParams struct {
	Name      string `json:"name"`
	Color     string `json:"color"`
	Position  int32  `json:"position"`
	CreatedBy *int64 `json:"created_by"`
}

func (q *Queries) CreateSpace(ctx context.Context, arg CreateSpaceParams) (Space, error) {
	row := q.db.QueryRow(ctx, createSpace,
		arg.Name,
		arg.Color,
		arg.Position,
		arg.CreatedBy,
	)
	var i Space
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Color,
		&i.Position,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const deleteFolder = `-- name: DeleteFolder :exec
DELETE FROM folders WHERE id = $1
`

func (q *Queries) DeleteFolder(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteFolder, id)
	return err
}

const deleteSpace = `-- name: DeleteSpace :exec
DELETE FROM spaces WHERE id = $1
`

func (q *Queries) DeleteSpace(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteSpace, id)
	return err
}

const listFolders = `-- name: ListFolders :many
SELECT id, space_id, name, position, created_at FROM folders ORDER BY position, id
`

func (q *Queries) ListFolders(ctx context.Context) ([]Folder, error) {
	rows, err := q.db.Query(ctx, listFolders)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Folder{}
	for rows.Next() {
		var i Folder
		if err := rows.Scan(
			&i.ID,
			&i.SpaceID,
			&i.Name,
			&i.Position,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSpaces = `-- name: ListSpaces :many
SELECT id, name, color, position, created_by, created_at FROM spaces ORDER BY position, id
`

func (q *Queries) ListSpaces(ctx context.Context) ([]Space, error) {
	rows, err := q.db.Query(ctx, listSpaces)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Space{}
	for rows.Next() {
		var i Space
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Color,
			&i.Position,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const maxFolderPosition = `-- name: MaxFolderPosition :one
SELECT COALESCE(MAX(position), -1)::int FROM folders WHERE space_id = $1
`

func (q *Queries) MaxFolderPosition(ctx context.Context, spaceID int64) (int32, error) {
	row := q.db.QueryRow(ctx, maxFolderPosition, spaceID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const maxSpacePosition = `-- name: MaxSpacePosition :one
SELECT COALESCE(MAX(position), -1)::int FROM spaces
`

func (q *Queries) MaxSpacePosition(ctx context.Context) (int32, error) {
	row := q.db.QueryRow(ctx, maxSpacePosition)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const updateFolder = `-- name: UpdateFolder :one
UPDATE folders SET name = $2 WHERE id = $1 RETURNING id, space_id, name, position, created_at
`

type UpdateFolderParams struct {
	ID   int64  `json:"id"`
	Name string `json:"name"`
}

func (q *Queries) UpdateFolder(ctx context.Context, arg UpdateFolderParams) (Folder, error) {
	row := q.db.QueryRow(ctx, updateFolder, arg.ID, arg.Name)
	var i Folder
	err := row.Scan(
		&i.ID,
		&i.SpaceID,
		&i.Name,
		&i.Position,
		&i.CreatedAt,
	)
	return i, err
}

const updateSpace = `-- name: UpdateSpace :one
UPDATE spaces SET name = $2, color = $3 WHERE id = $1 RETURNING id, name, color, position, created_by, created_at
`

type UpdateSpaceParams struct {
	ID    int64  `json:"id"`
	Name  string `json:"name"`
	Color string `json:"color"`
}

func (q *Queries) UpdateSpace(ctx context.Context, arg UpdateSpaceParams) (Space, error) {
	row := q.db.QueryRow(ctx, updateSpace, arg.ID, arg.Name, arg.Color)
	var i Space
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Color,
		&i.Position,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}
