// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sprints.sql

package db

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSprint = `-- name: CreateSprint :one
INSERT INTO sprints (name, goal, status, start_date, end_date, created_by)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, name, goal, status, start_date, end_date, created_by, created_at
`

type CreateSprintParams struct {
	Name      string             `json:"name"`
	Goal      string             `json:"goal"`
	Status    string             `json:"status"`
	StartDate pgtype.Timestamptz `json:"start_date"`
	EndDate   pgtype.Timestamptz `json:"end_date"`
	CreatedBy *int64             `json:"created_by"`
}

func (q *Queries) CreateSprint(ctx context.Context, arg CreateSprintParams) (Sprint, error) {
	row := q.db.QueryRow(ctx, createSprint,
		arg.Name,
		arg.Goal,
		arg.Status,
		arg.StartDate,
		arg.EndDate,
		arg.CreatedBy,
	)
	var i Sprint
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Goal,
		&i.Status,
		&i.StartDate,
		&i.EndDate,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const deleteSprint = `-- name: DeleteSprint :exec
DELETE FROM sprints WHERE id = $1
`

func (q *Queries) DeleteSprint(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteSprint, id)
	return err
}

const getSprint = `-- name: GetSprint :one
SELECT id, name, goal, status, start_date, end_date, created_by, created_at FROM sprints WHERE id = $1
`

func (q *Queries) GetSprint(ctx context.Context, id int64) (Sprint, error) {
	row := q.db.QueryRow(ctx, getSprint, id)
	var i Sprint
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Goal,
		&i.Status,
		&i.StartDate,
		&i.EndDate,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const listSprints = `-- name: ListSprints :many
SELECT s.id, s.name, s.goal, s.status, s.start_date, s.end_date, s.created_by, s.created_at,
       COALESCE(t.task_count, 0)::int   AS task_count,
       COALESCE(t.done_count, 0)::int   AS done_count,
       COALESCE(t.total_points, 0)::int AS total_points,
       COALESCE(t.done_points, 0)::int  AS done_points
FROM sprints s
LEFT JOIN (
    SELECT sprint_id,
           COUNT(*)                          AS task_count,
           COUNT(*) FILTER (WHERE done)      AS done_count,
           SUM(points)                       AS total_points,
           SUM(points) FILTER (WHERE done)   AS done_points
    FROM tasks
    WHERE sprint_id IS NOT NULL
    GROUP BY sprint_id
) t ON t.sprint_id = s.id
ORDER BY s.created_at DESC
`

type ListSprintsRow struct {
	ID          int64              `json:"id"`
	Name        string             `json:"name"`
	Goal        string             `json:"goal"`
	Status      string             `json:"status"`
	StartDate   pgtype.Timestamptz `json:"start_date"`
	EndDate     pgtype.Timestamptz `json:"end_date"`
	CreatedBy   *int64             `json:"created_by"`
	CreatedAt   time.Time          `json:"created_at"`
	TaskCount   int32              `json:"task_count"`
	DoneCount   int32              `json:"done_count"`
	TotalPoints int32              `json:"total_points"`
	DonePoints  int32              `json:"done_points"`
}

func (q *Queries) ListSprints(ctx context.Context) ([]ListSprintsRow, error) {
	rows, err := q.db.Query(ctx, listSprints)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSprintsRow{}
	for rows.Next() {
		var i ListSprintsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Goal,
			&i.Status,
			&i.StartDate,
			&i.EndDate,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.TaskCount,
			&i.DoneCount,
			&i.TotalPoints,
			&i.DonePoints,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const moveSprintTasksToBacklog = `-- name: MoveSprintTasksToBacklog :exec
UPDATE tasks
SET sprint_id = NULL, updated_at = now()
WHERE sprint_id = $1 AND NOT done
`

func (q *Queries) MoveSprintTasksToBacklog(ctx context.Context, sprintID *int64) error {
	_, err := q.db.Exec(ctx, moveSprintTasksToBacklog, sprintID)
	return err
}

const setSprintStatus = `-- name: SetSprintStatus :one
UPDATE sprints SET status = $2 WHERE id = $1 RETURNING id, name, goal, status, start_date, end_date, created_by, created_at
`

type SetSprintStatusParams struct {
	ID     int64  `json:"id"`
	Status string `json:"status"`
}

func (q *Queries) SetSprintStatus(ctx context.Context, arg SetSprintStatusParams) (Sprint, error) {
	row := q.db.QueryRow(ctx, setSprintStatus, arg.ID, arg.Status)
	var i Sprint
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Goal,
		&i.Status,
		&i.StartDate,
		&i.EndDate,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const updateSprint = `-- name: UpdateSprint :one
UPDATE sprints
SET name = $2, goal = $3, start_date = $4, end_date = $5
WHERE id = $1
RETURNING id, name, goal, status, start_date, end_date, created_by, created_at
`

type UpdateSprintParams struct {
	ID        int64              `json:"id"`
	Name      string             `json:"name"`
	Goal      string             `json:"goal"`
	StartDate pgtype.Timestamptz `json:"start_date"`
	EndDate   pgtype.Timestamptz `json:"end_date"`
}

func (q *Queries) UpdateSprint(ctx context.Context, arg UpdateSprintParams) (Sprint, error) {
	row := q.db.QueryRow(ctx, updateSprint,
		arg.ID,
		arg.Name,
		arg.Goal,
		arg.StartDate,
		arg.EndDate,
	)
	var i Sprint
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Goal,
		&i.Status,
		&i.StartDate,
		&i.EndDate,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}
