// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: statuses.sql

package db

import (
	"context"
)

const countTasksWithStatus = `-- name: CountTasksWithStatus :one
SELECT COUNT(*) FROM tasks WHERE status = $1
`

func (q *Queries) CountTasksWithStatus(ctx context.Context, status string) (int64, error) {
	row := q.db.QueryRow(ctx, countTasksWithStatus, status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createStatus = `-- name: CreateStatus :one
INSERT INTO task_statuses (key, label, color, position)
VALUES ($1, $2, $3, $4)
RETURNING id, key, label, color, position, protected
`

type CreateStatusParams struct {
	Key      string `json:"key"`
	Label    string `json:"label"`
	Color    string `json:"color"`
	Position int32  `json:"position"`
}

func (q *Queries) CreateStatus(ctx context.Context, arg CreateStatusParams) (TaskStatus, error) {
	row := q.db.QueryRow(ctx, createStatus,
		arg.Key,
		arg.Label,
		arg.Color,
		arg.Position,
	)
	var i TaskStatus
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.Label,
		&i.Color,
		&i.Position,
		&i.Protected,
	)
	return i, err
}

const deleteStatus = `-- name: DeleteStatus :exec
DELETE FROM task_statuses WHERE id = $1 AND NOT protected
`

func (q *Queries) DeleteStatus(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteStatus, id)
	return err
}

const getStatus = `-- name: GetStatus :one
SELECT id, key, label, color, position, protected FROM task_statuses WHERE id = $1
`

func (q *Queries) GetStatus(ctx context.Context, id int64) (TaskStatus, error) {
	row := q.db.QueryRow(ctx, getStatus, id)
	var i TaskStatus
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.Label,
		&i.Color,
		&i.Position,
		&i.Protected,
	)
	return i, err
}

const listStatuses = `-- name: ListStatuses :many
SELECT id, key, label, color, position, protected FROM task_statuses ORDER BY position, id
`

func (q *Queries) ListStatuses(ctx context.Context) ([]TaskStatus, error) {
	rows, err := q.db.Query(ctx, listStatuses)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TaskStatus{}
	for rows.Next() {
		var i TaskStatus
		if err := rows.Scan(
			&i.ID,
			&i.Key,
			&i.Label,
			&i.Color,
			&i.Position,
			&i.Protected,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const maxStatusPosition = `-- name: MaxStatusPosition :one
SELECT COALESCE(MAX(position), -1)::int FROM task_statuses
`

func (q *Queries) MaxStatusPosition(ctx context.Context) (int32, error) {
	row := q.db.QueryRow(ctx, maxStatusPosition)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const setStatusPosition = `-- name: SetStatusPosition :exec
UPDATE task_statuses SET position = $2 WHERE id = $1
`

type SetStatusPositionParams struct {
	ID       int64 `json:"id"`
	Position int32 `json:"position"`
}

func (q *Queries) SetStatusPosition(ctx context.Context, arg SetStatusPositionParams) error {
	_, err := q.db.Exec(ctx, setStatusPosition, arg.ID, arg.Position)
	return err
}

const statusKeyExists = `-- name: StatusKeyExists :one
SELECT EXISTS (SELECT 1 FROM task_statuses WHERE key = $1)
`

func (q *Queries) StatusKeyExists(ctx context.Context, key string) (bool, error) {
	row := q.db.QueryRow(ctx, statusKeyExists, key)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const updateStatus = `-- name: UpdateStatus :one
UPDATE task_statuses
SET label = $2, color = $3, position = $4
WHERE id = $1
RETURNING id, key, label, color, position, protected
`

type UpdateStatusParams struct {
	ID       int64  `json:"id"`
	Label    string `json:"label"`
	Color    string `json:"color"`
	Position int32  `json:"position"`
}

func (q *Queries) UpdateStatus(ctx context.Context, arg UpdateStatusParams) (TaskStatus, error) {
	row := q.db.QueryRow(ctx, updateStatus,
		arg.ID,
		arg.Label,
		arg.Color,
		arg.Position,
	)
	var i TaskStatus
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.Label,
		&i.Color,
		&i.Position,
		&i.Protected,
	)
	return i, err
}
