// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tasks.sql

package db

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const addTaskAssignee = `-- name: AddTaskAssignee :exec
INSERT INTO task_assignees (task_id, user_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type AddTaskAssigneeParams struct {
	TaskID int64 `json:"task_id"`
	UserID int64 `json:"user_id"`
}

func (q *Queries) AddTaskAssignee(ctx context.Context, arg AddTaskAssigneeParams) error {
	_, err := q.db.Exec(ctx, addTaskAssignee, arg.TaskID, arg.UserID)
	return err
}

const bulkDeleteTasks = `-- name: BulkDeleteTasks :exec
DELETE FROM tasks
WHERE id = ANY($1::bigint[])
`

func (q *Queries) BulkDeleteTasks(ctx context.Context, ids []int64) error {
	_, err := q.db.Exec(ctx, bulkDeleteTasks, ids)
	return err
}

const bulkSetTaskAssignee = `-- name: BulkSetTaskAssignee :exec
UPDATE tasks
SET assignee_id = $1,
    updated_at = now()
WHERE id = ANY($2::bigint[])
`

type BulkSetTaskAssigneeParams struct {
	Assignee *int64  `json:"assignee"`
	Ids      []int64 `json:"ids"`
}

func (q *Queries) BulkSetTaskAssignee(ctx context.Context, arg BulkSetTaskAssigneeParams) error {
	_, err := q.db.Exec(ctx, bulkSetTaskAssignee, arg.Assignee, arg.Ids)
	return err
}

const bulkSetTaskDone = `-- name: BulkSetTaskDone :exec
UPDATE tasks
SET done = $1,
    status = CASE WHEN $1 THEN 'done' ELSE 'todo' END,
    reminder_sent = CASE WHEN $1 THEN reminder_sent ELSE FALSE END,
    updated_at = now()
WHERE id = ANY($2::bigint[])
`

type BulkSetTaskDoneParams struct {
	Done bool    `json:"done"`
	Ids  []int64 `json:"ids"`
}

func (q *Queries) BulkSetTaskDone(ctx context.Context, arg BulkSetTaskDoneParams) error {
	_, err := q.db.Exec(ctx, bulkSetTaskDone, arg.Done, arg.Ids)
	return err
}

const bulkSetTaskPriority = `-- name: BulkSetTaskPriority :exec
UPDATE tasks
SET priority = $1,
    updated_at = now()
WHERE id = ANY($2::bigint[])
`

type BulkSetTaskPriorityParams struct {
	Priority string  `json:"priority"`
	Ids      []int64 `json:"ids"`
}

func (q *Queries) BulkSetTaskPriority(ctx context.Context, arg BulkSetTaskPriorityParams) error {
	_, err := q.db.Exec(ctx, bulkSetTaskPriority, arg.Priority, arg.Ids)
	return err
}

const bulkSetTaskStatus = `-- name: BulkSetTaskStatus :exec
UPDATE tasks
SET status = $1,
    done   = ($1 = 'done'),
    updated_at = now()
WHERE id = ANY($2::bigint[])
`

type BulkSetTaskStatusParams struct {
	Status string  `json:"status"`
	Ids    []int64 `json:"ids"`
}

func (q *Queries) BulkSetTaskStatus(ctx context.Context, arg BulkSetTaskStatusParams) error {
	_, err := q.db.Exec(ctx, bulkSetTaskStatus, arg.Status, arg.Ids)
	return err
}

const clearTaskAssignees = `-- name: ClearTaskAssignees :exec
DELETE FROM task_assignees WHERE task_id = $1
`

func (q *Queries) ClearTaskAssignees(ctx context.Context, taskID int64) error {
	_, err := q.db.Exec(ctx, clearTaskAssignees, taskID)
	return err
}

const createTask = `-- name: CreateTask :one
INSERT INTO tasks (title, description, project_id, assignee_id, start_date, due_date, status, parent_id, recurrence, priority, tags, estimate_minutes)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
RETURNING id, title, description, done, created_at, updated_at, project_id, assignee_id, start_date, due_date, status, parent_id, recurrence, baseline_start, baseline_due, priority, tags, reminder_sent, estimate_minutes
`

type CreateTaskParams struct {
	Title           string             `json:"title"`
	Description     string             `json:"description"`
	ProjectID       *int64             `json:"project_id"`
	AssigneeID      *int64             `json:"assignee_id"`
	StartDate       pgtype.Timestamptz `json:"start_date"`
	DueDate         pgtype.Timestamptz `json:"due_date"`
	Status          string             `json:"status"`
	ParentID        *int64             `json:"parent_id"`
	Recurrence      string             `json:"recurrence"`
	Priority        string             `json:"priority"`
	Tags            []string           `json:"tags"`
	EstimateMinutes int32              `json:"estimate_minutes"`
}

func (q *Queries) CreateTask(ctx context.Context, arg CreateTaskParams) (Task, error) {
	row := q.db.QueryRow(ctx, createTask,
		arg.Title,
		arg.Description,
		arg.ProjectID,
		arg.AssigneeID,
		arg.StartDate,
		arg.DueDate,
		arg.Status,
		arg.ParentID,
		arg.Recurrence,
		arg.Priority,
		arg.Tags,
		arg.EstimateMinutes,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Done,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ProjectID,
		&i.AssigneeID,
		&i.StartDate,
		&i.DueDate,
		&i.Status,
		&i.ParentID,
		&i.Recurrence,
		&i.BaselineStart,
		&i.BaselineDue,
		&i.Priority,
		&i.Tags,
		&i.ReminderSent,
		&i.EstimateMinutes,
	)
	return i, err
}

const deleteTask = `-- name: DeleteTask :exec
DELETE FROM tasks
WHERE id = $1
`

func (q *Queries) DeleteTask(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteTask, id)
	return err
}

const dueReminders = `-- name: DueReminders :many
SELECT id, title, assignee_id, due_date FROM tasks
WHERE NOT done
  AND assignee_id IS NOT NULL
  AND due_date IS NOT NULL
  AND due_date <= now() + INTERVAL '24 hours'
  AND NOT reminder_sent
`

type DueRemindersRow struct {
	ID         int64              `json:"id"`
	Title      string             `json:"title"`
	AssigneeID *int64             `json:"assignee_id"`
	DueDate    pgtype.Timestamptz `json:"due_date"`
}

func (q *Queries) DueReminders(ctx context.Context) ([]DueRemindersRow, error) {
	rows, err := q.db.Query(ctx, dueReminders)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DueRemindersRow{}
	for rows.Next() {
		var i DueRemindersRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.AssigneeID,
			&i.DueDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTask = `-- name: GetTask :one
SELECT id, title, description, done, created_at, updated_at, project_id, assignee_id, start_date, due_date, status, parent_id, recurrence, baseline_start, baseline_due, priority, tags, reminder_sent, estimate_minutes FROM tasks
WHERE id = $1
`

func (q *Queries) GetTask(ctx context.Context, id int64) (Task, error) {
	row := q.db.QueryRow(ctx, getTask, id)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Done,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ProjectID,
		&i.AssigneeID,
		&i.StartDate,
		&i.DueDate,
		&i.Status,
		&i.ParentID,
		&i.Recurrence,
		&i.BaselineStart,
		&i.BaselineDue,
		&i.Priority,
		&i.Tags,
		&i.ReminderSent,
		&i.EstimateMinutes,
	)
	return i, err
}

const listSubtasks = `-- name: ListSubtasks :many
SELECT id, title, description, done, created_at, updated_at, project_id, assignee_id, start_date, due_date, status, parent_id, recurrence, baseline_start, baseline_due, priority, tags, reminder_sent, estimate_minutes FROM tasks
WHERE parent_id = $1
ORDER BY created_at ASC
`

func (q *Queries) ListSubtasks(ctx context.Context, parentID *int64) ([]Task, error) {
	rows, err := q.db.Query(ctx, listSubtasks, parentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Task{}
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.Done,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ProjectID,
			&i.AssigneeID,
			&i.StartDate,
			&i.DueDate,
			&i.Status,
			&i.ParentID,
			&i.Recurrence,
			&i.BaselineStart,
			&i.BaselineDue,
			&i.Priority,
			&i.Tags,
			&i.ReminderSent,
			&i.EstimateMinutes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTaskAssignees = `-- name: ListTaskAssignees :many
SELECT ta.user_id, u.full_name
FROM task_assignees ta
JOIN users u ON u.id = ta.user_id
WHERE ta.task_id = $1
ORDER BY u.full_name
`

type ListTaskAssigneesRow struct {
	UserID   int64  `json:"user_id"`
	FullName string `json:"full_name"`
}

func (q *Queries) ListTaskAssignees(ctx context.Context, taskID int64) ([]ListTaskAssigneesRow, error) {
	rows, err := q.db.Query(ctx, listTaskAssignees, taskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTaskAssigneesRow{}
	for rows.Next() {
		var i ListTaskAssigneesRow
		if err := rows.Scan(&i.UserID, &i.FullName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTasks = `-- name: ListTasks :many
SELECT t.id, t.title, t.description, t.done, t.created_at, t.updated_at, t.project_id, t.assignee_id, t.start_date, t.due_date, t.status, t.parent_id, t.recurrence, t.baseline_start, t.baseline_due, t.priority, t.tags, t.reminder_sent, t.estimate_minutes,
       p.name      AS project_name,
       u.full_name AS assignee_name,
       COALESCE(st.total, 0)::int AS subtask_count,
       COALESCE(st.done, 0)::int  AS subtask_done_count,
       COALESCE(a.ids, ARRAY[]::bigint[])::bigint[] AS assignee_ids,
       COALESCE(a.names, ARRAY[]::text[])::text[]   AS assignee_names
FROM tasks t
LEFT JOIN projects p ON p.id = t.project_id
LEFT JOIN users u ON u.id = t.assignee_id
LEFT JOIN (
    SELECT parent_id,
           COUNT(*)                     AS total,
           COUNT(*) FILTER (WHERE done) AS done
    FROM tasks
    WHERE parent_id IS NOT NULL
    GROUP BY parent_id
) st ON st.parent_id = t.id
LEFT JOIN (
    SELECT ta.task_id,
           array_agg(ta.user_id ORDER BY au.full_name) AS ids,
           array_agg(au.full_name ORDER BY au.full_name) AS names
    FROM task_assignees ta
    JOIN users au ON au.id = ta.user_id
    GROUP BY ta.task_id
) a ON a.task_id = t.id
WHERE t.parent_id IS NULL
ORDER BY t.created_at DESC
`

type ListTasksRow struct {
	ID               int64              `json:"id"`
	Title            string             `json:"title"`
	Description      string             `json:"description"`
	Done             bool               `json:"done"`
	CreatedAt        time.Time          `json:"created_at"`
	UpdatedAt        time.Time          `json:"updated_at"`
	ProjectID        *int64             `json:"project_id"`
	AssigneeID       *int64             `json:"assignee_id"`
	StartDate        pgtype.Timestamptz `json:"start_date"`
	DueDate          pgtype.Timestamptz `json:"due_date"`
	Status           string             `json:"status"`
	ParentID         *int64             `json:"parent_id"`
	Recurrence       string             `json:"recurrence"`
	BaselineStart    pgtype.Timestamptz `json:"baseline_start"`
	BaselineDue      pgtype.Timestamptz `json:"baseline_due"`
	Priority         string             `json:"priority"`
	Tags             []string           `json:"tags"`
	ReminderSent     bool               `json:"reminder_sent"`
	EstimateMinutes  int32              `json:"estimate_minutes"`
	ProjectName      *string            `json:"project_name"`
	AssigneeName     *string            `json:"assignee_name"`
	SubtaskCount     int32              `json:"subtask_count"`
	SubtaskDoneCount int32              `json:"subtask_done_count"`
	AssigneeIds      []int64            `json:"assignee_ids"`
	AssigneeNames    []string           `json:"assignee_names"`
}

func (q *Queries) ListTasks(ctx context.Context) ([]ListTasksRow, error) {
	rows, err := q.db.Query(ctx, listTasks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTasksRow{}
	for rows.Next() {
		var i ListTasksRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.Done,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ProjectID,
			&i.AssigneeID,
			&i.StartDate,
			&i.DueDate,
			&i.Status,
			&i.ParentID,
			&i.Recurrence,
			&i.BaselineStart,
			&i.BaselineDue,
			&i.Priority,
			&i.Tags,
			&i.ReminderSent,
			&i.EstimateMinutes,
			&i.ProjectName,
			&i.AssigneeName,
			&i.SubtaskCount,
			&i.SubtaskDoneCount,
			&i.AssigneeIds,
			&i.AssigneeNames,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTasksRaw = `-- name: ListTasksRaw :many
SELECT id, title, description, done, created_at, updated_at, project_id, assignee_id, start_date, due_date, status, parent_id, recurrence, baseline_start, baseline_due, priority, tags, reminder_sent, estimate_minutes FROM tasks
`

func (q *Queries) ListTasksRaw(ctx context.Context) ([]Task, error) {
	rows, err := q.db.Query(ctx, listTasksRaw)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Task{}
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.Done,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ProjectID,
			&i.AssigneeID,
			&i.StartDate,
			&i.DueDate,
			&i.Status,
			&i.ParentID,
			&i.Recurrence,
			&i.BaselineStart,
			&i.BaselineDue,
			&i.Priority,
			&i.Tags,
			&i.ReminderSent,
			&i.EstimateMinutes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markReminded = `-- name: MarkReminded :exec
UPDATE tasks SET reminder_sent = TRUE WHERE id = $1
`

func (q *Queries) MarkReminded(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, markReminded, id)
	return err
}

const setBaseline = `-- name: SetBaseline :exec
UPDATE tasks
SET baseline_start = start_date,
    baseline_due   = due_date,
    updated_at     = now()
`

func (q *Queries) SetBaseline(ctx context.Context) error {
	_, err := q.db.Exec(ctx, setBaseline)
	return err
}

const setTaskDates = `-- name: SetTaskDates :exec
UPDATE tasks
SET start_date = $2,
    due_date   = $3,
    reminder_sent = FALSE,
    updated_at = now()
WHERE id = $1
`

type SetTaskDatesParams struct {
	ID        int64              `json:"id"`
	StartDate pgtype.Timestamptz `json:"start_date"`
	DueDate   pgtype.Timestamptz `json:"due_date"`
}

func (q *Queries) SetTaskDates(ctx context.Context, arg SetTaskDatesParams) error {
	_, err := q.db.Exec(ctx, setTaskDates, arg.ID, arg.StartDate, arg.DueDate)
	return err
}

const setTaskDone = `-- name: SetTaskDone :one
UPDATE tasks
SET done = $2,
    status = CASE WHEN $2 THEN 'done' ELSE 'todo' END,
    reminder_sent = CASE WHEN $2 THEN reminder_sent ELSE FALSE END,
    updated_at = now()
WHERE id = $1
RETURNING id, title, description, done, created_at, updated_at, project_id, assignee_id, start_date, due_date, status, parent_id, recurrence, baseline_start, baseline_due, priority, tags, reminder_sent, estimate_minutes
`

type SetTaskDoneParams struct {
	ID   int64 `json:"id"`
	Done bool  `json:"done"`
}

func (q *Queries) SetTaskDone(ctx context.Context, arg SetTaskDoneParams) (Task, error) {
	row := q.db.QueryRow(ctx, setTaskDone, arg.ID, arg.Done)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Done,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ProjectID,
		&i.AssigneeID,
		&i.StartDate,
		&i.DueDate,
		&i.Status,
		&i.ParentID,
		&i.Recurrence,
		&i.BaselineStart,
		&i.BaselineDue,
		&i.Priority,
		&i.Tags,
		&i.ReminderSent,
		&i.EstimateMinutes,
	)
	return i, err
}

const setTaskStatus = `-- name: SetTaskStatus :one
UPDATE tasks
SET status = $2,
    done   = ($2 = 'done'),
    updated_at = now()
WHERE id = $1
RETURNING id, title, description, done, created_at, updated_at, project_id, assignee_id, start_date, due_date, status, parent_id, recurrence, baseline_start, baseline_due, priority, tags, reminder_sent, estimate_minutes
`

type SetTaskStatusParams struct {
	ID     int64  `json:"id"`
	Status string `json:"status"`
}

func (q *Queries) SetTaskStatus(ctx context.Context, arg SetTaskStatusParams) (Task, error) {
	row := q.db.QueryRow(ctx, setTaskStatus, arg.ID, arg.Status)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Done,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ProjectID,
		&i.AssigneeID,
		&i.StartDate,
		&i.DueDate,
		&i.Status,
		&i.ParentID,
		&i.Recurrence,
		&i.BaselineStart,
		&i.BaselineDue,
		&i.Priority,
		&i.Tags,
		&i.ReminderSent,
		&i.EstimateMinutes,
	)
	return i, err
}

const updateTask = `-- name: UpdateTask :one
UPDATE tasks
SET title       = $2,
    description = $3,
    project_id  = $4,
    assignee_id = $5,
    start_date  = $6,
    due_date    = $7,
    status      = $8,
    recurrence  = $9,
    priority    = $10,
    tags        = $11,
    estimate_minutes = $12,
    done        = ($8 = 'done'),
    reminder_sent = FALSE,
    updated_at  = now()
WHERE id = $1
RETURNING id, title, description, done, created_at, updated_at, project_id, assignee_id, start_date, due_date, status, parent_id, recurrence, baseline_start, baseline_due, priority, tags, reminder_sent, estimate_minutes
`

type UpdateTaskParams struct {
	ID              int64              `json:"id"`
	Title           string             `json:"title"`
	Description     string             `json:"description"`
	ProjectID       *int64             `json:"project_id"`
	AssigneeID      *int64             `json:"assignee_id"`
	StartDate       pgtype.Timestamptz `json:"start_date"`
	DueDate         pgtype.Timestamptz `json:"due_date"`
	Status          string             `json:"status"`
	Recurrence      string             `json:"recurrence"`
	Priority        string             `json:"priority"`
	Tags            []string           `json:"tags"`
	EstimateMinutes int32              `json:"estimate_minutes"`
}

func (q *Queries) UpdateTask(ctx context.Context, arg UpdateTaskParams) (Task, error) {
	row := q.db.QueryRow(ctx, updateTask,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.ProjectID,
		arg.AssigneeID,
		arg.StartDate,
		arg.DueDate,
		arg.Status,
		arg.Recurrence,
		arg.Priority,
		arg.Tags,
		arg.EstimateMinutes,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Done,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ProjectID,
		&i.AssigneeID,
		&i.StartDate,
		&i.DueDate,
		&i.Status,
		&i.ParentID,
		&i.Recurrence,
		&i.BaselineStart,
		&i.BaselineDue,
		&i.Priority,
		&i.Tags,
		&i.ReminderSent,
		&i.EstimateMinutes,
	)
	return i, err
}
