// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: task_templates.sql

package db

import (
	"context"
)

const createTaskTemplate = `-- name: CreateTaskTemplate :one
INSERT INTO task_templates (
    name, title, description, status, priority, recurrence,
    estimate_minutes, tags, project_id, created_by
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, name, title, description, status, priority, recurrence, estimate_minutes, tags, project_id, created_by, created_at
`

type CreateTaskTemplateParams struct {
	Name            string   `json:"name"`
	Title           string   `json:"title"`
	Description     string   `json:"description"`
	Status          string   `json:"status"`
	Priority        string   `json:"priority"`
	Recurrence      string   `json:"recurrence"`
	EstimateMinutes int32    `json:"estimate_minutes"`
	Tags            []string `json:"tags"`
	ProjectID       *int64   `json:"project_id"`
	CreatedBy       *int64   `json:"created_by"`
}

func (q *Queries) CreateTaskTemplate(ctx context.Context, arg CreateTaskTemplateParams) (TaskTemplate, error) {
	row := q.db.QueryRow(ctx, createTaskTemplate,
		arg.Name,
		arg.Title,
		arg.Description,
		arg.Status,
		arg.Priority,
		arg.Recurrence,
		arg.EstimateMinutes,
		arg.Tags,
		arg.ProjectID,
		arg.CreatedBy,
	)
	var i TaskTemplate
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.Priority,
		&i.Recurrence,
		&i.EstimateMinutes,
		&i.Tags,
		&i.ProjectID,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const deleteTaskTemplate = `-- name: DeleteTaskTemplate :exec
DELETE FROM task_templates WHERE id = $1
`

func (q *Queries) DeleteTaskTemplate(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteTaskTemplate, id)
	return err
}

const listTaskTemplates = `-- name: ListTaskTemplates :many
SELECT id, name, title, description, status, priority, recurrence, estimate_minutes, tags, project_id, created_by, created_at FROM task_templates ORDER BY name, id
`

func (q *Queries) ListTaskTemplates(ctx context.Context) ([]TaskTemplate, error) {
	rows, err := q.db.Query(ctx, listTaskTemplates)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TaskTemplate{}
	for rows.Next() {
		var i TaskTemplate
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.Priority,
			&i.Recurrence,
			&i.EstimateMinutes,
			&i.Tags,
			&i.ProjectID,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
