// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: team.sql

package db

import (
	"context"
	"time"
)

const listMembers = `-- name: ListMembers :many
SELECT u.id,
       u.email,
       u.full_name,
       u.role,
       u.avatar,
       u.job_title,
       u.department,
       u.created_at,
       COALESCE(o.open, 0)::int AS open_tasks,
       COALESCE(d.done, 0)::int AS completed_tasks
FROM users u
LEFT JOIN (
    SELECT assignee_id, COUNT(*) AS open
    FROM tasks
    WHERE NOT done AND assignee_id IS NOT NULL
    GROUP BY assignee_id
) o ON o.assignee_id = u.id
LEFT JOIN (
    SELECT assignee_id, COUNT(*) AS done
    FROM tasks
    WHERE done AND assignee_id IS NOT NULL
    GROUP BY assignee_id
) d ON d.assignee_id = u.id
ORDER BY completed_tasks DESC, u.created_at ASC
`

type ListMembersRow struct {
	ID             int64     `json:"id"`
	Email          string    `json:"email"`
	FullName       string    `json:"full_name"`
	Role           string    `json:"role"`
	Avatar         string    `json:"avatar"`
	JobTitle       string    `json:"job_title"`
	Department     string    `json:"department"`
	CreatedAt      time.Time `json:"created_at"`
	OpenTasks      int32     `json:"open_tasks"`
	CompletedTasks int32     `json:"completed_tasks"`
}

func (q *Queries) ListMembers(ctx context.Context) ([]ListMembersRow, error) {
	rows, err := q.db.Query(ctx, listMembers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMembersRow{}
	for rows.Next() {
		var i ListMembersRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.FullName,
			&i.Role,
			&i.Avatar,
			&i.JobTitle,
			&i.Department,
			&i.CreatedAt,
			&i.OpenTasks,
			&i.CompletedTasks,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
