// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: timesheets.sql

package db

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const decideTimesheet = `-- name: DecideTimesheet :one
UPDATE timesheet_submissions
SET status = $1,
    approver_id = $2,
    decided_at = now()
WHERE id = $3
RETURNING id, user_id, week_start, status, minutes, note, approver_id, decided_at, submitted_at
`

type DecideTimesheetParams struct {
	Status     string `json:"status"`
	ApproverID *int64 `json:"approver_id"`
	ID         int64  `json:"id"`
}

func (q *Queries) DecideTimesheet(ctx context.Context, arg DecideTimesheetParams) (TimesheetSubmission, error) {
	row := q.db.QueryRow(ctx, decideTimesheet, arg.Status, arg.ApproverID, arg.ID)
	var i TimesheetSubmission
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.WeekStart,
		&i.Status,
		&i.Minutes,
		&i.Note,
		&i.ApproverID,
		&i.DecidedAt,
		&i.SubmittedAt,
	)
	return i, err
}

const listMyTimesheets = `-- name: ListMyTimesheets :many
SELECT t.id, t.user_id, t.week_start, t.status, t.minutes, t.note, t.approver_id, t.decided_at, t.submitted_at, COALESCE(a.full_name, '')::text AS approver_name
FROM timesheet_submissions t
LEFT JOIN users a ON a.id = t.approver_id
WHERE t.user_id = $1
ORDER BY t.week_start DESC
LIMIT 26
`

type ListMyTimesheetsRow struct {
	ID           int64              `json:"id"`
	UserID       int64              `json:"user_id"`
	WeekStart    time.Time          `json:"week_start"`
	Status       string             `json:"status"`
	Minutes      int32              `json:"minutes"`
	Note         string             `json:"note"`
	ApproverID   *int64             `json:"approver_id"`
	DecidedAt    pgtype.Timestamptz `json:"decided_at"`
	SubmittedAt  time.Time          `json:"submitted_at"`
	ApproverName string             `json:"approver_name"`
}

func (q *Queries) ListMyTimesheets(ctx context.Context, userID int64) ([]ListMyTimesheetsRow, error) {
	rows, err := q.db.Query(ctx, listMyTimesheets, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMyTimesheetsRow{}
	for rows.Next() {
		var i ListMyTimesheetsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.WeekStart,
			&i.Status,
			&i.Minutes,
			&i.Note,
			&i.ApproverID,
			&i.DecidedAt,
			&i.SubmittedAt,
			&i.ApproverName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingTimesheets = `-- name: ListPendingTimesheets :many
SELECT t.id, t.user_id, t.week_start, t.status, t.minutes, t.note, t.approver_id, t.decided_at, t.submitted_at, u.full_name AS user_name
FROM timesheet_submissions t
JOIN users u ON u.id = t.user_id
WHERE t.status = 'submitted'
ORDER BY t.submitted_at ASC
`

type ListPendingTimesheetsRow struct {
	ID          int64              `json:"id"`
	UserID      int64              `json:"user_id"`
	WeekStart   time.Time          `json:"week_start"`
	Status      string             `json:"status"`
	Minutes     int32              `json:"minutes"`
	Note        string             `json:"note"`
	ApproverID  *int64             `json:"approver_id"`
	DecidedAt   pgtype.Timestamptz `json:"decided_at"`
	SubmittedAt time.Time          `json:"submitted_at"`
	UserName    string             `json:"user_name"`
}

func (q *Queries) ListPendingTimesheets(ctx context.Context) ([]ListPendingTimesheetsRow, error) {
	rows, err := q.db.Query(ctx, listPendingTimesheets)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPendingTimesheetsRow{}
	for rows.Next() {
		var i ListPendingTimesheetsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.WeekStart,
			&i.Status,
			&i.Minutes,
			&i.Note,
			&i.ApproverID,
			&i.DecidedAt,
			&i.SubmittedAt,
			&i.UserName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const submitTimesheet = `-- name: SubmitTimesheet :one
INSERT INTO timesheet_submissions (
    user_id, week_start, minutes, note, status, submitted_at)
VALUES (
    $1, $2, $3,
    $4, 'submitted', now())
ON CONFLICT (user_id, week_start) DO UPDATE
    SET minutes = EXCLUDED.minutes,
        note = EXCLUDED.note,
        status = 'submitted',
        submitted_at = now(),
        approver_id = NULL,
        decided_at = NULL
RETURNING id, user_id, week_start, status, minutes, note, approver_id, decided_at, submitted_at
`

type SubmitTimesheetParams struct {
	UserID    int64     `json:"user_id"`
	WeekStart time.Time `json:"week_start"`
	Minutes   int32     `json:"minutes"`
	Note      string    `json:"note"`
}

func (q *Queries) SubmitTimesheet(ctx context.Context, arg SubmitTimesheetParams) (TimesheetSubmission, error) {
	row := q.db.QueryRow(ctx, submitTimesheet,
		arg.UserID,
		arg.WeekStart,
		arg.Minutes,
		arg.Note,
	)
	var i TimesheetSubmission
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.WeekStart,
		&i.Status,
		&i.Minutes,
		&i.Note,
		&i.ApproverID,
		&i.DecidedAt,
		&i.SubmittedAt,
	)
	return i, err
}

const weekMinutes = `-- name: WeekMinutes :one
SELECT COALESCE(SUM(minutes), 0)::int FROM time_entries
WHERE user_id = $1
  AND started_at >= $2
  AND started_at < $3
`

type WeekMinutesParams struct {
	UserID    int64     `json:"user_id"`
	WeekStart time.Time `json:"week_start"`
	WeekEnd   time.Time `json:"week_end"`
}

func (q *Queries) WeekMinutes(ctx context.Context, arg WeekMinutesParams) (int32, error) {
	row := q.db.QueryRow(ctx, weekMinutes, arg.UserID, arg.WeekStart, arg.WeekEnd)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}
