// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: time_entries.sql

package db

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTimeEntry = `-- name: CreateTimeEntry :one
INSERT INTO time_entries (user_id, task_id, minutes, started_at, ended_at,
                          description, billable)
VALUES ($1, $2, $3,
        $4, $4, $5,
        $6)
RETURNING id
`

type CreateTimeEntryParams struct {
	UserID      int64     `json:"user_id"`
	TaskID      *int64    `json:"task_id"`
	Minutes     int32     `json:"minutes"`
	StartedAt   time.Time `json:"started_at"`
	Description string    `json:"description"`
	Billable    bool      `json:"billable"`
}

func (q *Queries) CreateTimeEntry(ctx context.Context, arg CreateTimeEntryParams) (int64, error) {
	row := q.db.QueryRow(ctx, createTimeEntry,
		arg.UserID,
		arg.TaskID,
		arg.Minutes,
		arg.StartedAt,
		arg.Description,
		arg.Billable,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const deleteTimeEntry = `-- name: DeleteTimeEntry :exec
DELETE FROM time_entries WHERE id = $1 AND user_id = $2
`

type DeleteTimeEntryParams struct {
	ID     int64 `json:"id"`
	UserID int64 `json:"user_id"`
}

func (q *Queries) DeleteTimeEntry(ctx context.Context, arg DeleteTimeEntryParams) error {
	_, err := q.db.Exec(ctx, deleteTimeEntry, arg.ID, arg.UserID)
	return err
}

const getActiveTimer = `-- name: GetActiveTimer :one
SELECT te.id, te.user_id, te.task_id, te.minutes, te.started_at, te.ended_at,
       te.description, te.billable, te.created_at,
       COALESCE(t.title, '')::text AS task_title,
       COALESCE(u.full_name, '')::text AS user_name
FROM time_entries te
LEFT JOIN tasks t ON t.id = te.task_id
LEFT JOIN users u ON u.id = te.user_id
WHERE te.user_id = $1 AND te.ended_at IS NULL
ORDER BY te.started_at DESC
LIMIT 1
`

type GetActiveTimerRow struct {
	ID          int64              `json:"id"`
	UserID      int64              `json:"user_id"`
	TaskID      *int64             `json:"task_id"`
	Minutes     int32              `json:"minutes"`
	StartedAt   time.Time          `json:"started_at"`
	EndedAt     pgtype.Timestamptz `json:"ended_at"`
	Description string             `json:"description"`
	Billable    bool               `json:"billable"`
	CreatedAt   time.Time          `json:"created_at"`
	TaskTitle   string             `json:"task_title"`
	UserName    string             `json:"user_name"`
}

func (q *Queries) GetActiveTimer(ctx context.Context, userID int64) (GetActiveTimerRow, error) {
	row := q.db.QueryRow(ctx, getActiveTimer, userID)
	var i GetActiveTimerRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TaskID,
		&i.Minutes,
		&i.StartedAt,
		&i.EndedAt,
		&i.Description,
		&i.Billable,
		&i.CreatedAt,
		&i.TaskTitle,
		&i.UserName,
	)
	return i, err
}

const getTimeEntry = `-- name: GetTimeEntry :one
SELECT te.id, te.user_id, te.task_id, te.minutes, te.started_at, te.ended_at,
       te.description, te.billable, te.created_at,
       COALESCE(t.title, '')::text AS task_title,
       COALESCE(u.full_name, '')::text AS user_name
FROM time_entries te
LEFT JOIN tasks t ON t.id = te.task_id
LEFT JOIN users u ON u.id = te.user_id
WHERE te.id = $1
`

type GetTimeEntryRow struct {
	ID          int64              `json:"id"`
	UserID      int64              `json:"user_id"`
	TaskID      *int64             `json:"task_id"`
	Minutes     int32              `json:"minutes"`
	StartedAt   time.Time          `json:"started_at"`
	EndedAt     pgtype.Timestamptz `json:"ended_at"`
	Description string             `json:"description"`
	Billable    bool               `json:"billable"`
	CreatedAt   time.Time          `json:"created_at"`
	TaskTitle   string             `json:"task_title"`
	UserName    string             `json:"user_name"`
}

func (q *Queries) GetTimeEntry(ctx context.Context, id int64) (GetTimeEntryRow, error) {
	row := q.db.QueryRow(ctx, getTimeEntry, id)
	var i GetTimeEntryRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TaskID,
		&i.Minutes,
		&i.StartedAt,
		&i.EndedAt,
		&i.Description,
		&i.Billable,
		&i.CreatedAt,
		&i.TaskTitle,
		&i.UserName,
	)
	return i, err
}

const listTimeEntries = `-- name: ListTimeEntries :many
SELECT te.id, te.user_id, te.task_id, te.minutes, te.started_at, te.ended_at,
       te.description, te.billable, te.created_at,
       COALESCE(t.title, '')::text AS task_title,
       COALESCE(u.full_name, '')::text AS user_name
FROM time_entries te
LEFT JOIN tasks t ON t.id = te.task_id
LEFT JOIN users u ON u.id = te.user_id
WHERE te.user_id = $1
  AND te.started_at >= $2
  AND te.started_at < $3
ORDER BY te.started_at DESC
`

type ListTimeEntriesParams struct {
	UserID int64     `json:"user_id"`
	FromTs time.Time `json:"from_ts"`
	ToTs   time.Time `json:"to_ts"`
}

type ListTimeEntriesRow struct {
	ID          int64              `json:"id"`
	UserID      int64              `json:"user_id"`
	TaskID      *int64             `json:"task_id"`
	Minutes     int32              `json:"minutes"`
	StartedAt   time.Time          `json:"started_at"`
	EndedAt     pgtype.Timestamptz `json:"ended_at"`
	Description string             `json:"description"`
	Billable    bool               `json:"billable"`
	CreatedAt   time.Time          `json:"created_at"`
	TaskTitle   string             `json:"task_title"`
	UserName    string             `json:"user_name"`
}

func (q *Queries) ListTimeEntries(ctx context.Context, arg ListTimeEntriesParams) ([]ListTimeEntriesRow, error) {
	rows, err := q.db.Query(ctx, listTimeEntries, arg.UserID, arg.FromTs, arg.ToTs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTimeEntriesRow{}
	for rows.Next() {
		var i ListTimeEntriesRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.TaskID,
			&i.Minutes,
			&i.StartedAt,
			&i.EndedAt,
			&i.Description,
			&i.Billable,
			&i.CreatedAt,
			&i.TaskTitle,
			&i.UserName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const startTimer = `-- name: StartTimer :one
INSERT INTO time_entries (user_id, task_id, description, billable)
VALUES ($1, $2, $3,
        $4)
RETURNING id
`

type StartTimerParams struct {
	UserID      int64  `json:"user_id"`
	TaskID      *int64 `json:"task_id"`
	Description string `json:"description"`
	Billable    bool   `json:"billable"`
}

func (q *Queries) StartTimer(ctx context.Context, arg StartTimerParams) (int64, error) {
	row := q.db.QueryRow(ctx, startTimer,
		arg.UserID,
		arg.TaskID,
		arg.Description,
		arg.Billable,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const stopTimer = `-- name: StopTimer :one
UPDATE time_entries
SET ended_at = now(),
    minutes = GREATEST(
        1, ROUND(EXTRACT(EPOCH FROM (now() - started_at)) / 60.0)::int)
WHERE id = $1 AND user_id = $2 AND ended_at IS NULL
RETURNING id
`

type StopTimerParams struct {
	ID     int64 `json:"id"`
	UserID int64 `json:"user_id"`
}

func (q *Queries) StopTimer(ctx context.Context, arg StopTimerParams) (int64, error) {
	row := q.db.QueryRow(ctx, stopTimer, arg.ID, arg.UserID)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const updateTimeEntry = `-- name: UpdateTimeEntry :exec
UPDATE time_entries
SET task_id = $1, minutes = $2,
    started_at = $3, description = $4,
    billable = $5
WHERE id = $6 AND user_id = $7
`

type UpdateTimeEntryParams struct {
	TaskID      *int64    `json:"task_id"`
	Minutes     int32     `json:"minutes"`
	StartedAt   time.Time `json:"started_at"`
	Description string    `json:"description"`
	Billable    bool      `json:"billable"`
	ID          int64     `json:"id"`
	UserID      int64     `json:"user_id"`
}

func (q *Queries) UpdateTimeEntry(ctx context.Context, arg UpdateTimeEntryParams) error {
	_, err := q.db.Exec(ctx, updateTimeEntry,
		arg.TaskID,
		arg.Minutes,
		arg.StartedAt,
		arg.Description,
		arg.Billable,
		arg.ID,
		arg.UserID,
	)
	return err
}
