// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countUsers = `-- name: CountUsers :one
SELECT COUNT(*) FROM users
`

func (q *Queries) CountUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (email, password_hash, full_name)
VALUES ($1, $2, $3)
RETURNING id, email, password_hash, full_name, email_verified, created_at, updated_at, role, avatar, status, status_message, last_seen_at
`

type CreateUserParams struct {
	Email        string `json:"email"`
	PasswordHash string `json:"password_hash"`
	FullName     string `json:"full_name"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Email, arg.PasswordHash, arg.FullName)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.FullName,
		&i.EmailVerified,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Role,
		&i.Avatar,
		&i.Status,
		&i.StatusMessage,
		&i.LastSeenAt,
	)
	return i, err
}

const emailExists = `-- name: EmailExists :one
SELECT EXISTS (SELECT 1 FROM users WHERE email = $1)
`

func (q *Queries) EmailExists(ctx context.Context, email string) (bool, error) {
	row := q.db.QueryRow(ctx, emailExists, email)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, password_hash, full_name, email_verified, created_at, updated_at, role, avatar, status, status_message, last_seen_at FROM users
WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.FullName,
		&i.EmailVerified,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Role,
		&i.Avatar,
		&i.Status,
		&i.StatusMessage,
		&i.LastSeenAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, password_hash, full_name, email_verified, created_at, updated_at, role, avatar, status, status_message, last_seen_at FROM users
WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.FullName,
		&i.EmailVerified,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Role,
		&i.Avatar,
		&i.Status,
		&i.StatusMessage,
		&i.LastSeenAt,
	)
	return i, err
}

const listUserStatuses = `-- name: ListUserStatuses :many
SELECT id, status, status_message, last_seen_at FROM users
`

type ListUserStatusesRow struct {
	ID            int64              `json:"id"`
	Status        string             `json:"status"`
	StatusMessage string             `json:"status_message"`
	LastSeenAt    pgtype.Timestamptz `json:"last_seen_at"`
}

func (q *Queries) ListUserStatuses(ctx context.Context) ([]ListUserStatusesRow, error) {
	rows, err := q.db.Query(ctx, listUserStatuses)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUserStatusesRow{}
	for rows.Next() {
		var i ListUserStatusesRow
		if err := rows.Scan(
			&i.ID,
			&i.Status,
			&i.StatusMessage,
			&i.LastSeenAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markEmailVerified = `-- name: MarkEmailVerified :exec
UPDATE users
SET email_verified = TRUE, updated_at = now()
WHERE email = $1
`

func (q *Queries) MarkEmailVerified(ctx context.Context, email string) error {
	_, err := q.db.Exec(ctx, markEmailVerified, email)
	return err
}

const setLastSeen = `-- name: SetLastSeen :exec
UPDATE users SET last_seen_at = now() WHERE id = $1
`

func (q *Queries) SetLastSeen(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, setLastSeen, id)
	return err
}

const setUserAvatar = `-- name: SetUserAvatar :one
UPDATE users
SET avatar = $2, updated_at = now()
WHERE id = $1
RETURNING id, email, password_hash, full_name, email_verified, created_at, updated_at, role, avatar, status, status_message, last_seen_at
`

type SetUserAvatarParams struct {
	ID     int64  `json:"id"`
	Avatar string `json:"avatar"`
}

func (q *Queries) SetUserAvatar(ctx context.Context, arg SetUserAvatarParams) (User, error) {
	row := q.db.QueryRow(ctx, setUserAvatar, arg.ID, arg.Avatar)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.FullName,
		&i.EmailVerified,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Role,
		&i.Avatar,
		&i.Status,
		&i.StatusMessage,
		&i.LastSeenAt,
	)
	return i, err
}

const setUserRole = `-- name: SetUserRole :one
UPDATE users
SET role = $2, updated_at = now()
WHERE id = $1
RETURNING id, email, password_hash, full_name, email_verified, created_at, updated_at, role, avatar, status, status_message, last_seen_at
`

type SetUserRoleParams struct {
	ID   int64  `json:"id"`
	Role string `json:"role"`
}

func (q *Queries) SetUserRole(ctx context.Context, arg SetUserRoleParams) (User, error) {
	row := q.db.QueryRow(ctx, setUserRole, arg.ID, arg.Role)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.FullName,
		&i.EmailVerified,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Role,
		&i.Avatar,
		&i.Status,
		&i.StatusMessage,
		&i.LastSeenAt,
	)
	return i, err
}

const setUserStatus = `-- name: SetUserStatus :exec
UPDATE users
SET status = $2, status_message = $3, updated_at = now()
WHERE id = $1
`

type SetUserStatusParams struct {
	ID            int64  `json:"id"`
	Status        string `json:"status"`
	StatusMessage string `json:"status_message"`
}

func (q *Queries) SetUserStatus(ctx context.Context, arg SetUserStatusParams) error {
	_, err := q.db.Exec(ctx, setUserStatus, arg.ID, arg.Status, arg.StatusMessage)
	return err
}

const updatePassword = `-- name: UpdatePassword :exec
UPDATE users
SET password_hash = $2, updated_at = now()
WHERE email = $1
`

type UpdatePasswordParams struct {
	Email        string `json:"email"`
	PasswordHash string `json:"password_hash"`
}

func (q *Queries) UpdatePassword(ctx context.Context, arg UpdatePasswordParams) error {
	_, err := q.db.Exec(ctx, updatePassword, arg.Email, arg.PasswordHash)
	return err
}

const updateUserName = `-- name: UpdateUserName :one
UPDATE users
SET full_name = $2, updated_at = now()
WHERE id = $1
RETURNING id, email, password_hash, full_name, email_verified, created_at, updated_at, role, avatar, status, status_message, last_seen_at
`

type UpdateUserNameParams struct {
	ID       int64  `json:"id"`
	FullName string `json:"full_name"`
}

func (q *Queries) UpdateUserName(ctx context.Context, arg UpdateUserNameParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserName, arg.ID, arg.FullName)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.FullName,
		&i.EmailVerified,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Role,
		&i.Avatar,
		&i.Status,
		&i.StatusMessage,
		&i.LastSeenAt,
	)
	return i, err
}
