// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: watchers.sql

package db

import (
	"context"
)

const addWatcher = `-- name: AddWatcher :exec
INSERT INTO task_watchers (task_id, user_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type AddWatcherParams struct {
	TaskID int64 `json:"task_id"`
	UserID int64 `json:"user_id"`
}

func (q *Queries) AddWatcher(ctx context.Context, arg AddWatcherParams) error {
	_, err := q.db.Exec(ctx, addWatcher, arg.TaskID, arg.UserID)
	return err
}

const countWatchers = `-- name: CountWatchers :one
SELECT COUNT(*)::int FROM task_watchers WHERE task_id = $1
`

func (q *Queries) CountWatchers(ctx context.Context, taskID int64) (int32, error) {
	row := q.db.QueryRow(ctx, countWatchers, taskID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const isWatching = `-- name: IsWatching :one
SELECT EXISTS (
    SELECT 1 FROM task_watchers WHERE task_id = $1 AND user_id = $2
)
`

type IsWatchingParams struct {
	TaskID int64 `json:"task_id"`
	UserID int64 `json:"user_id"`
}

func (q *Queries) IsWatching(ctx context.Context, arg IsWatchingParams) (bool, error) {
	row := q.db.QueryRow(ctx, isWatching, arg.TaskID, arg.UserID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const removeWatcher = `-- name: RemoveWatcher :exec
DELETE FROM task_watchers WHERE task_id = $1 AND user_id = $2
`

type RemoveWatcherParams struct {
	TaskID int64 `json:"task_id"`
	UserID int64 `json:"user_id"`
}

func (q *Queries) RemoveWatcher(ctx context.Context, arg RemoveWatcherParams) error {
	_, err := q.db.Exec(ctx, removeWatcher, arg.TaskID, arg.UserID)
	return err
}

const watchedTaskIDs = `-- name: WatchedTaskIDs :many
SELECT task_id FROM task_watchers WHERE user_id = $1
ORDER BY created_at DESC
`

func (q *Queries) WatchedTaskIDs(ctx context.Context, userID int64) ([]int64, error) {
	rows, err := q.db.Query(ctx, watchedTaskIDs, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var task_id int64
		if err := rows.Scan(&task_id); err != nil {
			return nil, err
		}
		items = append(items, task_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const watcherIDs = `-- name: WatcherIDs :many
SELECT user_id FROM task_watchers WHERE task_id = $1
`

func (q *Queries) WatcherIDs(ctx context.Context, taskID int64) ([]int64, error) {
	rows, err := q.db.Query(ctx, watcherIDs, taskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var user_id int64
		if err := rows.Scan(&user_id); err != nil {
			return nil, err
		}
		items = append(items, user_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
